{{
    config(
        materialized='table',
        tags=['childhood_imms'])
}}

WITH ELIG AS (
SELECT 
p.PERSON_ID,
p.BIRTH_DATE_APPROX,
p.AGE,
p.AGE_DAYS_APPROX,
p.BORN_SEP_2022_FLAG,
p.BORN_JUL_2024_FLAG,
p.BORN_JAN_2025_FLAG,
p.FIRST_BDAY,
p.SECOND_BDAY,
p.THIRD_BDAY,
p.FIFTH_BDAY,
p.SIXTH_BDAY,
p.ELEVENTH_BDAY,
p.TWELFTH_BDAY,
p.THIRTEENTH_BDAY,
p.FOURTEENTH_BDAY,
p.SIXTEENTH_BDAY,
p.SEVENTEENTH_BDAY,
sched.VACCINE_ORDER,
sched.VACCINE_ID,
sched.VACCINE_NAME,
sched.DOSE_NUMBER,
sched.ELIGIBLE_AGE_FROM_DAYS,
sched.ELIGIBLE_AGE_TO_DAYS,
sched.MAXIMUM_AGE_DAYS,
DATE((BIRTH_DATE_APPROX + sched.ELIGIBLE_AGE_FROM_DAYS)) AS ELIGIBLE_FROM_DATE,
DATE((BIRTH_DATE_APPROX + sched.ELIGIBLE_AGE_TO_DAYS)) AS ELIGIBLE_TO_DATE,
CASE 
        WHEN AGE_DAYS_APPROX >= sched.eligible_age_from_days
             AND AGE_DAYS_APPROX <= sched.eligible_age_to_days THEN 'Yes' 
        ELSE 'No' 
    END AS CURRENTLY_ELIGIBLE
FROM {{ ref('int_childhood_imms_current_population') }} p
CROSS JOIN 
     {{ ref('stg_reference_imms_schedule_child_latest') }} sched
WHERE 
AGE_DAYS_APPROX >= (select min(ELIGIBLE_AGE_FROM_DAYS) from {{ ref('stg_reference_imms_schedule_child_latest') }}) 
)
SELECT 
PERSON_ID,
BIRTH_DATE_APPROX,
AGE,
AGE_DAYS_APPROX,
BORN_SEP_2022_FLAG,
BORN_JUL_2024_FLAG,
BORN_JAN_2025_FLAG,
FIRST_BDAY,
SECOND_BDAY,
THIRD_BDAY,
FIFTH_BDAY,
SIXTH_BDAY,
ELEVENTH_BDAY,
TWELFTH_BDAY,
THIRTEENTH_BDAY,
FOURTEENTH_BDAY,
SIXTEENTH_BDAY,
SEVENTEENTH_BDAY,
VACCINE_ORDER,
VACCINE_ID,
VACCINE_NAME,
DOSE_NUMBER,
ELIGIBLE_AGE_FROM_DAYS,
ELIGIBLE_AGE_TO_DAYS,
ELIGIBLE_FROM_DATE,
ELIGIBLE_TO_DATE,
MAXIMUM_AGE_DAYS,
CURRENTLY_ELIGIBLE,
CASE 
WHEN VACCINE_ID in ('6IN1_4','MMRV_1B','MMRV_2B') AND BORN_JUL_2024_FLAG = 'Yes' THEN 'Yes' 
WHEN VACCINE_ID in ('6IN1_4','MMRV_1B','MMRV_2B') AND BORN_JUL_2024_FLAG = 'No' THEN 'No'
WHEN VACCINE_ID in ('MMRV_1','MMRV_2') AND BORN_JAN_2025_FLAG = 'Yes' THEN 'Yes' 
WHEN VACCINE_ID in ('MMRV_1','MMRV_2') AND BORN_JAN_2025_FLAG = 'No' THEN 'No'
WHEN VACCINE_ID in ('MMRV_1C') AND BORN_SEP_2022_FLAG = 'Yes' THEN 'Yes' 
WHEN VACCINE_ID in ('MMRV_1C') AND BORN_SEP_2022_FLAG = 'No' THEN 'No'
ELSE 'Yes' END AS VACCINE_ELIGIBLE
from ELIG