{{
    config(
        materialized='table',
        tags=['childhood_imms'],
        cluster_by=['person_id'])
}}
SELECT DISTINCT
dem.PERSON_ID
,dem.BIRTH_DATE_APPROX
,dem.BIRTH_DATE_APPROX_END_OF_MONTH AS DOB_EOM
,dem.AGE_AT_LEAST
,dem.AGE 
,age.AGE_DAYS_APPROX
,CASE WHEN dem.BIRTH_DATE_APPROX >= '2024-07-01' THEN 'Yes'
ELSE 'No' END AS BORN_JUL_2024_FLAG
,CASE WHEN dem.BIRTH_DATE_APPROX >= '2025-01-01' THEN 'Yes'
ELSE 'No' END AS BORN_JAN_2025_FLAG
,dem.SEX AS GENDER
,DATEADD(YEAR,1,dem.BIRTH_DATE_APPROX) as FIRST_BDAY
,DATEADD(YEAR,2,dem.BIRTH_DATE_APPROX) as SECOND_BDAY
,DATEADD(YEAR,3,dem.BIRTH_DATE_APPROX) as THIRD_BDAY
,DATEADD(YEAR,5,dem.BIRTH_DATE_APPROX) as FIFTH_BDAY
,DATEADD(YEAR,6,dem.BIRTH_DATE_APPROX) as SIXTH_BDAY
,DATEADD(YEAR,11,dem.BIRTH_DATE_APPROX) as ELEVENTH_BDAY
,DATEADD(YEAR,12,dem.BIRTH_DATE_APPROX) as TWELFTH_BDAY
,DATEADD(YEAR,13,dem.BIRTH_DATE_APPROX) as THIRTEENTH_BDAY
,DATEADD(YEAR,14,dem.BIRTH_DATE_APPROX) as FOURTEENTH_BDAY
,DATEADD(YEAR,15,dem.BIRTH_DATE_APPROX) as FIFTEENTH_BDAY
,DATEADD(YEAR,16,dem.BIRTH_DATE_APPROX) as SIXTEENTH_BDAY
,DATEADD(YEAR,17,dem.BIRTH_DATE_APPROX) as SEVENTEENTH_BDAY
,CASE
WHEN dem.ETHNICITY_CATEGORY = 'Not Recorded' THEN 'Unknown'
ELSE dem.ETHNICITY_CATEGORY END AS ETHNICITY_CATEGORY
,CASE 
WHEN dem.ETHNICITY_CATEGORY = 'Asian' THEN 1
WHEN dem.ETHNICITY_CATEGORY = 'Black' THEN 2
WHEN dem.ETHNICITY_CATEGORY = 'Mixed' THEN 3
WHEN dem.ETHNICITY_CATEGORY = 'Other' THEN 4
WHEN dem.ETHNICITY_CATEGORY = 'White' THEN 5
WHEN dem.ETHNICITY_CATEGORY = 'Unknown' THEN 6
WHEN dem.ETHNICITY_CATEGORY = 'Not Recorded' THEN 6
END AS ETHCAT_ORDER 
,CASE
WHEN dem.ETHNICITY_SUBCATEGORY in ('Not Recorded','Not stated','Not Stated','Recorded Not Known','Refused') THEN 'Unknown'
ELSE dem.ETHNICITY_SUBCATEGORY END AS ETHNICITY_SUBCATEGORY
,CASE 
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Bangladeshi' THEN 1
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Chinese' THEN 2
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Indian' THEN 3
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Pakistani' THEN 4
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Other Asian' THEN 5
WHEN dem.ETHNICITY_SUBCATEGORY = 'Black: African' THEN 6
WHEN dem.ETHNICITY_SUBCATEGORY = 'Black: Caribbean' THEN 7
WHEN dem.ETHNICITY_SUBCATEGORY = 'Black: Other Black' THEN 8
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: White and Asian' THEN 9
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: White and Black African' THEN 10
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: White and Black Caribbean' THEN 11
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: Other Mixed' THEN 12
WHEN dem.ETHNICITY_SUBCATEGORY = 'Other: Arab' THEN 13
WHEN dem.ETHNICITY_SUBCATEGORY = 'Other: Other' THEN 14
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: British' THEN 15
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: Irish' THEN 16
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: Traveller' THEN 17
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: Other White' THEN 18
WHEN dem.ETHNICITY_SUBCATEGORY = 'Unknown' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Not Recorded' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Not stated' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Not Stated' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Recorded Not Known' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Refused' THEN 19
END AS ETHSUBCAT_ORDER
,CASE 
WHEN dem.ETHNICITY_GRANULAR = 'MENA' THEN 'Middle East and North African'
WHEN dem.ETHNICITY_GRANULAR in ('Muslim', 'Sikh') THEN 'Unknown'
WHEN dem.ETHNICITY_GRANULAR in ('Recorded Not Known', 'Refused', 'Not stated', 'Not Recorded','Not Stated') THEN 'Unknown'
WHEN dem.ETHNICITY_GRANULAR = 'Black - E.African Asian' THEN 'East African Asian'
WHEN dem.ETHNICITY_GRANULAR = 'Indo-Caribbean' THEN 'Caribbean Asian'
WHEN dem.ETHNICITY_GRANULAR = 'Cornish' THEN 'English'
WHEN dem.ETHNICITY_GRANULAR in ('Gypsy or Irish Traveller','Gypsy','Irish Traveller') THEN 'Gypsy or Irish Traveller'
WHEN dem.ETHNICITY_GRANULAR in ('Albanian/Serbian', 'Serbian') THEN 'Albanian or Serbian'
ELSE dem.ETHNICITY_GRANULAR END AS ETHNICITY_GRANULAR
,CASE WHEN dem.IMD_QUINTILE_19 IS NULL THEN 'Unknown' 
ELSE dem.IMD_QUINTILE_19 END AS IMD_QUINTILE
,CASE 
WHEN dem.IMD_QUINTILE_19 = 'Most Deprived' THEN 1
WHEN dem.IMD_QUINTILE_19 = 'Second Most Deprived' THEN 2
WHEN dem.IMD_QUINTILE_19 = 'Third Most Deprived' THEN 3
WHEN dem.IMD_QUINTILE_19 = 'Second Least Deprived' THEN 4
WHEN dem.IMD_QUINTILE_19 = 'Least Deprived' THEN 5
ELSE 6 END AS IMDQUINTILE_ORDER
,dem.IMD_DECILE_19 AS IMD_DECILE
,CASE 
WHEN m.LANGUAGE = 'Pushto' THEN 'Pashto' 
WHEN m.language in ('Makaton sign language','Sign language','British Sign Language') THEN 'Sign language'
WHEN m.language = 'Not Recorded' THEN 'Unknown'
ELSE m.LANGUAGE END AS MAIN_LANGUAGE
,dem.BOROUGH_REGISTERED AS PRACTICE_BOROUGH 
,dem.NEIGHBOURHOOD_REGISTERED AS PRACTICE_NEIGHBOURHOOD
,dem.PCN_NAME AS PRIMARY_CARE_NETWORK
,dem.PRACTICE_NAME AS GP_NAME
,dem.PRACTICE_CODE
,CASE WHEN dem.LOCAL_AUTHORITY_NAME  IS NULL THEN 'Unknown'
ELSE dem.LOCAL_AUTHORITY_NAME END as RESIDENTIAL_BOROUGH
,CASE WHEN dem.NEIGHBOURHOOD_RESIDENT IS NULL THEN 'Unknown' 
ELSE dem.NEIGHBOURHOOD_RESIDENT END as RESIDENTIAL_NEIGHBOURHOOD
,CASE WHEN la.RESIDENT_FLAG IS NULL THEN 'Unknown'
ELSE la.RESIDENT_FLAG END as RESIDENTIAL_LOC
,dem.WARD_CODE
,dem.WARD_NAME
,CASE WHEN l.PERSON_ID IS NULL  THEN 'No' ELSE 'Yes' END AS LAC_FLAG
FROM {{ ref('dim_person_demographics') }} dem
LEFT JOIN {{ ref('dim_person_age') }} age on age.PERSON_ID = dem.PERSON_ID
LEFT JOIN {{ ref('dim_looked_after_child') }}  l on l.PERSON_ID = dem.PERSON_ID
LEFT JOIN {{ ref('dim_person_main_language') }} m on m.PERSON_ID = dem.PERSON_ID
LEFT JOIN DEV__MODELLING.LOOKUP_NCL.LSOA_2021_WARD_2025_LOCAL_AUTHORITY_2025 la on la.LSOA_2021_CODE = dem.LSOA_CODE_21
WHERE dem.is_active = 'TRUE' 
AND dem.IS_DECEASED = FALSE
AND dem.age < 20
-- AND ICB_CODE = 'QMJ'