{{
    config(
        materialized='table',
        tags=['childhood_imms'])
}}
--define flag for new vaccines introduced in January 2026
with new_vacc_def as (
SELECT 
p.PERSON_ID,
p.BIRTH_DATE_APPROX,
p.AGE,
p.AGE_DAYS_APPROX,
p.BORN_SEP_2022_FLAG,
p.BORN_JUL_2024_FLAG,
p.BORN_JAN_2025_FLAG,
sched.VACCINE_ORDER,
sched.VACCINE_ID,
sched.VACCINE_NAME,
sched.DOSE_NUMBER,
sched.ELIGIBLE_AGE_FROM_DAYS,
sched.ELIGIBLE_AGE_TO_DAYS,
sched.MAXIMUM_AGE_DAYS,
DATE((BIRTH_DATE_APPROX + sched.ELIGIBLE_AGE_FROM_DAYS)) AS ELIGIBLE_FROM_DATE,
DATE((BIRTH_DATE_APPROX + sched.ELIGIBLE_AGE_TO_DAYS)) AS ELIGIBLE_TO_DATE,
--schedule change new vaccines added. Some started July 2025 and some started Jan 2026
CASE 
WHEN VACCINE_ID in ('PCV_1B') AND (BORN_JUL_2024_FLAG = 'Yes' OR BORN_JAN_2025_FLAG = 'Yes') THEN 'Yes' 
WHEN VACCINE_ID in ('MENB_2B') AND (BORN_JUL_2024_FLAG = 'Yes' OR BORN_JAN_2025_FLAG = 'Yes') THEN 'Yes' 
WHEN VACCINE_ID in ('6IN1_4') AND (BORN_JUL_2024_FLAG = 'Yes' OR BORN_JAN_2025_FLAG = 'Yes') THEN 'Yes' 
WHEN VACCINE_ID in ('MMRV_1','MMRV_2') AND BORN_JAN_2025_FLAG = 'Yes' THEN 'Yes' 
WHEN VACCINE_ID in ('MMRV_1B','MMRV_2B') AND BORN_JUL_2024_FLAG = 'Yes' THEN 'Yes' 
WHEN VACCINE_ID in ('MMRV_1C') AND BORN_SEP_2022_FLAG = 'Yes' THEN 'Yes' 
ELSE 'No' END AS NEW_VACCINE_APPLICABLE
FROM {{ ref('int_childhood_imms_current_population') }} p
--FROM MODELLING.OLIDS_PROGRAMME.INT_CHILDHOOD_IMMS_CURRENT_POPULATION p 
CROSS JOIN 
     {{ ref('stg_reference_imms_schedule_child_latest') }} sched
     --MODELLING.DBT_STAGING.STG_REFERENCE_IMMS_SCHEDULE_CHILD_LATEST sched
WHERE 
AGE_DAYS_APPROX >= (select min(ELIGIBLE_AGE_FROM_DAYS) 
from {{ ref('stg_reference_imms_schedule_child_latest') }}) 
--from MODELLING.DBT_STAGING.STG_REFERENCE_IMMS_SCHEDULE_CHILD_LATEST))
order by vaccine_id
)
--define currently eligible based on date only
,curr_elig as (
SELECT 
PERSON_ID,
BIRTH_DATE_APPROX,
AGE,
AGE_DAYS_APPROX,
BORN_SEP_2022_FLAG,
BORN_JUL_2024_FLAG,
BORN_JAN_2025_FLAG,
VACCINE_ORDER,
VACCINE_ID,
VACCINE_NAME,
DOSE_NUMBER,
ELIGIBLE_AGE_FROM_DAYS,
ELIGIBLE_AGE_TO_DAYS,
MAXIMUM_AGE_DAYS,
ELIGIBLE_FROM_DATE,
ELIGIBLE_TO_DATE,
NEW_VACCINE_APPLICABLE,
--currently eligible is purely defined by date. 
CASE 
WHEN AGE_DAYS_APPROX >= ELIGIBLE_AGE_FROM_DAYS
    AND AGE_DAYS_APPROX <= ELIGIBLE_AGE_TO_DAYS THEN 'Yes' ELSE 'No' 
    END AS CURRENTLY_ELIGIBLE
from new_vacc_def
)
--Add the nuances for discontinued and new vaccines to currently eligible flag
SELECT
PERSON_ID,
BIRTH_DATE_APPROX,
AGE,
AGE_DAYS_APPROX,
BORN_SEP_2022_FLAG,
BORN_JUL_2024_FLAG,
BORN_JAN_2025_FLAG,
VACCINE_ORDER,
VACCINE_ID,
VACCINE_NAME,
DOSE_NUMBER,
ELIGIBLE_AGE_FROM_DAYS,
ELIGIBLE_AGE_TO_DAYS,
MAXIMUM_AGE_DAYS,
ELIGIBLE_FROM_DATE,
ELIGIBLE_TO_DATE,
NEW_VACCINE_APPLICABLE,
CASE 
--MMR vaccines now discontinued
WHEN vaccine_name like 'MMR%' AND NEW_VACCINE_APPLICABLE = 'Yes' AND CURRENTLY_ELIGIBLE = 'Yes' THEN 'Yes'
WHEN vaccine_name like 'MMR%' AND NEW_VACCINE_APPLICABLE = 'No' AND CURRENTLY_ELIGIBLE = 'Yes' THEN 'No'
--HibMenC no longer offered for those born on or after July 2024. Replaced by 6IN1 Dose 4 at 18 mths
WHEN vaccine_name = 'Hib/MenC' AND (BORN_JUL_2024_FLAG = 'Yes' OR BORN_JAN_2025_FLAG = 'Yes') THEN 'No'
--PCV1 AND MENB2 switched timings after July 2025 applicable to those born on or after July 2024. PCV1 now at 16 weeks and MenB2 at 12 weeks
WHEN vaccine_id in ('PCV_1','MENB_2') AND NEW_VACCINE_APPLICABLE = 'Yes' AND CURRENTLY_ELIGIBLE = 'Yes' THEN 'Yes'
WHEN vaccine_id in ('PCV_1','MENB_2') AND (BORN_JUL_2024_FLAG = 'Yes' OR BORN_JAN_2025_FLAG = 'Yes') THEN 'No'
ELSE CURRENTLY_ELIGIBLE END AS CURRENTLY_ELIGIBLE
from curr_elig