{{
    config(
        description="Raw layer (Analyst-managed reference datasets and business rules in the MODELLING environment). 1:1 passthrough with cleaned column names. \nSource: MODELLING.LOOKUP_NCL.IMD_2019 \ndbt: source(''reference_lookup_ncl'', ''IMD_2019'') \nColumns:\n  LSOA_CODE_2011 -> lsoa_code_2011\n  LSOA_NAME_2011 -> lsoa_name_2011\n  LOCAL_AUTHORITY_DISTRICT_CODE_2019 -> local_authority_district_code_2019\n  LOCAL_AUTHORITY_DISTRICT_NAME_2019 -> local_authority_district_name_2019\n  INDEX_OF_MULTIPLE_DEPRIVATION_SCORE -> index_of_multiple_deprivation_score\n  INDEX_OF_MULTIPLE_DEPRIVATION_RANK -> index_of_multiple_deprivation_rank\n  INDEX_OF_MULTIPLE_DEPRIVATION_DECILE -> index_of_multiple_deprivation_decile\n  INCOME_SCORE -> income_score\n  INCOME_RANK -> income_rank\n  INCOME_DECILE -> income_decile\n  EMPLOYMENT_SCORE -> employment_score\n  EMPLOYMENT_RANK -> employment_rank\n  EMPLOYMENT_DECILE -> employment_decile\n  EDUCATION_SKILLS_AND_TRAINING_SCORE -> education_skills_and_training_score\n  EDUCATION_SKILLS_AND_TRAINING_RANK -> education_skills_and_training_rank\n  EDUCATION_SKILLS_AND_TRAINING_DECILE -> education_skills_and_training_decile\n  HEALTH_DEPRIVATION_AND_DISABILITY_SCORE -> health_deprivation_and_disability_score\n  HEALTH_DEPRIVATION_AND_DISABILITY_RANK -> health_deprivation_and_disability_rank\n  HEALTH_DEPRIVATION_AND_DISABILITY_DECILE -> health_deprivation_and_disability_decile\n  CRIME_SCORE -> crime_score\n  CRIME_RANK -> crime_rank\n  CRIME_DECILE -> crime_decile\n  BARRIERS_TO_HOUSING_AND_SERVICES_SCORE -> barriers_to_housing_and_services_score\n  BARRIERS_TO_HOUSING_AND_SERVICES_RANK -> barriers_to_housing_and_services_rank\n  BARRIERS_TO_HOUSING_AND_SERVICES_DECILE -> barriers_to_housing_and_services_decile\n  LIVING_ENVIRONMENT_SCORE -> living_environment_score\n  LIVING_ENVIRONMENT_RANK -> living_environment_rank\n  LIVING_ENVIRONMENT_DECILE -> living_environment_decile\n  INCOME_DEPRIVATION_AFFECTING_CHILDREN_INDEX_SCORE -> income_deprivation_affecting_children_index_score\n  INCOME_DEPRIVATION_AFFECTING_CHILDREN_INDEX_RANK -> income_deprivation_affecting_children_index_rank\n  INCOME_DEPRIVATION_AFFECTING_CHILDREN_INDEX_DECILE -> income_deprivation_affecting_children_index_decile\n  INCOME_DEPRIVATION_AFFECTING_OLDER_PEOPLE_SCORE -> income_deprivation_affecting_older_people_score\n  INCOME_DEPRIVATION_AFFECTING_OLDER_PEOPLE_RANK -> income_deprivation_affecting_older_people_rank\n  INCOME_DEPRIVATION_AFFECTING_OLDER_PEOPLE_DECILE -> income_deprivation_affecting_older_people_decile\n  CHILDREN_AND_YOUNG_PEOPLE_SUB-DOMAIN_SCORE -> children_and_young_people_sub_domain_score\n  CHILDREN_AND_YOUNG_PEOPLE_SUB-DOMAIN_RANK -> children_and_young_people_sub_domain_rank\n  CHILDREN_AND_YOUNG_PEOPLE_SUB-DOMAIN_DECILE -> children_and_young_people_sub_domain_decile\n  ADULT_SKILLS_SUB-DOMAIN_SCORE -> adult_skills_sub_domain_score\n  ADULT_SKILLS_SUB-DOMAIN_RANK -> adult_skills_sub_domain_rank\n  ADULT_SKILLS_SUB-DOMAIN_DECILE -> adult_skills_sub_domain_decile\n  GEOGRAPHICAL_BARRIERS_SUB-DOMAIN_SCORE -> geographical_barriers_sub_domain_score\n  GEOGRAPHICAL_BARRIERS_SUB-DOMAIN_RANK -> geographical_barriers_sub_domain_rank\n  GEOGRAPHICAL_BARRIERS_SUB-DOMAIN_DECILE -> geographical_barriers_sub_domain_decile\n  WIDER_BARRIERS_SUB-DOMAIN_SCORE -> wider_barriers_sub_domain_score\n  WIDER_BARRIERS_SUB-DOMAIN_RANK -> wider_barriers_sub_domain_rank\n  WIDER_BARRIERS_SUB-DOMAIN_DECILE -> wider_barriers_sub_domain_decile\n  INDOORS_SUB-DOMAIN_SCORE -> indoors_sub_domain_score\n  INDOORS_SUB-DOMAIN_RANK -> indoors_sub_domain_rank\n  INDOORS_SUB-DOMAIN_DECILE -> indoors_sub_domain_decile\n  OUTDOORS_SUB-DOMAIN_SCORE -> outdoors_sub_domain_score\n  OUTDOORS_SUB-DOMAIN_RANK -> outdoors_sub_domain_rank\n  OUTDOORS_SUB-DOMAIN_DECILE -> outdoors_sub_domain_decile\n  TOTAL_POPULATION_MID_2015 -> total_population_mid_2015\n  DEPENDENT_CHILDREN_AGED_0-15_MID_2015 -> dependent_children_aged_0_15_mid_2015\n  POPULATION_AGED_16-59_MID_2015 -> population_aged_16_59_mid_2015\n  OLDER_POPULATION_AGED_60_AND_OVER_MID_2015 -> older_population_aged_60_and_over_mid_2015\n  WORKING_AGE_POPULATION_18-59/64 -> working_age_population_18_59_64\n  INDEX_OF_MULTIPLE_DEPRIVATION_QUINTILE -> index_of_multiple_deprivation_quintile"
    )
}}
select
    "LSOA_CODE_2011" as lsoa_code_2011,
    "LSOA_NAME_2011" as lsoa_name_2011,
    "LOCAL_AUTHORITY_DISTRICT_CODE_2019" as local_authority_district_code_2019,
    "LOCAL_AUTHORITY_DISTRICT_NAME_2019" as local_authority_district_name_2019,
    "INDEX_OF_MULTIPLE_DEPRIVATION_SCORE" as index_of_multiple_deprivation_score,
    "INDEX_OF_MULTIPLE_DEPRIVATION_RANK" as index_of_multiple_deprivation_rank,
    "INDEX_OF_MULTIPLE_DEPRIVATION_DECILE" as index_of_multiple_deprivation_decile,
    "INCOME_SCORE" as income_score,
    "INCOME_RANK" as income_rank,
    "INCOME_DECILE" as income_decile,
    "EMPLOYMENT_SCORE" as employment_score,
    "EMPLOYMENT_RANK" as employment_rank,
    "EMPLOYMENT_DECILE" as employment_decile,
    "EDUCATION_SKILLS_AND_TRAINING_SCORE" as education_skills_and_training_score,
    "EDUCATION_SKILLS_AND_TRAINING_RANK" as education_skills_and_training_rank,
    "EDUCATION_SKILLS_AND_TRAINING_DECILE" as education_skills_and_training_decile,
    "HEALTH_DEPRIVATION_AND_DISABILITY_SCORE" as health_deprivation_and_disability_score,
    "HEALTH_DEPRIVATION_AND_DISABILITY_RANK" as health_deprivation_and_disability_rank,
    "HEALTH_DEPRIVATION_AND_DISABILITY_DECILE" as health_deprivation_and_disability_decile,
    "CRIME_SCORE" as crime_score,
    "CRIME_RANK" as crime_rank,
    "CRIME_DECILE" as crime_decile,
    "BARRIERS_TO_HOUSING_AND_SERVICES_SCORE" as barriers_to_housing_and_services_score,
    "BARRIERS_TO_HOUSING_AND_SERVICES_RANK" as barriers_to_housing_and_services_rank,
    "BARRIERS_TO_HOUSING_AND_SERVICES_DECILE" as barriers_to_housing_and_services_decile,
    "LIVING_ENVIRONMENT_SCORE" as living_environment_score,
    "LIVING_ENVIRONMENT_RANK" as living_environment_rank,
    "LIVING_ENVIRONMENT_DECILE" as living_environment_decile,
    "INCOME_DEPRIVATION_AFFECTING_CHILDREN_INDEX_SCORE" as income_deprivation_affecting_children_index_score,
    "INCOME_DEPRIVATION_AFFECTING_CHILDREN_INDEX_RANK" as income_deprivation_affecting_children_index_rank,
    "INCOME_DEPRIVATION_AFFECTING_CHILDREN_INDEX_DECILE" as income_deprivation_affecting_children_index_decile,
    "INCOME_DEPRIVATION_AFFECTING_OLDER_PEOPLE_SCORE" as income_deprivation_affecting_older_people_score,
    "INCOME_DEPRIVATION_AFFECTING_OLDER_PEOPLE_RANK" as income_deprivation_affecting_older_people_rank,
    "INCOME_DEPRIVATION_AFFECTING_OLDER_PEOPLE_DECILE" as income_deprivation_affecting_older_people_decile,
    "CHILDREN_AND_YOUNG_PEOPLE_SUB-DOMAIN_SCORE" as children_and_young_people_sub_domain_score,
    "CHILDREN_AND_YOUNG_PEOPLE_SUB-DOMAIN_RANK" as children_and_young_people_sub_domain_rank,
    "CHILDREN_AND_YOUNG_PEOPLE_SUB-DOMAIN_DECILE" as children_and_young_people_sub_domain_decile,
    "ADULT_SKILLS_SUB-DOMAIN_SCORE" as adult_skills_sub_domain_score,
    "ADULT_SKILLS_SUB-DOMAIN_RANK" as adult_skills_sub_domain_rank,
    "ADULT_SKILLS_SUB-DOMAIN_DECILE" as adult_skills_sub_domain_decile,
    "GEOGRAPHICAL_BARRIERS_SUB-DOMAIN_SCORE" as geographical_barriers_sub_domain_score,
    "GEOGRAPHICAL_BARRIERS_SUB-DOMAIN_RANK" as geographical_barriers_sub_domain_rank,
    "GEOGRAPHICAL_BARRIERS_SUB-DOMAIN_DECILE" as geographical_barriers_sub_domain_decile,
    "WIDER_BARRIERS_SUB-DOMAIN_SCORE" as wider_barriers_sub_domain_score,
    "WIDER_BARRIERS_SUB-DOMAIN_RANK" as wider_barriers_sub_domain_rank,
    "WIDER_BARRIERS_SUB-DOMAIN_DECILE" as wider_barriers_sub_domain_decile,
    "INDOORS_SUB-DOMAIN_SCORE" as indoors_sub_domain_score,
    "INDOORS_SUB-DOMAIN_RANK" as indoors_sub_domain_rank,
    "INDOORS_SUB-DOMAIN_DECILE" as indoors_sub_domain_decile,
    "OUTDOORS_SUB-DOMAIN_SCORE" as outdoors_sub_domain_score,
    "OUTDOORS_SUB-DOMAIN_RANK" as outdoors_sub_domain_rank,
    "OUTDOORS_SUB-DOMAIN_DECILE" as outdoors_sub_domain_decile,
    "TOTAL_POPULATION_MID_2015" as total_population_mid_2015,
    "DEPENDENT_CHILDREN_AGED_0-15_MID_2015" as dependent_children_aged_0_15_mid_2015,
    "POPULATION_AGED_16-59_MID_2015" as population_aged_16_59_mid_2015,
    "OLDER_POPULATION_AGED_60_AND_OVER_MID_2015" as older_population_aged_60_and_over_mid_2015,
    "WORKING_AGE_POPULATION_18-59/64" as working_age_population_18_59_64,
    "INDEX_OF_MULTIPLE_DEPRIVATION_QUINTILE" as index_of_multiple_deprivation_quintile
from {{ source('reference_lookup_ncl', 'IMD_2019') }}
