{{
    config(
        description="Raw layer (Residential information (ACORN)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.ACORN.dscro_mpi \ndbt: source(''acorn'', ''dscro_mpi'') \nColumns:\n  der_gbg_matching_dataset_ABP_or_PAF -> der_gbg_matching_dataset_abp_or_paf\n  der_Address_Residency_From -> der_address_residency_from\n  der_gbg_Address_Matching_Score -> der_gbg_address_matching_score\n  der_Address_Matching_Source -> der_address_matching_source\n  der_Birth_Month -> der_birth_month\n  caci_Acorn_Household_Type -> caci_acorn_household_type\n  CACI_Household_Acorn_Type_Description -> caci_household_acorn_type_description\n  caci_Acorn_Postcode_Type -> caci_acorn_postcode_type\n  caci_WellBeing_Postcode_Type -> caci_well_being_postcode_type\n  care_home_month -> care_home_month\n  der_Care_Home_Service_Type -> der_care_home_service_type\n  CareHome_Is_Active -> care_home_is_active\n  Carehome_CQC_Loc_ID -> carehome_cqc_loc_id\n  der_Care_Home_Longterm_Temporary_Patient -> der_care_home_longterm_temporary_patient\n  Carehome_ODS_Code -> carehome_ods_code\n  der_CQC_Care_Home_Specialises_in_Over65s -> der_cqc_care_home_specialises_in_over65s\n  der_Care_Home_Residence_Flag -> der_care_home_residence_flag\n  Pseudo_NHS_Number -> pseudo_nhs_number\n  Pseudo_Parent_UPRN -> pseudo_parent_uprn\n  Pseudo_Postcode -> pseudo_postcode\n  Pseudo_UPRN -> pseudo_uprn\n  der_Detained_Estates_Flag -> der_detained_estates_flag\n  der_Death_Month -> der_death_month\n  der_Age -> der_age\n  der_Care_Home_FlagMatch_Strength -> der_care_home_flag_match_strength\n  der_SICB_Code_Of_Registration -> der_sicb_code_of_registration\n  der_SICB_Code_Of_Residence -> der_sicb_code_of_residence\n  EPC_BuiltForm -> epc_built_form\n  EPC_Current_Energy_Efficiency -> epc_current_energy_efficiency\n  EPC_Current_Energy_Rating -> epc_current_energy_rating\n  EPC_Extension_Count -> epc_extension_count\n  EPC_Inspection_Date -> epc_inspection_date\n  EPC_Mechanical_Ventilation -> epc_mechanical_ventilation\n  EPC_Number_Of_Habitable_Rooms -> epc_number_of_habitable_rooms\n  EPC_Number_Of_Heated_Rooms -> epc_number_of_heated_rooms\n  EPC_Potential_Energy_Efficiency -> epc_potential_energy_efficiency\n  EPC_Potential_Energy_Rating -> epc_potential_energy_rating\n  EPC_Property_Type -> epc_property_type\n  EPC_Roof_Description -> epc_roof_description\n  EPC_Tenure -> epc_tenure\n  EPC_Wall_Description -> epc_wall_description\n  EPC_Window_Description -> epc_window_description\n  der_gbg_Address_Matching_Status -> der_gbg_address_matching_status\n  Gender -> gender\n  GP_Practice_Code -> gp_practice_code\n  der_HMRC_Property_Taxed_As_Holiday_Accommadation_Flag -> der_hmrc_property_taxed_as_holiday_accommadation_flag\n  der_Living_Alone_Flag -> der_living_alone_flag\n  der_Living_with_People_Over64_Flag -> der_living_with_people_over64_flag\n  der_Living_with_People_Under18_Flag -> der_living_with_people_under18_flag\n  der_ONS_LSOA2011 -> der_ons_lsoa2011\n  der_ONS_LSOA2021 -> der_ons_lsoa2021\n  der_gbg_match_step -> der_gbg_match_step\n  Number_Of_EPC_Certificates -> number_of_epc_certificates\n  OS_Build_Status -> os_build_status\n  os_UPRN_Property_Classification -> os_uprn_property_classification\n  os_UPRN_Property_Classification_Description -> os_uprn_property_classification_description\n  OS_Private_Outdoor_Space_Flag -> os_private_outdoor_space_flag\n  OS_Rural_Urban_Classification -> os_rural_urban_classification\n  OS_Rural_Urban_Code -> os_rural_urban_code\n  der_gbg_Postcode_Change_Type -> der_gbg_postcode_change_type\n  der_Potential_Homeless_Flag -> der_potential_homeless_flag\n  der_Potential_Student_Flag -> der_potential_student_flag\n  ri_flag -> ri_flag\n  der_Total_Household_Population -> der_total_household_population\n  dmic_RowCreatedDateTime -> dmic_row_created_date_time\n  dmic_RowIdentifier -> dmic_row_identifier\n  dmic_RowIsLatest -> dmic_row_is_latest\n  dmic_RowSupersededDateTime -> dmic_row_superseded_date_time\n  dmic_RowVersion -> dmic_row_version"
    )
}}
select
    "der_gbg_matching_dataset_ABP_or_PAF" as der_gbg_matching_dataset_abp_or_paf,
    "der_Address_Residency_From" as der_address_residency_from,
    "der_gbg_Address_Matching_Score" as der_gbg_address_matching_score,
    "der_Address_Matching_Source" as der_address_matching_source,
    "der_Birth_Month" as der_birth_month,
    "caci_Acorn_Household_Type" as caci_acorn_household_type,
    "CACI_Household_Acorn_Type_Description" as caci_household_acorn_type_description,
    "caci_Acorn_Postcode_Type" as caci_acorn_postcode_type,
    "caci_WellBeing_Postcode_Type" as caci_well_being_postcode_type,
    "care_home_month" as care_home_month,
    "der_Care_Home_Service_Type" as der_care_home_service_type,
    "CareHome_Is_Active" as care_home_is_active,
    "Carehome_CQC_Loc_ID" as carehome_cqc_loc_id,
    "der_Care_Home_Longterm_Temporary_Patient" as der_care_home_longterm_temporary_patient,
    "Carehome_ODS_Code" as carehome_ods_code,
    "der_CQC_Care_Home_Specialises_in_Over65s" as der_cqc_care_home_specialises_in_over65s,
    "der_Care_Home_Residence_Flag" as der_care_home_residence_flag,
    "Pseudo_NHS_Number" as pseudo_nhs_number,
    "Pseudo_Parent_UPRN" as pseudo_parent_uprn,
    "Pseudo_Postcode" as pseudo_postcode,
    "Pseudo_UPRN" as pseudo_uprn,
    "der_Detained_Estates_Flag" as der_detained_estates_flag,
    "der_Death_Month" as der_death_month,
    "der_Age" as der_age,
    "der_Care_Home_FlagMatch_Strength" as der_care_home_flag_match_strength,
    "der_SICB_Code_Of_Registration" as der_sicb_code_of_registration,
    "der_SICB_Code_Of_Residence" as der_sicb_code_of_residence,
    "EPC_BuiltForm" as epc_built_form,
    "EPC_Current_Energy_Efficiency" as epc_current_energy_efficiency,
    "EPC_Current_Energy_Rating" as epc_current_energy_rating,
    "EPC_Extension_Count" as epc_extension_count,
    "EPC_Inspection_Date" as epc_inspection_date,
    "EPC_Mechanical_Ventilation" as epc_mechanical_ventilation,
    "EPC_Number_Of_Habitable_Rooms" as epc_number_of_habitable_rooms,
    "EPC_Number_Of_Heated_Rooms" as epc_number_of_heated_rooms,
    "EPC_Potential_Energy_Efficiency" as epc_potential_energy_efficiency,
    "EPC_Potential_Energy_Rating" as epc_potential_energy_rating,
    "EPC_Property_Type" as epc_property_type,
    "EPC_Roof_Description" as epc_roof_description,
    "EPC_Tenure" as epc_tenure,
    "EPC_Wall_Description" as epc_wall_description,
    "EPC_Window_Description" as epc_window_description,
    "der_gbg_Address_Matching_Status" as der_gbg_address_matching_status,
    "Gender" as gender,
    "GP_Practice_Code" as gp_practice_code,
    "der_HMRC_Property_Taxed_As_Holiday_Accommadation_Flag" as der_hmrc_property_taxed_as_holiday_accommadation_flag,
    "der_Living_Alone_Flag" as der_living_alone_flag,
    "der_Living_with_People_Over64_Flag" as der_living_with_people_over64_flag,
    "der_Living_with_People_Under18_Flag" as der_living_with_people_under18_flag,
    "der_ONS_LSOA2011" as der_ons_lsoa2011,
    "der_ONS_LSOA2021" as der_ons_lsoa2021,
    "der_gbg_match_step" as der_gbg_match_step,
    "Number_Of_EPC_Certificates" as number_of_epc_certificates,
    "OS_Build_Status" as os_build_status,
    "os_UPRN_Property_Classification" as os_uprn_property_classification,
    "os_UPRN_Property_Classification_Description" as os_uprn_property_classification_description,
    "OS_Private_Outdoor_Space_Flag" as os_private_outdoor_space_flag,
    "OS_Rural_Urban_Classification" as os_rural_urban_classification,
    "OS_Rural_Urban_Code" as os_rural_urban_code,
    "der_gbg_Postcode_Change_Type" as der_gbg_postcode_change_type,
    "der_Potential_Homeless_Flag" as der_potential_homeless_flag,
    "der_Potential_Student_Flag" as der_potential_student_flag,
    "ri_flag" as ri_flag,
    "der_Total_Household_Population" as der_total_household_population,
    "dmic_RowCreatedDateTime" as dmic_row_created_date_time,
    "dmic_RowIdentifier" as dmic_row_identifier,
    "dmic_RowIsLatest" as dmic_row_is_latest,
    "dmic_RowSupersededDateTime" as dmic_row_superseded_date_time,
    "dmic_RowVersion" as dmic_row_version
from {{ source('acorn', 'dscro_mpi') }}
