-- Raw layer model for aic.STG_CCMS__INT_FLAGS
-- Source: "DATA_LAKE__NCL"."AIC_DEV"
-- Description: AIC pipelines
-- This is a 1:1 passthrough from source with standardized column names
select
    "PERSON_ID" as person_id,
    "ALCOHOLINTOXICATION" as alcoholintoxication,
    "HARMFULUSEOFALCOHOL" as harmfuluseofalcohol,
    "DISORDERCAUSEDBYALCOHOL" as disordercausedbyalcohol,
    "DEPRESSIVEDISORDER" as depressivedisorder,
    "ANXIETYDISORDER" as anxietydisorder,
    "NEUROSIS" as neurosis,
    "ATRIALFIBRILLATION" as atrialfibrillation,
    "MALIGNANTNEOPLASTICDISEASEEXCEPTSKIN" as malignantneoplasticdiseaseexceptskin,
    "MALIGNANTMELANOMA" as malignantmelanoma,
    "VIRALHEPATITISRPT" as viralhepatitisrpt,
    "CHRONICLIVERDISEASE" as chronicliverdisease,
    "COPD" as copd,
    "DEMENTIA" as dementia,
    "DIABETEST1" as diabetest1,
    "DIABETEST2" as diabetest2,
    "DISORDEROFPROSTATE" as disorderofprostate,
    "EPILEPSY" as epilepsy,
    "CONGESTIVECARDIACFAILURE" as congestivecardiacfailure,
    "IRRITABLEBOWELSYNDROME" as irritablebowelsyndrome,
    "DEVELOPMENTALACADEMICDISORDER" as developmentalacademicdisorder,
    "INTELLECTUALDISABILITY" as intellectualdisability,
    "COMPLETETRISOMY21SYNDROME" as completetrisomy21_syndrome,
    "MULTIPLESCLEROSIS" as multiplesclerosis,
    "PARKINSONISM" as parkinsonism,
    "PERIPHVASCDISEASELEG" as periphvascdiseaseleg,
    "SUBSTANCEMISUSE" as substancemisuse,
    "SCHIZOPHRENIADISORDER" as schizophreniadisorder,
    "BIPOLARDISORDER" as bipolardisorder,
    "ANTIDEPRESSANTMEDICATION" as antidepressantmedication,
    "ANXIOLYTICS" as anxiolytics,
    "LAXATIVES" as laxatives,
    "ANTIEPILEPTICMEDICATION" as antiepilepticmedication,
    "ANTISPASMEDICMEDICATION" as antispasmedicmedication,
    "ANALGESICSOROPIODSNOTMIGRAINEMEDICATION" as analgesicsoropiodsnotmigrainemedication,
    "ANTIEPILEPTICMEDICATIONEXCEPTBENZODIAZEPINES" as antiepilepticmedicationexceptbenzodiazepines,
    "LITHIUM" as lithium,
    "EGFR" as egfr
from {{ source('aic', 'STG_CCMS__INT_FLAGS') }}
