-- Raw layer model for aic.BASE_SUS__APC_SPELL_CRITICAL_CARE_CONSOLIDATED
-- Source: "DATA_LAKE__NCL"."AIC_DEV"
-- Description: AIC pipelines
-- This is a 1:1 passthrough from source with standardized column names
select
    "ROWNUMBER_ID" as rownumber_id,
    "PRIMARYKEY_ID" as primarykey_id,
    "CRITICAL_CARE_CONSOLIDATED_ID" as critical_care_consolidated_id,
    "IDENTIFIER_LOCAL_IDENTIFIER" as identifier_local_identifier,
    "IDENTIFIER_SUS_CC_PERIOD" as identifier_sus_cc_period,
    "IDENTIFIER_SUBMITTED_ON_EPISODE" as identifier_submitted_on_episode,
    "IDENTIFIER_CC_PERIOD_TYPE" as identifier_cc_period_type,
    "IDENTIFIER_CC_PERIOD_TYPE_NUMERIC" as identifier_cc_period_type_numeric,
    "ADMISSION_DATE" as admission_date,
    "ADMISSION_TIME" as admission_time,
    "ADMISSION_UNIT_FUNCTION" as admission_unit_function,
    "ADMISSION_UNIT_BED_CONFIGURATION" as admission_unit_bed_configuration,
    "ADMISSION_SOURCE" as admission_source,
    "ADMISSION_SOURCE_LOCATION" as admission_source_location,
    "DISCHARGE_DATE" as discharge_date,
    "DISCHARGE_TIME" as discharge_time,
    "DISCHARGE_STATUS" as discharge_status,
    "DISCHARGE_LOCATION" as discharge_location,
    "ORGAN_SUPPORT_DAYS_ADVANCED_RESPIRATORY" as organ_support_days_advanced_respiratory,
    "ORGAN_SUPPORT_DAYS_BASIC_RESPIRATORY" as organ_support_days_basic_respiratory,
    "ORGAN_SUPPORT_DAYS_ADVANCED_CARDIOVASCULAR" as organ_support_days_advanced_cardiovascular,
    "ORGAN_SUPPORT_DAYS_BASIC_CARDIOVASCULAR" as organ_support_days_basic_cardiovascular,
    "ORGAN_SUPPORT_DAYS_RENAL" as organ_support_days_renal,
    "ORGAN_SUPPORT_DAYS_NEUROLOGICAL" as organ_support_days_neurological,
    "ORGAN_SUPPORT_DAYS_GASTRO_INTESTINAL" as organ_support_days_gastro_intestinal,
    "ORGAN_SUPPORT_DAYS_DERMATOLOGICAL" as organ_support_days_dermatological,
    "ORGAN_SUPPORT_DAYS_LIVER" as organ_support_days_liver,
    "ORGAN_SUPPORT_DAYS_MAXIMUM_SYSTEMS" as organ_support_days_maximum_systems,
    "INTENSITY_SUPPORT_DAYS_LEVEL_2" as intensity_support_days_level_2,
    "INTENSITY_SUPPORT_DAYS_LEVEL_3" as intensity_support_days_level_3,
    "ADMISSION_GESTATION_LENGTH_AT_DELIVERY" as admission_gestation_length_at_delivery,
    "ADMISSION_TYPE" as admission_type,
    "DISCHARGE_READY_DATE" as discharge_ready_date,
    "DISCHARGE_READY_TIME" as discharge_ready_time,
    "DISCHARGE_DESTINATION" as discharge_destination,
    "DMIC_IMPORT_LOG_ID" as dmic_import_log_id
from {{ source('aic', 'BASE_SUS__APC_SPELL_CRITICAL_CARE_CONSOLIDATED') }}
