{{
    config(
        description="Raw layer (National submission from local authorities for adult social care (client level dataset)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.SOCIAL_CARE.Adult_Social_Care_CLD \ndbt: source(''adult_social_care_cld'', ''Adult_Social_Care_CLD'') \nColumns:\n  LA Code -> la_code\n  Reporting Period Start Date -> reporting_period_start_date\n  Reporting Period End Date -> reporting_period_end_date\n  Pseudo NHS Number -> pseudo_nhs_number\n  LA Person Unique Identifier -> la_person_unique_identifier\n  GP Practice Name -> gp_practice_name\n  GP Practice Code -> gp_practice_code\n  Gender -> gender\n  Ethnicity -> ethnicity\n  Client Type -> client_type\n  Primary Support Reason -> primary_support_reason\n  Accommodation Status -> accommodation_status\n  Employment Status -> employment_status\n  Has Unpaid Carer -> has_unpaid_carer\n  Autism Spectrum Disorder (ASD) -> autism_spectrum_disorder_asd\n  Visual Impairment -> visual_impairment\n  Hearing Impairment -> hearing_impairment\n  Dementia -> dementia\n  Client Funding Status -> client_funding_status\n  Event Type -> event_type\n  Event Reference -> event_reference\n  Event Start Date -> event_start_date\n  Event End Date -> event_end_date\n  Event Description -> event_description\n  Event Outcome -> event_outcome\n  Request: Route of Access -> request_route_of_access\n  Assessment Type -> assessment_type\n  Eligible Needs Identified -> eligible_needs_identified\n  Informal Carer involved in Assessment -> informal_carer_involved_in_assessment\n  Method of Assessment -> method_of_assessment\n  Total Hrs Caring per week -> total_hrs_caring_per_week\n  No. of adults being cared for -> no_of_adults_being_cared_for\n  Adult 1 Linked Person_ID -> adult_1_linked_person_id\n  Adult 2 Linked Person_ID -> adult_2_linked_person_id\n  Adult 3 Linked Person_ID -> adult_3_linked_person_id\n  Service Type -> service_type\n  Service Component -> service_component\n  Delivery Mechanism -> delivery_mechanism\n  Provider CQC Location Name -> provider_cqc_location_name\n  Provider CQC Location ID -> provider_cqc_location_id\n  Review Reason -> review_reason\n  Review Outcomes Achieved -> review_outcomes_achieved\n  Method of Review -> method_of_review\n  Unit Cost -> unit_cost\n  Cost Frequency (Unit Type) -> cost_frequency_unit_type\n  Planned units per week -> planned_units_per_week\n  Full cost client -> full_cost_client\n  dmAgeAtReportingPeriodStartDate -> dm_age_at_reporting_period_start_date\n  dmCcgOfPracticeFromNHSNumber -> dm_ccg_of_practice_from_nhs_number\n  dmCcgOfResidenceFromNHSNumber -> dm_ccg_of_residence_from_nhs_number\n  dmPracticeCodeFromNHSNumber -> dm_practice_code_from_nhs_number\n  dmPostCodeSectorFromSubmittedPostCode -> dm_post_code_sector_from_submitted_post_code\n  dmLsoaFromSubmittedPostcode -> dm_lsoa_from_submitted_postcode\n  dmLoadDate -> dm_load_date\n  dmYearAndMonthOfBirth -> dm_year_and_month_of_birth\n  dmYearAndMonthofDeath -> dm_year_and_monthof_death\n  dmCCGOfPracticeFromSubmittedPractice -> dm_ccg_of_practice_from_submitted_practice\n  dmCCGOfResidenceFromSubmittedPostcode -> dm_ccg_of_residence_from_submitted_postcode\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  dmIcbRegistrationSubmitted -> dm_icb_registration_submitted\n  dmIcbResidenceSubmitted -> dm_icb_residence_submitted\n  dmSubIcbRegistrationSubmitted -> dm_sub_icb_registration_submitted\n  dmSubIcbResidenceSubmitted -> dm_sub_icb_residence_submitted\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason\n  dmImportLogId -> dm_import_log_id\n  dmRowId -> dm_row_id\n  dmFlowId -> dm_flow_id\n  dmSubmittedFileName -> dm_submitted_file_name\n  dmSpecification -> dm_specification\n  dmReceivedDate -> dm_received_date"
    )
}}
select
    "LA Code" as la_code,
    "Reporting Period Start Date" as reporting_period_start_date,
    "Reporting Period End Date" as reporting_period_end_date,
    "Pseudo NHS Number" as pseudo_nhs_number,
    "LA Person Unique Identifier" as la_person_unique_identifier,
    "GP Practice Name" as gp_practice_name,
    "GP Practice Code" as gp_practice_code,
    "Gender" as gender,
    "Ethnicity" as ethnicity,
    "Client Type" as client_type,
    "Primary Support Reason" as primary_support_reason,
    "Accommodation Status" as accommodation_status,
    "Employment Status" as employment_status,
    "Has Unpaid Carer" as has_unpaid_carer,
    "Autism Spectrum Disorder (ASD)" as autism_spectrum_disorder_asd,
    "Visual Impairment" as visual_impairment,
    "Hearing Impairment" as hearing_impairment,
    "Dementia" as dementia,
    "Client Funding Status" as client_funding_status,
    "Event Type" as event_type,
    "Event Reference" as event_reference,
    "Event Start Date" as event_start_date,
    "Event End Date" as event_end_date,
    "Event Description" as event_description,
    "Event Outcome" as event_outcome,
    "Request: Route of Access" as request_route_of_access,
    "Assessment Type" as assessment_type,
    "Eligible Needs Identified" as eligible_needs_identified,
    "Informal Carer involved in Assessment" as informal_carer_involved_in_assessment,
    "Method of Assessment" as method_of_assessment,
    "Total Hrs Caring per week" as total_hrs_caring_per_week,
    "No. of adults being cared for" as no_of_adults_being_cared_for,
    "Adult 1 Linked Person_ID" as adult_1_linked_person_id,
    "Adult 2 Linked Person_ID" as adult_2_linked_person_id,
    "Adult 3 Linked Person_ID" as adult_3_linked_person_id,
    "Service Type" as service_type,
    "Service Component" as service_component,
    "Delivery Mechanism" as delivery_mechanism,
    "Provider CQC Location Name" as provider_cqc_location_name,
    "Provider CQC Location ID" as provider_cqc_location_id,
    "Review Reason" as review_reason,
    "Review Outcomes Achieved" as review_outcomes_achieved,
    "Method of Review" as method_of_review,
    "Unit Cost" as unit_cost,
    "Cost Frequency (Unit Type)" as cost_frequency_unit_type,
    "Planned units per week" as planned_units_per_week,
    "Full cost client" as full_cost_client,
    "dmAgeAtReportingPeriodStartDate" as dm_age_at_reporting_period_start_date,
    "dmCcgOfPracticeFromNHSNumber" as dm_ccg_of_practice_from_nhs_number,
    "dmCcgOfResidenceFromNHSNumber" as dm_ccg_of_residence_from_nhs_number,
    "dmPracticeCodeFromNHSNumber" as dm_practice_code_from_nhs_number,
    "dmPostCodeSectorFromSubmittedPostCode" as dm_post_code_sector_from_submitted_post_code,
    "dmLsoaFromSubmittedPostcode" as dm_lsoa_from_submitted_postcode,
    "dmLoadDate" as dm_load_date,
    "dmYearAndMonthOfBirth" as dm_year_and_month_of_birth,
    "dmYearAndMonthofDeath" as dm_year_and_monthof_death,
    "dmCCGOfPracticeFromSubmittedPractice" as dm_ccg_of_practice_from_submitted_practice,
    "dmCCGOfResidenceFromSubmittedPostcode" as dm_ccg_of_residence_from_submitted_postcode,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmIcbRegistrationSubmitted" as dm_icb_registration_submitted,
    "dmIcbResidenceSubmitted" as dm_icb_residence_submitted,
    "dmSubIcbRegistrationSubmitted" as dm_sub_icb_registration_submitted,
    "dmSubIcbResidenceSubmitted" as dm_sub_icb_residence_submitted,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "dmImportLogId" as dm_import_log_id,
    "dmRowId" as dm_row_id,
    "dmFlowId" as dm_flow_id,
    "dmSubmittedFileName" as dm_submitted_file_name,
    "dmSpecification" as dm_specification,
    "dmReceivedDate" as dm_received_date
from {{ source('adult_social_care_cld', 'Adult_Social_Care_CLD') }}
