{{
    config(
        description="Raw layer (Analyst-managed reference datasets and business rules). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE__NCL.ANALYST_MANAGED.EFI2_RULES \ndbt: source(''reference_analyst_managed'', ''EFI2_RULES'') \nColumns:\n  CODE -> code\n  DEFICIT -> deficit\n  DEFICIT_TYPE -> deficit_type\n  TIME_CONSTRAINT_DAYS -> time_constraint_days\n  TIME_CONSTRAINT_TYPE -> time_constraint_type\n  TIME_CONSTRAINT_DESCRIPTION -> time_constraint_description\n  MIN_AGE -> min_age\n  AGE_RESTRICTION_DESCRIPTION -> age_restriction_description\n  CATEGORY_NAME -> category_name\n  CATEGORY_ORDER -> category_order\n  CATEGORY_RANGE_START -> category_range_start\n  CATEGORY_RANGE_END -> category_range_end\n  CATEGORY_DESCRIPTION -> category_description\n  THRESHOLD_VALUE -> threshold_value\n  THRESHOLD_COMPARATOR -> threshold_comparator\n  THRESHOLD_DESCRIPTION -> threshold_description\n  THRESHOLD_UNIT -> threshold_unit\n  THRESHOLD_TYPE -> threshold_type\n  READINGS_REQUIRED -> readings_required\n  READINGS_TIMEFRAME -> readings_timeframe\n  SUPERSEDES -> supersedes\n  SUPERSEDED_BY -> superseded_by\n  HIERARCHY_LEVEL -> hierarchy_level\n  RESOLUTION_TEST -> resolution_test\n  RESOLUTION_THRESHOLD -> resolution_threshold\n  RESOLUTION_UNIT -> resolution_unit\n  RESOLUTION_GENDER_SPECIFIC -> resolution_gender_specific\n  RESOLUTION_MALE_THRESHOLD -> resolution_male_threshold\n  RESOLUTION_FEMALE_THRESHOLD -> resolution_female_threshold\n  VALIDATION_RULE -> validation_rule\n  VALIDATION_DESCRIPTION -> validation_description\n  EFI2_COEFFICIENT -> efi2_coefficient\n  EFI2_TRANSFORMED_COEFFICIENT -> efi2_transformed_coefficient\n  EFI_PLUS_FALLS_COEFFICIENT -> efi_plus_falls_coefficient\n  EFI_PLUS_CARE_HOME_COEFFICIENT -> efi_plus_care_home_coefficient\n  EFI_PLUS_MORTALITY_COEFFICIENT -> efi_plus_mortality_coefficient\n  EFI_PLUS_HOME_CARE_COEFFICIENT -> efi_plus_home_care_coefficient\n  SOURCE_INSTRUCTION -> source_instruction\n  RULE_PRIORITY -> rule_priority"
    )
}}
select
    "CODE" as code,
    "DEFICIT" as deficit,
    "DEFICIT_TYPE" as deficit_type,
    "TIME_CONSTRAINT_DAYS" as time_constraint_days,
    "TIME_CONSTRAINT_TYPE" as time_constraint_type,
    "TIME_CONSTRAINT_DESCRIPTION" as time_constraint_description,
    "MIN_AGE" as min_age,
    "AGE_RESTRICTION_DESCRIPTION" as age_restriction_description,
    "CATEGORY_NAME" as category_name,
    "CATEGORY_ORDER" as category_order,
    "CATEGORY_RANGE_START" as category_range_start,
    "CATEGORY_RANGE_END" as category_range_end,
    "CATEGORY_DESCRIPTION" as category_description,
    "THRESHOLD_VALUE" as threshold_value,
    "THRESHOLD_COMPARATOR" as threshold_comparator,
    "THRESHOLD_DESCRIPTION" as threshold_description,
    "THRESHOLD_UNIT" as threshold_unit,
    "THRESHOLD_TYPE" as threshold_type,
    "READINGS_REQUIRED" as readings_required,
    "READINGS_TIMEFRAME" as readings_timeframe,
    "SUPERSEDES" as supersedes,
    "SUPERSEDED_BY" as superseded_by,
    "HIERARCHY_LEVEL" as hierarchy_level,
    "RESOLUTION_TEST" as resolution_test,
    "RESOLUTION_THRESHOLD" as resolution_threshold,
    "RESOLUTION_UNIT" as resolution_unit,
    "RESOLUTION_GENDER_SPECIFIC" as resolution_gender_specific,
    "RESOLUTION_MALE_THRESHOLD" as resolution_male_threshold,
    "RESOLUTION_FEMALE_THRESHOLD" as resolution_female_threshold,
    "VALIDATION_RULE" as validation_rule,
    "VALIDATION_DESCRIPTION" as validation_description,
    "EFI2_COEFFICIENT" as efi2_coefficient,
    "EFI2_TRANSFORMED_COEFFICIENT" as efi2_transformed_coefficient,
    "EFI_PLUS_FALLS_COEFFICIENT" as efi_plus_falls_coefficient,
    "EFI_PLUS_CARE_HOME_COEFFICIENT" as efi_plus_care_home_coefficient,
    "EFI_PLUS_MORTALITY_COEFFICIENT" as efi_plus_mortality_coefficient,
    "EFI_PLUS_HOME_CARE_COEFFICIENT" as efi_plus_home_care_coefficient,
    "SOURCE_INSTRUCTION" as source_instruction,
    "RULE_PRIORITY" as rule_priority
from {{ source('reference_analyst_managed', 'EFI2_RULES') }}
