{{
    config(
        materialized='view'
    )
}}

SELECT
BASE.PERSON_ID,
CASE 
    WHEN BASE.GENDER IN ('Male','Female') THEN BASE.GENDER 
    ELSE 'Unknown' 
END AS GENDER,
BASE.AGE_BAND_10Y,
CASE 
    WHEN BASE.AGE_BAND_10Y = '0-9'THEN 1
    WHEN BASE.AGE_BAND_10Y = '10-19' THEN 2
    WHEN BASE.AGE_BAND_10Y = '20-29' THEN 3
    WHEN BASE.AGE_BAND_10Y = '30-39' THEN 4
    WHEN BASE.AGE_BAND_10Y = '40-49' THEN 5
    WHEN BASE.AGE_BAND_10Y = '50-59' THEN 6
    WHEN BASE.AGE_BAND_10Y = '60-69' THEN 7
    WHEN BASE.AGE_BAND_10Y = '70-79' THEN 8
    WHEN BASE.AGE_BAND_10Y = '80-89' THEN 9
    WHEN BASE.AGE_BAND_10Y = '90-99' THEN 10
    WHEN BASE.AGE_BAND_10Y = '100+' THEN 11   
END AS AGE_BAND_10Y_SORT_KEY,

BASE.AGE_BAND_5Y,
CASE    
    WHEN BASE.AGE_BAND_5Y = '0-4'THEN 1
    WHEN BASE.AGE_BAND_5Y = '5-9' THEN 2
    WHEN BASE.AGE_BAND_5Y = '10-14' THEN 3
    WHEN BASE.AGE_BAND_5Y = '15-19' THEN 4
    WHEN BASE.AGE_BAND_5Y = '20-24' THEN 5
    WHEN BASE.AGE_BAND_5Y = '25-29' THEN 6
    WHEN BASE.AGE_BAND_5Y = '30-34' THEN 7
    WHEN BASE.AGE_BAND_5Y = '35-39' THEN 8
    WHEN BASE.AGE_BAND_5Y = '40-44' THEN 9
    WHEN BASE.AGE_BAND_5Y = '45-49' THEN 10
    WHEN BASE.AGE_BAND_5Y = '50-54' THEN 11
    WHEN BASE.AGE_BAND_5Y = '55-59' THEN 12
    WHEN BASE.AGE_BAND_5Y = '60-64' THEN 13
    WHEN BASE.AGE_BAND_5Y = '65-69' THEN 14
    WHEN BASE.AGE_BAND_5Y = '70-74' THEN 15
    WHEN BASE.AGE_BAND_5Y = '75-79' THEN 16
    WHEN BASE.AGE_BAND_5Y = '80-84' THEN 17
    WHEN BASE.AGE_BAND_5Y = '85+'   THEN 18
END AS AGE_BAND_5Y_SORT_KEY,
BASE.ETHNICITY_CATEGORY,
CASE    
    WHEN BASE.ETHNICITY_CATEGORY= 'Asian' THEN 1
    WHEN BASE.ETHNICITY_CATEGORY= 'Black' THEN 2
    WHEN BASE.ETHNICITY_CATEGORY= 'White' THEN 3
    WHEN BASE.ETHNICITY_CATEGORY= 'Mixed' THEN 4
    WHEN BASE.ETHNICITY_CATEGORY= 'Other' THEN 5
    WHEN BASE.ETHNICITY_CATEGORY= 'Unknown' THEN 6
END AS ETHNICITY_CATEGORY_SORT_KEY,

BASE.ETHNICITY_SUBCATEGORY,
BASE.MAIN_LANGUAGE,

CASE
    WHEN BASE.PATIENT_LSOA IS NULL THEN 'Unknown' 
    ELSE BASE.PATIENT_LSOA 
END AS PATIENT_LSOA,

BASE.PATIENT_IMD_DECILE_19,
CASE    
    WHEN BASE.PATIENT_IMD_QUINTILE_19 IS NULL THEN 'Unknown' 
    ELSE BASE.PATIENT_IMD_QUINTILE_19 
END AS PATIENT_IMD_QUINTILE_19,

CASE    WHEN BASE.PATIENT_IMD_QUINTILE_19 = 'Least Deprived' THEN 5
        WHEN BASE.PATIENT_IMD_QUINTILE_19 = 'Second Least Deprived' THEN 4
        WHEN BASE.PATIENT_IMD_QUINTILE_19 = 'Third Most Deprived' THEN 3
        WHEN BASE.PATIENT_IMD_QUINTILE_19 = 'Second Most Deprived' THEN 2
        WHEN BASE.PATIENT_IMD_QUINTILE_19 = 'Most Deprived' THEN 1
END AS PATIENT_IMD_QUINTILE_19_SORT_KEY,

BASE.NEIGHBOURHOOD_RESIDENT AS PATIENT_NEIGHBOURHOOD,
BASE.NEIGHBOURHOOD_REGISTERED AS PRACTICE_NEIGHBOURHOOD,
BASE.BOROUGH_REGISTERED AS PRACTICE_BOROUGH,
BASE.PCN_NAME,
BASE.PRACTICE_CODE,
BASE.PRACTICE_NAME,
BASE.PRACTICE_LSOA,
BASE.WARD_CODE,
BASE.WARD_NAME,
BASE.PRACTICE_IMD_QUINTILE_19,
CASE 
    WHEN BASE.TOTAL_CONDITIONS > 0 THEN 'LTC patients' 
    ELSE 'Non-LTC patients' 
END AS CONDITION_NAME,
CASE 
    WHEN BASE.SMOKING_STATUS = 'Current Smoker' OR
        BASE.ALCOHOL_STATUS IN ('Higher Risk','Historical Alcohol Misuse Disorder','Active Alcohol Misuse Disorder','Increasing Risk','Possible Dependence') OR
        BASE.BMI_CATEGORY IN ('Obese Class I','Overweight','Obese Class II','Obese Class III') THEN 'Patients with risk factor' 
    ELSE 'Patients without risk factor' 
END AS RISK_FACTOR,
CASE WHEN BASE.AGE > 18 THEN 'Yes' ELSE 'No' END AS IS_PATIENT_19_AND_OVER,
CASE WHEN BASE.IS_ACTIVE = 'TRUE' THEN 'Yes' ELSE 'No' END AS IS_ACTIVE,
LISTSIZE.PRACTICE_NORMALISED_WEIGHTED_LIST_SIZE,
BASE.TOTAL_CONDITIONS AS TOTAL_LTC_CONDITIONS,
BASE.RISK_FACTOR_COUNT

--PS_C.POPSEG_CODE,
--PS_C.POPSEG_NAME

FROM {{ ref('population_health_needs_base') }} BASE

LEFT JOIN {{ ref('stg_reference_gp_weighted_list_size') }} LISTSIZE
ON BASE.PRACTICE_CODE = LISTSIZE.PRACTICE_CODE

WHERE BASE.IS_ACTIVE = 'TRUE' 

GROUP BY ALL