name: 'ncl_analytics'
version: '1.0'
config-version: 2

profile: 'ncl_analytics'

flags:
  partial_parse: true

# Display connection info when dbt runs start
on-run-start:
  - "{{ log('🔗 DBT CONNECTION: Role=' ~ target.role ~ ', Warehouse=' ~ target.warehouse ~ ', Database=' ~ target.database ~ ', Schema=' ~ target.schema ~ ', Target=' ~ target.name, info=True) }}"
  - "{% if flags.WHICH in ['run', 'build'] %}{{ ensure_governance_tags() }}{% endif %}"


target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

model-paths: ["models"]

# Configure dbt audit schema naming
vars:
  dbt_audit_schema: "test_audit"

  # Schema generation configuration
  # Domains listed here will have schema names automatically derived from subdomain folder structure
  # Pattern: {DOMAIN}_{SUBDOMAIN} e.g. models/modelling/olids/diagnoses/ → OLIDS_DIAGNOSES
  auto_schema_domains: ['olids']

  # Flu campaign configuration - Change these values to run for different campaign years
  flu_current_campaign: "Flu 2025-26"     # Current flu campaign (Supported: Flu 2023-24, Flu 2024-25, Flu 2025-26)
  flu_previous_campaign: "Flu 2024-25"    # Previous flu campaign (for year-over-year comparison)
  flu_audit_end_date: "CURRENT_DATE"      # Default audit end date

  # COVID campaign configuration - Multi-campaign support
  covid_current_autumn: "COVID Autumn 2025"    # Current autumn campaign
  covid_current_spring: "COVID Spring 2025"    # Current spring campaign
  covid_previous_autumn: "COVID Autumn 2024"   # Previous autumn campaign
  covid_previous_spring: "COVID Spring 2025"   # Previous spring campaign (for comparison)
  covid_audit_end_date: "2025-06-30"           # End of last completed campaign (spring 2025)

# Configure test failure storage (only for failures)
tests:
  +store_failures: false
  +schema: "test_audit"

models:
  ncl_analytics:
    +materialized: table
    +persist_docs:
      columns: true
    +post-hook: ["{{ grant_ownership_with_copy() }}"]
    +enabled: true

    # Raw layer - source data with minimal transformation
    raw:
      +materialized: view
      +database: "MODELLING"
      +schema: "DBT_RAW"
      +tags: ["raw"]
      +post-hook: ["{{ add_model_comment() }}"]

    # Staging layer - cleaned and standardised source data
    staging:
      +materialized: view
      +database: "MODELLING"
      +schema: "DBT_STAGING"
      +tags: ["staging"]
      +post-hook: ["{{ add_model_comment() }}"]
      olids:
        +meta:
          custom_message: "Includes OLIDS data - don't publish/share outputs without DAC approval"

    # Modelling layer - business logic and transformations
    modelling:
      +enabled: true
      +materialized: table
      +database: "MODELLING"
      +tags: ["modelling"]
      +post-hook: ["{{ add_model_comment() }}"]
      commissioning:
        +schema: "COMMISSIONING_MODELLING"
      olids:
        +meta:
          custom_message: "Includes OLIDS data - don't publish/share outputs without DAC approval"
      shared:
        +schema: "REFERENCE"

    # Reporting layer - aggregated and analytical models
    reporting:
      +enabled: true
      +materialized: table
      +database: "REPORTING"
      +tags: ["reporting"]
      +post-hook: ["{{ add_model_comment() }}"]
      commissioning:
        +schema: "COMMISSIONING_REPORTING"
      olids:
        +meta:
          custom_message: "Includes OLIDS data - don't publish/share outputs without DAC approval"
        # Schema names automatically derived from subdomain folder names via generate_schema_name macro
        definitions:
          +database: "{{ target.database.replace('MODELLING', 'REPORTING') }}"
      shared:
        +schema: "REFERENCE"

    # Published layer - production-ready datasets for end users
    published:
      +enabled: true
      +materialized: table
      +tags: ["published_reporting"]
      +post-hook: ["{{ add_model_comment() }}"]
      direct_care:
        +database: "PUBLISHED_REPORTING__DIRECT_CARE"
        olids:
          +meta:
            custom_message: "Includes OLIDS data - don't publish/share outputs without DAC approval"
          +schema: "OLIDS_PUBLISHED"
        C_LTCS:
          +meta:
            custom_message: "Requires access via application role - clinical programme team only."
          +schema: "C_LTCS"
        shared:
          +schema: "REFERENCE"
      secondary_use:
        +database: "PUBLISHED_REPORTING__SECONDARY_USE"
        commissioning:
          +schema: "COMMISSIONING_PUBLISHED"
        olids:
          +meta:
            custom_message: "Includes OLIDS data - don't publish/share outputs without DAC approval"
          +schema: "OLIDS_PUBLISHED"
          +post-hook:
            - "{{ add_model_comment() }}"
            - "{{ apply_snowflake_tag_if_tagged('secondary_use_opt_out', 'DATA_CATEGORY', 'PRIMARY_CARE_SECONDARY_USE') }}"
        shared:
          +schema: "REFERENCE"

seeds:
  ncl_analytics:
    +database: "MODELLING"
    +schema: "REFERENCE"
