name: 'ncl_analytics'
version: '1.0'
config-version: 2

profile: 'ncl_analytics'

# Display connection info when dbt runs start
on-run-start:
  - "{{ log('🔗 DBT CONNECTION: Role=' ~ target.role ~ ', Warehouse=' ~ target.warehouse ~ ', Database=' ~ target.database ~ ', Schema=' ~ target.schema ~ ', Target=' ~ target.name, info=True) }}"


target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

model-paths: ["models"]

# Configure dbt audit schema naming
vars:
  dbt_audit_schema: "test_audit"

  # Flu campaign configuration - Change these values to run for different campaign years
  flu_current_campaign: "flu_2025_26"     # Current flu campaign (flu_2023_24, flu_2024_25, flu_2025_26)
  flu_previous_campaign: "flu_2024_25"    # Previous flu campaign (for year-over-year comparison)
  flu_audit_end_date: "CURRENT_DATE"      # Default audit end date

  # COVID campaign configuration - Multi-campaign support
  covid_current_autumn: "covid_2025_autumn"    # Current autumn campaign
  covid_current_spring: "covid_2025_spring"    # Current spring campaign
  covid_previous_autumn: "covid_2024_autumn"   # Previous autumn campaign
  covid_previous_spring: "covid_2025_spring"   # Previous spring campaign (for comparison)
  covid_audit_end_date: "2025-06-30"           # End of last completed campaign (spring 2025)

# Configure test failure storage (only for failures)
tests:
  +store_failures: false
  +schema: "test_audit"

models:
  ncl_analytics:
    +materialized: table
    +persist_docs:
      columns: true
    +post-hook: ["{{ grant_ownership_with_copy() }}"]

    # Commissioning analytics models
    commissioning:
      staging:
        +materialized: view
        +database: "MODELLING"
        +schema: "DBT_STAGING"
        +tags: ["staging"]
        +post-hook: ["{{ add_model_comment() }}"]
      modelling:
        +materialized: table
        +database: "MODELLING"
        +schema: "COMMISSIONING_MODELLING"
        +post-hook: ["{{ add_model_comment() }}"]
      reporting:
        +materialized: table
        +database: "REPORTING"
        +schema: "COMMISSIONING_REPORTING"
        +post-hook: ["{{ add_model_comment() }}"]
      published_reporting_secondary_use:
        +materialized: table
        +database: "PUBLISHED_REPORTING__SECONDARY_USE"
        +schema: "COMMISSIONING_PUBLISHED"
        +post-hook: ["{{ add_model_comment() }}"]
    
    # OLIDS analytics models
    olids:
      staging:
        +materialized: view
        +database: "MODELLING"
        +schema: "DBT_STAGING"
        +tags: ["staging"]
        +post-hook: ["{{ add_model_comment() }}"]
      modelling:
        +materialized: table
        +database: "MODELLING"
        +post-hook: ["{{ add_model_comment() }}"]
        # Business area schema mappings based on OLIDS domains
        diagnoses:
          +schema: "OLIDS_DIAGNOSES"
        medications:
          +schema: "OLIDS_MEDICATIONS"
        observations:
          +schema: "OLIDS_OBSERVATIONS"
        organisation:
          +schema: "OLIDS_ORGANISATION"
        person_attributes:
          +schema: "OLIDS_PERSON_ATTRIBUTES"
        programme:
          +schema: "OLIDS_PROGRAMME"
        utilities:
          +schema: "OLIDS_UTILITIES"
      reporting:
        +materialized: table
        +database: "REPORTING"
        +post-hook: ["{{ add_model_comment() }}"]
        # Business area schema mappings for reporting models
        clinical_safety:
          +schema: "OLIDS_CLINICAL_SAFETY"
        data_quality:
          +schema: "OLIDS_DATA_QUALITY"
        definitions:
          +database: "{{ target.database.replace('MODELLING', 'REPORTING') }}"
          +schema: "OLIDS_DEFINITIONS"
        disease_registers:
          +schema: "OLIDS_DISEASE_REGISTERS"
        geography:
          +schema: "OLIDS_GEOGRAPHY"
        measures:
          +schema: "OLIDS_MEASURES"
        organisation:
          +schema: "OLIDS_ORGANISATION"
        person_analytics:
          +schema: "OLIDS_PERSON_ANALYTICS"
        person_demographics:
          +schema: "OLIDS_PERSON_DEMOGRAPHICS"
        person_status:
          +schema: "OLIDS_PERSON_STATUS"
        programme:
          +schema: "OLIDS_PROGRAMME"
      published_reporting_direct_care:
        +materialized: table
        +database: "PUBLISHED_REPORTING__DIRECT_CARE"
        +schema: "OLIDS_PUBLISHED"
        +post-hook: ["{{ add_model_comment() }}"]
      published_reporting_secondary_use:
        +materialized: table
        +database: "PUBLISHED_REPORTING__SECONDARY_USE"
        +schema: "OLIDS_PUBLISHED"
        +post-hook: ["{{ add_model_comment() }}"]
    
    # Shared models (reference data, utilities)
    shared:
      staging:
        +materialized: view
        +database: "MODELLING"
        +schema: "DBT_STAGING"
        +tags: ["staging"]
        +post-hook: ["{{ add_model_comment() }}"]
      modelling:
        +materialized: table
        +database: "MODELLING"
        +schema: "REFERENCE"
        +post-hook: ["{{ add_model_comment() }}"]
      reporting:
        +materialized: table
        +database: "REPORTING"
        +schema: "REFERENCE"
        +post-hook: ["{{ add_model_comment() }}"]
      published_reporting_direct_care:
        +materialized: table
        +database: "PUBLISHED_REPORTING__DIRECT_CARE"
        +schema: "REFERENCE"
        +post-hook: ["{{ add_model_comment() }}"]
      published_reporting_secondary_use:
        +materialized: table
        +database: "PUBLISHED_REPORTING__SECONDARY_USE"
        +schema: "REFERENCE"
        +post-hook: ["{{ add_model_comment() }}"]

seeds:
  ncl_analytics:
    +database: "MODELLING"
    +schema: "REFERENCE"
