# dbt profiles for NCL Analytics project
#
# This file is tracked in git (uses env_var() with defaults - no secrets stored).
# Set required environment variables in your .env file (see env.example).
#
# Targets:
#   dev            - Local dev (uses env vars for credentials)
#   prod           - Local prod (uses env vars for credentials)
#   snowflake-dev  - Snowflake native execution (empty credentials)
#   snowflake-prod - Snowflake native execution (empty credentials)

ncl_analytics:
  target: dev  # Default target for local dev
  outputs:
    # Local development targets (require env vars)
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"
      user: "{{ env_var('SNOWFLAKE_USER', '') }}"
      authenticator: externalbrowser
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ANALYST') }}"
      database: MODELLING
      schema: DBT_DEV
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', '') }}"
      threads: 16
      client_session_keep_alive: true
      query_tag: dbt_ncl_analytics_dev

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"
      user: "{{ env_var('SNOWFLAKE_USER', '') }}"
      authenticator: externalbrowser
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ANALYST') }}"
      database: MODELLING
      schema: DBT_PROD
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', '') }}"
      threads: 16
      client_session_keep_alive: true
      query_tag: dbt_ncl_analytics_prod

    # Snowflake native execution targets (empty credentials - runs in Snowflake context)
    snowflake-dev:
      type: snowflake
      account: ''
      user: ''
      role: DBT_ADMIN
      database: MODELLING
      schema: DBT_DEV
      warehouse: NCL_ANALYTICS_M
      threads: 16
      client_session_keep_alive: false
      query_tag: dbt_ncl_analytics_dev

    snowflake-prod:
      type: snowflake
      account: ''
      user: ''
      role: DBT_ADMIN
      database: MODELLING
      schema: DBT_PROD
      warehouse: NCL_ANALYTICS_M
      threads: 16
      client_session_keep_alive: false
      query_tag: dbt_ncl_analytics_prod
