{{
    config(
        materialized='view',
        tags=['adult_imms']
    )
}}
--Current practice list for all projects
SELECT DISTINCT BOROUGH_REGISTERED, NEIGHBOURHOOD_REGISTERED, PCN_NAME, PRACTICE_CODE, PRACTICE_NAME 
FROM REPORTING.OLIDS_PERSON_DEMOGRAPHICS.DIM_PERSON_DEMOGRAPHICS 
WHERE IS_ACTIVE=TRUE ORDER BY 1