-- Raw layer model for csds.CYP102ServiceTypeReferredTo
-- Source: "DATA_LAKE"."CSDS"
-- Description: Community services dataset
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "SERVICE REQUEST IDENTIFIER" as service_request_identifier,
    "CARE PROFESSIONAL TEAM LOCAL IDENTIFIER" as care_professional_team_local_identifier,
    "SERVICE OR TEAM TYPE REFERRED TO (COMMUNITY CARE)" as service_or_team_type_referred_to_community_care,
    "REFERRAL CLOSURE DATE" as referral_closure_date,
    "REFERRAL REJECTION DATE" as referral_rejection_date,
    "REFERRAL CLOSURE REASON" as referral_closure_reason,
    "REFERRAL REJECTION REASON" as referral_rejection_reason,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP102 UNIQUE ID" as cyp102_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UNIQUE SERVICE REQUEST IDENTIFIER" as unique_service_request_identifier,
    "UNIQUE CARE PROFESSIONAL TEAM LOCAL IDENTIFIER" as unique_care_professional_team_local_identifier,
    "AGE AT SERVICE REFERRAL CLOSURE" as age_at_service_referral_closure,
    "AGE AT SERVICE REFERRAL REJECTION" as age_at_service_referral_rejection,
    "AGE AT SERVICE REFERRAL CLOSURE (YEARS)" as age_at_service_referral_closure_years,
    "IC_AGE_AT_SERVICE_REFERRAL_CLOSURE" as ic_age_at_service_referral_closure,
    "AGE AT SERVICE REFERRAL REJECTION (YEARS)" as age_at_service_referral_rejection_years,
    "IC_AGE_AT_SERVICE_REFERRAL_REJECTION" as ic_age_at_service_referral_rejection,
    "RECORD START DATE" as record_start_date,
    "RECORD END DATE" as record_end_date,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (REFERRAL CLOSURE DATE)" as age_group_referral_closure_date,
    "AGE GROUP (REFERRAL REJECTION DATE)" as age_group_referral_rejection_date,
    "AGE BAND (REFERRAL CLOSURE DATE)" as age_band_referral_closure_date,
    "AGE BAND (REFERRAL REJECTION DATE)" as age_band_referral_rejection_date,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP102ServiceTypeReferredTo') }}
