{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS001MPI \ndbt: source(''mhsds'', ''MHS001MPI'') \nColumns:\n  SK -> sk\n  LocalPatientId -> local_patient_id\n  OrgIDLocalPatientId -> org_id_local_patient_id\n  OrgIDResidenceResp -> org_id_residence_resp\n  OrgIDEduEstab -> org_id_edu_estab\n  NHSNumber Pseudo -> nhs_number_pseudo\n  NHSNumberStatus -> nhs_number_status\n  PersonBirthDate Pseudo -> person_birth_date_pseudo\n  Postcode Pseudo -> postcode_pseudo\n  GenderIDCode -> gender_id_code\n  GenderSameAtBirth -> gender_same_at_birth\n  Gender -> gender\n  MaritalStatus -> marital_status\n  EthnicCategory -> ethnic_category\n  EthnicCategory2021 -> ethnic_category2021\n  LanguageCodePreferred -> language_code_preferred\n  PersDeathDate -> pers_death_date\n  RecordNumber -> record_number\n  MHS001UniqID -> mhs001_uniq_id\n  OrgIDProv -> org_id_prov\n  OrgIDCCGRes -> org_idccg_res\n  Person_ID -> person_id\n  UniqSubmissionID -> uniq_submission_id\n  AgeRepPeriodStart -> age_rep_period_start\n  AgeRepPeriodEnd -> age_rep_period_end\n  AgeDeath -> age_death\n  PostcodeDistrict -> postcode_district\n  DefaultPostcode Pseudo -> default_postcode_pseudo\n  LSOA2011 -> lsoa2011\n  LSOA -> lsoa\n  LSOA2021 -> lsoa2021\n  LADistrictAuth -> la_district_auth\n  County -> county\n  ElectoralWard -> electoral_ward\n  UniqMonthID -> uniq_month_id\n  NHSDEthnicity -> nhsd_ethnicity\n  PatMRecInRP -> pat_mrec_in_rp\n  RecordStartDate -> record_start_date\n  RecordEndDate -> record_end_date\n  CCGGPRes -> ccggp_res\n  IMDQuart -> imd_quart\n  EFFECTIVE_FROM -> effective_from\n  OrgIDICBRes -> org_idicb_res\n  OrgIDICSRes -> org_idics_res\n  EthnicityHigher -> ethnicity_higher\n  EthnicityLow -> ethnicity_low\n  LDAFlag -> lda_flag\n  STPICRECCCG -> stpicrecccg\n  RegionICRECCCG -> region_icrecccg\n  EmploymentNationalLatest -> employment_national_latest\n  EmploymentProviderLatest -> employment_provider_latest\n  AccommodationNationalLatest -> accommodation_national_latest\n  AccommodationProviderLatest -> accommodation_provider_latest\n  OrgIDSubICBLocResidence -> org_id_sub_icb_loc_residence\n  ICRECSUBICB -> icrecsubicb\n  ICRECCCG -> icrecccg\n  ICRECSUBICBNAME -> icrecsubicbname\n  ICRECCCGNAME -> icrecccgname\n  RegionICRECSUBICB -> region_icrecsubicb\n  RegionICRECSUBICBName -> region_icrecsubicb_name\n  ICRECICB -> icrecicb\n  ICRECICBName -> icrecicb_name\n  NHSEValidatedPostcode Pseudo -> nhse_validated_postcode_pseudo\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicOrgIDCCGGPPractice -> dmic_org_idccggp_practice\n  dmicEthnicCategoryGroup -> dmic_ethnic_category_group\n  dmicAgeGroupRPEndDate -> dmic_age_group_rp_end_date\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  Unique_LocalPatientId -> unique_local_patient_id\n  dmIcbRegistrationSubmitted -> dm_icb_registration_submitted\n  dmSubIcbRegistrationSubmitted -> dm_sub_icb_registration_submitted\n  dmIcbResidenceSubmitted -> dm_icb_residence_submitted\n  dmSubIcbResidenceSubmitted -> dm_sub_icb_residence_submitted\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "LocalPatientId" as local_patient_id,
    "OrgIDLocalPatientId" as org_id_local_patient_id,
    "OrgIDResidenceResp" as org_id_residence_resp,
    "OrgIDEduEstab" as org_id_edu_estab,
    "NHSNumber Pseudo" as nhs_number_pseudo,
    "NHSNumberStatus" as nhs_number_status,
    "PersonBirthDate Pseudo" as person_birth_date_pseudo,
    "Postcode Pseudo" as postcode_pseudo,
    "GenderIDCode" as gender_id_code,
    "GenderSameAtBirth" as gender_same_at_birth,
    "Gender" as gender,
    "MaritalStatus" as marital_status,
    "EthnicCategory" as ethnic_category,
    "EthnicCategory2021" as ethnic_category2021,
    "LanguageCodePreferred" as language_code_preferred,
    "PersDeathDate" as pers_death_date,
    "RecordNumber" as record_number,
    "MHS001UniqID" as mhs001_uniq_id,
    "OrgIDProv" as org_id_prov,
    "OrgIDCCGRes" as org_idccg_res,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "AgeRepPeriodStart" as age_rep_period_start,
    "AgeRepPeriodEnd" as age_rep_period_end,
    "AgeDeath" as age_death,
    "PostcodeDistrict" as postcode_district,
    "DefaultPostcode Pseudo" as default_postcode_pseudo,
    "LSOA2011" as lsoa2011,
    "LSOA" as lsoa,
    "LSOA2021" as lsoa2021,
    "LADistrictAuth" as la_district_auth,
    "County" as county,
    "ElectoralWard" as electoral_ward,
    "UniqMonthID" as uniq_month_id,
    "NHSDEthnicity" as nhsd_ethnicity,
    "PatMRecInRP" as pat_mrec_in_rp,
    "RecordStartDate" as record_start_date,
    "RecordEndDate" as record_end_date,
    "CCGGPRes" as ccggp_res,
    "IMDQuart" as imd_quart,
    "EFFECTIVE_FROM" as effective_from,
    "OrgIDICBRes" as org_idicb_res,
    "OrgIDICSRes" as org_idics_res,
    "EthnicityHigher" as ethnicity_higher,
    "EthnicityLow" as ethnicity_low,
    "LDAFlag" as lda_flag,
    "STPICRECCCG" as stpicrecccg,
    "RegionICRECCCG" as region_icrecccg,
    "EmploymentNationalLatest" as employment_national_latest,
    "EmploymentProviderLatest" as employment_provider_latest,
    "AccommodationNationalLatest" as accommodation_national_latest,
    "AccommodationProviderLatest" as accommodation_provider_latest,
    "OrgIDSubICBLocResidence" as org_id_sub_icb_loc_residence,
    "ICRECSUBICB" as icrecsubicb,
    "ICRECCCG" as icrecccg,
    "ICRECSUBICBNAME" as icrecsubicbname,
    "ICRECCCGNAME" as icrecccgname,
    "RegionICRECSUBICB" as region_icrecsubicb,
    "RegionICRECSUBICBName" as region_icrecsubicb_name,
    "ICRECICB" as icrecicb,
    "ICRECICBName" as icrecicb_name,
    "NHSEValidatedPostcode Pseudo" as nhse_validated_postcode_pseudo,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicOrgIDCCGGPPractice" as dmic_org_idccggp_practice,
    "dmicEthnicCategoryGroup" as dmic_ethnic_category_group,
    "dmicAgeGroupRPEndDate" as dmic_age_group_rp_end_date,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "dmIcbRegistrationSubmitted" as dm_icb_registration_submitted,
    "dmSubIcbRegistrationSubmitted" as dm_sub_icb_registration_submitted,
    "dmIcbResidenceSubmitted" as dm_icb_residence_submitted,
    "dmSubIcbResidenceSubmitted" as dm_sub_icb_residence_submitted,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS001MPI') }}
