{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS005PatInd \ndbt: source(''mhsds'', ''MHS005PatInd'') \nColumns:\n  SK -> sk\n  LocalPatientId -> local_patient_id\n  ConstSuperReqDueToDis -> const_super_req_due_to_dis\n  ParentalResp -> parental_resp\n  YoungCarer -> young_carer\n  LACStatus -> lac_status\n  LACLegalStatus -> lac_legal_status\n  EducationalAssessOutcome -> educational_assess_outcome\n  CPP -> cpp\n  ExBAFIndicator -> ex_baf_indicator\n  OffenceHistory -> offence_history\n  ProPsychDate -> pro_psych_date\n  EmerPsychDate -> emer_psych_date\n  ManPsychDate -> man_psych_date\n  PsychPrescDate -> psych_presc_date\n  PsychTreatDate -> psych_treat_date\n  ReasonableAdjustmentInd -> reasonable_adjustment_ind\n  IMCARequired -> imca_required\n  IMHARequired -> imha_required\n  IMCAAssigned -> imca_assigned\n  IMHAAssigned -> imha_assigned\n  LDStatus -> ld_status\n  AutismStatus -> autism_status\n  RecordNumber -> record_number\n  MHS005UniqID -> mhs005_uniq_id\n  OrgIDProv -> org_id_prov\n  Person_ID -> person_id\n  UniqSubmissionID -> uniq_submission_id\n  UniqMonthID -> uniq_month_id\n  EFFECTIVE_FROM -> effective_from\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  Unique_LocalPatientId -> unique_local_patient_id\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "LocalPatientId" as local_patient_id,
    "ConstSuperReqDueToDis" as const_super_req_due_to_dis,
    "ParentalResp" as parental_resp,
    "YoungCarer" as young_carer,
    "LACStatus" as lac_status,
    "LACLegalStatus" as lac_legal_status,
    "EducationalAssessOutcome" as educational_assess_outcome,
    "CPP" as cpp,
    "ExBAFIndicator" as ex_baf_indicator,
    "OffenceHistory" as offence_history,
    "ProPsychDate" as pro_psych_date,
    "EmerPsychDate" as emer_psych_date,
    "ManPsychDate" as man_psych_date,
    "PsychPrescDate" as psych_presc_date,
    "PsychTreatDate" as psych_treat_date,
    "ReasonableAdjustmentInd" as reasonable_adjustment_ind,
    "IMCARequired" as imca_required,
    "IMHARequired" as imha_required,
    "IMCAAssigned" as imca_assigned,
    "IMHAAssigned" as imha_assigned,
    "LDStatus" as ld_status,
    "AutismStatus" as autism_status,
    "RecordNumber" as record_number,
    "MHS005UniqID" as mhs005_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqMonthID" as uniq_month_id,
    "EFFECTIVE_FROM" as effective_from,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS005PatInd') }}
