{{
    config(
        description="Raw layer (Community services dataset). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.CSDS.CYP202CareActivity \ndbt: source(''csds'', ''CYP202CareActivity'') \nColumns:\n  SK -> sk\n  CARE ACTIVITY IDENTIFIER -> care_activity_identifier\n  CARE CONTACT IDENTIFIER -> care_contact_identifier\n  COMMUNITY CARE ACTIVITY TYPE -> community_care_activity_type\n  COMMUNITY CARE ACTIVITY TYPE CODE -> community_care_activity_type_code\n  CARE PROFESSIONAL LOCAL IDENTIFIER -> care_professional_local_identifier\n  CLINICAL CONTACT DURATION OF CARE ACTIVITY -> clinical_contact_duration_of_care_activity\n  PROCEDURE SCHEME IN USE (COMMUNITY CARE) -> procedure_scheme_in_use_community_care\n  PROCEDURE SCHEME IN USE -> procedure_scheme_in_use\n  CODED PROCEDURE (CLINICAL TERMINOLOGY) -> coded_procedure_clinical_terminology\n  FINDING SCHEME IN USE (COMMUNITY CARE) -> finding_scheme_in_use_community_care\n  FINDING SCHEME IN USE -> finding_scheme_in_use\n  CODED FINDING (CODED CLINICAL ENTRY) -> coded_finding_coded_clinical_entry\n  OBSERVATION SCHEME IN USE (COMMUNITY CARE) -> observation_scheme_in_use_community_care\n  OBSERVATION SCHEME IN USE -> observation_scheme_in_use\n  CODED OBSERVATION (CLINICAL TERMINOLOGY) -> coded_observation_clinical_terminology\n  OBSERVATION VALUE -> observation_value\n  UCUM UNIT OF MEASUREMENT -> ucum_unit_of_measurement\n  EFFECTIVE FROM -> effective_from\n  RECORD NUMBER -> record_number\n  CYP202 UNIQUE ID -> cyp202_unique_id\n  ORGANISATION IDENTIFIER (CODE OF PROVIDER) -> organisation_identifier_code_of_provider\n  ORGANISATION CODE (PROVIDER) -> organisation_code_provider\n  PERSON ID -> person_id\n  UNIQUE CSDS ID (PATIENT) -> unique_csds_id_patient\n  UNIQUE SUBMISSION ID -> unique_submission_id\n  BSP UNIQUE ID -> bsp_unique_id\n  UNIQUE CARE CONTACT IDENTIFIER -> unique_care_contact_identifier\n  UNIQUE CARE ACTIVITY IDENTIFIER -> unique_care_activity_identifier\n  UNIQUE MONTH ID -> unique_month_id\n  DERIVED BREASTFEEDING STATUS (MASTER) -> derived_breastfeeding_status_master\n  MAPPED SNOMED CT PROCEDURE CODE -> mapped_snomed_ct_procedure_code\n  MASTER SNOMED CT PROCEDURE CODE -> master_snomed_ct_procedure_code\n  MASTER SNOMED CT PROCEDURE PREFERRED TERM -> master_snomed_ct_procedure_preferred_term\n  MAPPED OPCS-4 PROCEDURE CODE -> mapped_opcs_4_procedure_code\n  MAPPED OPCS-4 PROCEDURE DESCRIPTION -> mapped_opcs_4_procedure_description\n  MAPPED SNOMED CT FINDING CODE -> mapped_snomed_ct_finding_code\n  MASTER SNOMED CT FINDING CODE -> master_snomed_ct_finding_code\n  MASTER SNOMED CT FINDING PREFERRED TERM -> master_snomed_ct_finding_preferred_term\n  MAPPED ICD-10 FINDING CODE -> mapped_icd_10_finding_code\n  MASTER ICD-10 FINDING CODE -> master_icd_10_finding_code\n  MASTER ICD-10 FINDING DESCRIPTION -> master_icd_10_finding_description\n  MAPPED SNOMED CT OBSERVATION CODE -> mapped_snomed_ct_observation_code\n  MASTER SNOMED CT OBSERVATION CODE -> master_snomed_ct_observation_code\n  MASTER SNOMED CT OBSERVATION PREFERRED TERM -> master_snomed_ct_observation_preferred_term\n  DERIVED PERSON HEIGHT -> derived_person_height\n  DERIVED PERSON WEIGHT -> derived_person_weight\n  dmicImportLogId -> dmic_import_log_id\n  dmicActivityDate -> dmic_activity_date\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicCCG -> dmic_ccg\n  Unique_CareProfessionalId_Local -> unique_care_professional_id_local\n  UniqueCYPHS_ID_Patient -> unique_cyphs_id_patient\n  FILE TYPE -> file_type\n  REPORTING PERIOD START DATE -> reporting_period_start_date\n  REPORTING PERIOD END DATE -> reporting_period_end_date"
    )
}}
select
    "SK" as sk,
    "CARE ACTIVITY IDENTIFIER" as care_activity_identifier,
    "CARE CONTACT IDENTIFIER" as care_contact_identifier,
    "COMMUNITY CARE ACTIVITY TYPE" as community_care_activity_type,
    "COMMUNITY CARE ACTIVITY TYPE CODE" as community_care_activity_type_code,
    "CARE PROFESSIONAL LOCAL IDENTIFIER" as care_professional_local_identifier,
    "CLINICAL CONTACT DURATION OF CARE ACTIVITY" as clinical_contact_duration_of_care_activity,
    "PROCEDURE SCHEME IN USE (COMMUNITY CARE)" as procedure_scheme_in_use_community_care,
    "PROCEDURE SCHEME IN USE" as procedure_scheme_in_use,
    "CODED PROCEDURE (CLINICAL TERMINOLOGY)" as coded_procedure_clinical_terminology,
    "FINDING SCHEME IN USE (COMMUNITY CARE)" as finding_scheme_in_use_community_care,
    "FINDING SCHEME IN USE" as finding_scheme_in_use,
    "CODED FINDING (CODED CLINICAL ENTRY)" as coded_finding_coded_clinical_entry,
    "OBSERVATION SCHEME IN USE (COMMUNITY CARE)" as observation_scheme_in_use_community_care,
    "OBSERVATION SCHEME IN USE" as observation_scheme_in_use,
    "CODED OBSERVATION (CLINICAL TERMINOLOGY)" as coded_observation_clinical_terminology,
    "OBSERVATION VALUE" as observation_value,
    "UCUM UNIT OF MEASUREMENT" as ucum_unit_of_measurement,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP202 UNIQUE ID" as cyp202_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UNIQUE CARE CONTACT IDENTIFIER" as unique_care_contact_identifier,
    "UNIQUE CARE ACTIVITY IDENTIFIER" as unique_care_activity_identifier,
    "UNIQUE MONTH ID" as unique_month_id,
    "DERIVED BREASTFEEDING STATUS (MASTER)" as derived_breastfeeding_status_master,
    "MAPPED SNOMED CT PROCEDURE CODE" as mapped_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE CODE" as master_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE PREFERRED TERM" as master_snomed_ct_procedure_preferred_term,
    "MAPPED OPCS-4 PROCEDURE CODE" as mapped_opcs_4_procedure_code,
    "MAPPED OPCS-4 PROCEDURE DESCRIPTION" as mapped_opcs_4_procedure_description,
    "MAPPED SNOMED CT FINDING CODE" as mapped_snomed_ct_finding_code,
    "MASTER SNOMED CT FINDING CODE" as master_snomed_ct_finding_code,
    "MASTER SNOMED CT FINDING PREFERRED TERM" as master_snomed_ct_finding_preferred_term,
    "MAPPED ICD-10 FINDING CODE" as mapped_icd_10_finding_code,
    "MASTER ICD-10 FINDING CODE" as master_icd_10_finding_code,
    "MASTER ICD-10 FINDING DESCRIPTION" as master_icd_10_finding_description,
    "MAPPED SNOMED CT OBSERVATION CODE" as mapped_snomed_ct_observation_code,
    "MASTER SNOMED CT OBSERVATION CODE" as master_snomed_ct_observation_code,
    "MASTER SNOMED CT OBSERVATION PREFERRED TERM" as master_snomed_ct_observation_preferred_term,
    "DERIVED PERSON HEIGHT" as derived_person_height,
    "DERIVED PERSON WEIGHT" as derived_person_weight,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicActivityDate" as dmic_activity_date,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "Unique_CareProfessionalId_Local" as unique_care_professional_id_local,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP202CareActivity') }}
