{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS204IndirectActivity \ndbt: source(''mhsds'', ''MHS204IndirectActivity'') \nColumns:\n  SK -> sk\n  ServiceRequestId -> service_request_id\n  IndirectActDate -> indirect_act_date\n  OtherCareProfTeamLocalID -> other_care_prof_team_local_id\n  CareProfTeamLocalId -> care_prof_team_local_id\n  IndirectActTime -> indirect_act_time\n  IndActPersCons -> ind_act_pers_cons\n  DurationIndirectAct -> duration_indirect_act\n  OrgIDComm -> org_id_comm\n  CareProfLocalId -> care_prof_local_id\n  IndActProcedure -> ind_act_procedure\n  CodeProcAndProcStatus -> code_proc_and_proc_status\n  CodeIndActProcAndProcStatus -> code_ind_act_proc_and_proc_status\n  FindSchemeInUse -> find_scheme_in_use\n  Finding -> finding\n  CodeFind -> code_find\n  RecordNumber -> record_number\n  MHS204UniqID -> mhs204_uniq_id\n  OrgIDProv -> org_id_prov\n  Person_ID -> person_id\n  UniqSubmissionID -> uniq_submission_id\n  UniqServReqID -> uniq_serv_req_id\n  UniqCareProfLocalID -> uniq_care_prof_local_id\n  UniqMonthID -> uniq_month_id\n  EFFECTIVE_FROM -> effective_from\n  MasterSnomedCTFindingCode -> master_snomed_ct_finding_code\n  AgeAtIndirectActivity -> age_at_indirect_activity\n  UniqOtherCareProfTeamLocalID -> uniq_other_care_prof_team_local_id\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "ServiceRequestId" as service_request_id,
    "IndirectActDate" as indirect_act_date,
    "OtherCareProfTeamLocalID" as other_care_prof_team_local_id,
    "CareProfTeamLocalId" as care_prof_team_local_id,
    "IndirectActTime" as indirect_act_time,
    "IndActPersCons" as ind_act_pers_cons,
    "DurationIndirectAct" as duration_indirect_act,
    "OrgIDComm" as org_id_comm,
    "CareProfLocalId" as care_prof_local_id,
    "IndActProcedure" as ind_act_procedure,
    "CodeProcAndProcStatus" as code_proc_and_proc_status,
    "CodeIndActProcAndProcStatus" as code_ind_act_proc_and_proc_status,
    "FindSchemeInUse" as find_scheme_in_use,
    "Finding" as finding,
    "CodeFind" as code_find,
    "RecordNumber" as record_number,
    "MHS204UniqID" as mhs204_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "UniqCareProfLocalID" as uniq_care_prof_local_id,
    "UniqMonthID" as uniq_month_id,
    "EFFECTIVE_FROM" as effective_from,
    "MasterSnomedCTFindingCode" as master_snomed_ct_finding_code,
    "AgeAtIndirectActivity" as age_at_indirect_activity,
    "UniqOtherCareProfTeamLocalID" as uniq_other_care_prof_team_local_id,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS204IndirectActivity') }}
