{{
    config(
        description="Raw layer (Community services dataset). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.CSDS.CYP501CodedImm \ndbt: source(''csds'', ''CYP501CodedImm'') \nColumns:\n  SK -> sk\n  LOCAL PATIENT IDENTIFIER (EXTENDED) -> local_patient_identifier_extended\n  IMMUNISATION DATE -> immunisation_date\n  PROCEDURE SCHEME IN USE (COMMUNITY CARE) -> procedure_scheme_in_use_community_care\n  PROCEDURE SCHEME IN USE -> procedure_scheme_in_use\n  IMMUNISATION PROCEDURE (CLINICAL TERMINOLOGY) -> immunisation_procedure_clinical_terminology\n  ORGANISATION IDENTIFIER (IMMUNISATION RESPONSIBLE ORGANISATION) -> organisation_identifier_immunisation_responsible_organisation\n  ORGANISATION CODE (IMMUNISATION RESPONSIBLE ORGANISATION) -> organisation_code_immunisation_responsible_organisation\n  EFFECTIVE FROM -> effective_from\n  RECORD NUMBER -> record_number\n  CYP501 UNIQUE ID -> cyp501_unique_id\n  ORGANISATION IDENTIFIER (CODE OF PROVIDER) -> organisation_identifier_code_of_provider\n  ORGANISATION CODE (PROVIDER) -> organisation_code_provider\n  PERSON ID -> person_id\n  UNIQUE CSDS ID (PATIENT) -> unique_csds_id_patient\n  UNIQUE SUBMISSION ID -> unique_submission_id\n  BSP UNIQUE ID -> bsp_unique_id\n  AGE AT IMMUNISATION DATE -> age_at_immunisation_date\n  SCHOOL YEAR AT IMMUNISATION DATE -> school_year_at_immunisation_date\n  AGE AT IMMUNISATION DATE (YEARS) -> age_at_immunisation_date_years\n  IC_AGE_AT_IMMUNISATION_DATE -> ic_age_at_immunisation_date\n  RECORD START DATE -> record_start_date\n  RECORD END DATE -> record_end_date\n  UNIQUE MONTH ID -> unique_month_id\n  AGE GROUP (IMMUNISATION DATE) -> age_group_immunisation_date\n  AGE BAND (IMMUNISATION DATE) -> age_band_immunisation_date\n  MAPPED SNOMED CT PROCEDURE CODE -> mapped_snomed_ct_procedure_code\n  MASTER SNOMED CT PROCEDURE CODE -> master_snomed_ct_procedure_code\n  MASTER SNOMED CT PROCEDURE PREFERRED TERM -> master_snomed_ct_procedure_preferred_term\n  MAPPED OPCS-4 PROCEDURE CODE -> mapped_opcs_4_procedure_code\n  MAPPED OPCS-4 PROCEDURE DESCRIPTION -> mapped_opcs_4_procedure_description\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicCCG -> dmic_ccg\n  Unique_LocalPatientId -> unique_local_patient_id\n  UniqueCYPHS_ID_Patient -> unique_cyphs_id_patient\n  FILE TYPE -> file_type\n  REPORTING PERIOD START DATE -> reporting_period_start_date\n  REPORTING PERIOD END DATE -> reporting_period_end_date"
    )
}}
select
    "SK" as sk,
    "LOCAL PATIENT IDENTIFIER (EXTENDED)" as local_patient_identifier_extended,
    "IMMUNISATION DATE" as immunisation_date,
    "PROCEDURE SCHEME IN USE (COMMUNITY CARE)" as procedure_scheme_in_use_community_care,
    "PROCEDURE SCHEME IN USE" as procedure_scheme_in_use,
    "IMMUNISATION PROCEDURE (CLINICAL TERMINOLOGY)" as immunisation_procedure_clinical_terminology,
    "ORGANISATION IDENTIFIER (IMMUNISATION RESPONSIBLE ORGANISATION)" as organisation_identifier_immunisation_responsible_organisation,
    "ORGANISATION CODE (IMMUNISATION RESPONSIBLE ORGANISATION)" as organisation_code_immunisation_responsible_organisation,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP501 UNIQUE ID" as cyp501_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "AGE AT IMMUNISATION DATE" as age_at_immunisation_date,
    "SCHOOL YEAR AT IMMUNISATION DATE" as school_year_at_immunisation_date,
    "AGE AT IMMUNISATION DATE (YEARS)" as age_at_immunisation_date_years,
    "IC_AGE_AT_IMMUNISATION_DATE" as ic_age_at_immunisation_date,
    "RECORD START DATE" as record_start_date,
    "RECORD END DATE" as record_end_date,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (IMMUNISATION DATE)" as age_group_immunisation_date,
    "AGE BAND (IMMUNISATION DATE)" as age_band_immunisation_date,
    "MAPPED SNOMED CT PROCEDURE CODE" as mapped_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE CODE" as master_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE PREFERRED TERM" as master_snomed_ct_procedure_preferred_term,
    "MAPPED OPCS-4 PROCEDURE CODE" as mapped_opcs_4_procedure_code,
    "MAPPED OPCS-4 PROCEDURE DESCRIPTION" as mapped_opcs_4_procedure_description,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP501CodedImm') }}
