-- Raw layer model for mhsds.MHS005PatInd
-- Source: "DATA_LAKE"."MHSDS"
-- Description: Mental Health Services Data Set (MHSDS)
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "LocalPatientId" as local_patient_id,
    "ConstSuperReqDueToDis" as const_super_req_due_to_dis,
    "ParentalResp" as parental_resp,
    "YoungCarer" as young_carer,
    "LACStatus" as lac_status,
    "LACLegalStatus" as lac_legal_status,
    "EducationalAssessOutcome" as educational_assess_outcome,
    "CPP" as cpp,
    "ExBAFIndicator" as ex_baf_indicator,
    "OffenceHistory" as offence_history,
    "ProPsychDate" as pro_psych_date,
    "EmerPsychDate" as emer_psych_date,
    "ManPsychDate" as man_psych_date,
    "PsychPrescDate" as psych_presc_date,
    "PsychTreatDate" as psych_treat_date,
    "ReasonableAdjustmentInd" as reasonable_adjustment_ind,
    "IMCARequired" as imca_required,
    "IMHARequired" as imha_required,
    "IMCAAssigned" as imca_assigned,
    "IMHAAssigned" as imha_assigned,
    "LDStatus" as ld_status,
    "AutismStatus" as autism_status,
    "RecordNumber" as record_number,
    "MHS005UniqID" as mhs005_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqMonthID" as uniq_month_id,
    "EFFECTIVE_FROM" as effective_from,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS005PatInd') }}
