{{
    config(
        description="Raw layer (SUS Monthly outpatient appointments and activity). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.SUS_OP.EncounterDetail \ndbt: source(''sus_op_monthly'', ''EncounterDetail'') \nColumns:\n  SK_EncounterID -> sk_encounter_id\n  StartDate -> start_date\n  EndDate -> end_date\n  SK_SourceOfReferralID -> sk_source_of_referral_id\n  Attendance_Identifier -> attendance_identifier\n  SK_AdminCategoryID -> sk_admin_category_id\n  SK_AttendanceTypeID -> sk_attendance_type_id\n  SK_AttendanceOutcomeID -> sk_attendance_outcome_id\n  SK_DNAIndicatorID -> sk_dna_indicator_id\n  PrimaryProcedure -> primary_procedure\n  PrimaryDiagnosis -> primary_diagnosis\n  HRGCode -> hrg_code\n  HRG4Code -> hrg4_code\n  FCEHRG -> fcehrg\n  UniqueCDSIdentifier -> unique_cds_identifier\n  EncounterStartDateTime -> encounter_start_date_time\n  EncounterEndDateTime -> encounter_end_date_time\n  SK_ServiceProviderID -> sk_service_provider_id\n  SK_PatientID -> sk_patient_id\n  SK_StaffID -> sk_staff_id\n  SK_ConsultantID -> sk_consultant_id\n  PbROrSEM_NotUsed -> pb_ror_sem_not_used\n  DeleteEncounter -> delete_encounter\n  SK_AgeBandID -> sk_age_band_id\n  SK_PriorityTypeID -> sk_priority_type_id\n  Referrer_Code -> referrer_code\n  Referring_Org_Code -> referring_org_code\n  Date_Appointment_Request -> date_appointment_request\n  Is_SpCommissioner -> is_sp_commissioner\n  SK_CommissionerID -> sk_commissioner_id\n  SK_SpecialtyID -> sk_specialty_id\n  SK_Commissioner_PCTID -> sk_commissioner_pctid\n  SK_ConsultantMainSpecialtyID -> sk_consultant_main_specialty_id\n  PASHospitalNumber -> pas_hospital_number\n  COMMISSIONER_SERIAL_NO -> commissioner_serial_no\n  SC_Service_Line_Code_Local -> sc_service_line_code_local\n  SC_Service_Line_Code_National -> sc_service_line_code_national\n  PROVIDER_REFERENCE_NO -> provider_reference_no\n  AGREEMENT_LINE_NO -> agreement_line_no\n  Clinic_Code -> clinic_code\n  Local_Site_Code -> local_site_code\n  Appointment_Time -> appointment_time\n  Local_Sub_Specialty_Code -> local_sub_specialty_code\n  SK_ActivityLocationTypeID -> sk_activity_location_type_id\n  Referral_Request_Date -> referral_request_date\n  SK_Org_CommissionerID -> sk_org_commissioner_id\n  SK_Org_ServiceProviderID -> sk_org_service_provider_id\n  SK_RTTPeriodStatusID -> sk_rtt_period_status_id\n  SK_ServiceTypeRequestedID -> sk_service_type_requested_id\n  RTT_Period_Start_Date -> rtt_period_start_date\n  RTT_Period_End_Date -> rtt_period_end_date\n  Patient_Pathway_ID -> patient_pathway_id\n  PbROrSEM -> pb_ror_sem\n  Is_Valid_UBRN -> is_valid_ubrn\n  UBRN_Occurrence_Count -> ubrn_occurrence_count"
    )
}}
select
    "SK_EncounterID" as sk_encounter_id,
    "StartDate" as start_date,
    "EndDate" as end_date,
    "SK_SourceOfReferralID" as sk_source_of_referral_id,
    "Attendance_Identifier" as attendance_identifier,
    "SK_AdminCategoryID" as sk_admin_category_id,
    "SK_AttendanceTypeID" as sk_attendance_type_id,
    "SK_AttendanceOutcomeID" as sk_attendance_outcome_id,
    "SK_DNAIndicatorID" as sk_dna_indicator_id,
    "PrimaryProcedure" as primary_procedure,
    "PrimaryDiagnosis" as primary_diagnosis,
    "HRGCode" as hrg_code,
    "HRG4Code" as hrg4_code,
    "FCEHRG" as fcehrg,
    "UniqueCDSIdentifier" as unique_cds_identifier,
    "EncounterStartDateTime" as encounter_start_date_time,
    "EncounterEndDateTime" as encounter_end_date_time,
    "SK_ServiceProviderID" as sk_service_provider_id,
    "SK_PatientID" as sk_patient_id,
    "SK_StaffID" as sk_staff_id,
    "SK_ConsultantID" as sk_consultant_id,
    "PbROrSEM_NotUsed" as pb_ror_sem_not_used,
    "DeleteEncounter" as delete_encounter,
    "SK_AgeBandID" as sk_age_band_id,
    "SK_PriorityTypeID" as sk_priority_type_id,
    "Referrer_Code" as referrer_code,
    "Referring_Org_Code" as referring_org_code,
    "Date_Appointment_Request" as date_appointment_request,
    "Is_SpCommissioner" as is_sp_commissioner,
    "SK_CommissionerID" as sk_commissioner_id,
    "SK_SpecialtyID" as sk_specialty_id,
    "SK_Commissioner_PCTID" as sk_commissioner_pctid,
    "SK_ConsultantMainSpecialtyID" as sk_consultant_main_specialty_id,
    "PASHospitalNumber" as pas_hospital_number,
    "COMMISSIONER_SERIAL_NO" as commissioner_serial_no,
    "SC_Service_Line_Code_Local" as sc_service_line_code_local,
    "SC_Service_Line_Code_National" as sc_service_line_code_national,
    "PROVIDER_REFERENCE_NO" as provider_reference_no,
    "AGREEMENT_LINE_NO" as agreement_line_no,
    "Clinic_Code" as clinic_code,
    "Local_Site_Code" as local_site_code,
    "Appointment_Time" as appointment_time,
    "Local_Sub_Specialty_Code" as local_sub_specialty_code,
    "SK_ActivityLocationTypeID" as sk_activity_location_type_id,
    "Referral_Request_Date" as referral_request_date,
    "SK_Org_CommissionerID" as sk_org_commissioner_id,
    "SK_Org_ServiceProviderID" as sk_org_service_provider_id,
    "SK_RTTPeriodStatusID" as sk_rtt_period_status_id,
    "SK_ServiceTypeRequestedID" as sk_service_type_requested_id,
    "RTT_Period_Start_Date" as rtt_period_start_date,
    "RTT_Period_End_Date" as rtt_period_end_date,
    "Patient_Pathway_ID" as patient_pathway_id,
    "PbROrSEM" as pb_ror_sem,
    "Is_Valid_UBRN" as is_valid_ubrn,
    "UBRN_Occurrence_Count" as ubrn_occurrence_count
from {{ source('sus_op_monthly', 'EncounterDetail') }}
