{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS501HospProvSpell \ndbt: source(''mhsds'', ''MHS501HospProvSpell'') \nColumns:\n  SK -> sk\n  HospProvSpellID -> hosp_prov_spell_id\n  HospProvSpellNum -> hosp_prov_spell_num\n  ServiceRequestId -> service_request_id\n  StartDateHospProvSpell -> start_date_hosp_prov_spell\n  StartTimeHospProvSpell -> start_time_hosp_prov_spell\n  DecidedToAdmitDate -> decided_to_admit_date\n  DecidedToAdmitTime -> decided_to_admit_time\n  SourceAdmCodeHospProvSpell -> source_adm_code_hosp_prov_spell\n  SourceAdmMHHospProvSpell -> source_adm_mh_hosp_prov_spell\n  MethAdmMHHospProvSpell -> meth_adm_mh_hosp_prov_spell\n  AdmMethCodeHospProvSpell -> adm_meth_code_hosp_prov_spell\n  PostcodeMainVisitor Pseudo -> postcode_main_visitor_pseudo\n  EstimatedDischDateHospProvSpell -> estimated_disch_date_hosp_prov_spell\n  PlannedDischDateHospProvSpell -> planned_disch_date_hosp_prov_spell\n  PlannedDestDisch -> planned_dest_disch\n  PlannedDischDestCode -> planned_disch_dest_code\n  DischDateHospProvSpell -> disch_date_hosp_prov_spell\n  DischTimeHospProvSpell -> disch_time_hosp_prov_spell\n  MethOfDischMHHospProvSpell -> meth_of_disch_mh_hosp_prov_spell\n  DischMethCodeHospProvSpell -> disch_meth_code_hosp_prov_spell\n  DestOfDischHospProvSpell -> dest_of_disch_hosp_prov_spell\n  DischDestCodeHospProvSpell -> disch_dest_code_hosp_prov_spell\n  PostcodeDischDestHospProvSpell Pseudo -> postcode_disch_dest_hosp_prov_spell_pseudo\n  TransformingCareInd -> transforming_care_ind\n  TransformingCareCategory -> transforming_care_category\n  RecordNumber -> record_number\n  MHS501UniqID -> mhs501_uniq_id\n  OrgIDProv -> org_id_prov\n  Person_ID -> person_id\n  UniqSubmissionID -> uniq_submission_id\n  UniqServReqID -> uniq_serv_req_id\n  UniqHospProvSpellID -> uniq_hosp_prov_spell_id\n  UniqHospProvSpellNum -> uniq_hosp_prov_spell_num\n  PostcodeDistrictMainVisitor -> postcode_district_main_visitor\n  PostcodeDistrictDischDest -> postcode_district_disch_dest\n  UniqMonthID -> uniq_month_id\n  RecordStartDate -> record_start_date\n  RecordEndDate -> record_end_date\n  InactTimeHPS -> inact_time_hps\n  LOSDischHosSpell -> los_disch_hos_spell\n  LOSHosSpellEoRP -> los_hos_spell_eo_rp\n  TimeEstDischDate -> time_est_disch_date\n  TimePlanDischDate -> time_plan_disch_date\n  EFFECTIVE_FROM -> effective_from\n  AgeHospStartDate -> age_hosp_start_date\n  AgeHospDischDate -> age_hosp_disch_date\n  NHSEValidatedPostcodeMainVisitor Pseudo -> nhse_validated_postcode_main_visitor_pseudo\n  NHSEValidatedPostcodeDischDestHospProvSpell Pseudo -> nhse_validated_postcode_disch_dest_hosp_prov_spell_pseudo\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "HospProvSpellID" as hosp_prov_spell_id,
    "HospProvSpellNum" as hosp_prov_spell_num,
    "ServiceRequestId" as service_request_id,
    "StartDateHospProvSpell" as start_date_hosp_prov_spell,
    "StartTimeHospProvSpell" as start_time_hosp_prov_spell,
    "DecidedToAdmitDate" as decided_to_admit_date,
    "DecidedToAdmitTime" as decided_to_admit_time,
    "SourceAdmCodeHospProvSpell" as source_adm_code_hosp_prov_spell,
    "SourceAdmMHHospProvSpell" as source_adm_mh_hosp_prov_spell,
    "MethAdmMHHospProvSpell" as meth_adm_mh_hosp_prov_spell,
    "AdmMethCodeHospProvSpell" as adm_meth_code_hosp_prov_spell,
    "PostcodeMainVisitor Pseudo" as postcode_main_visitor_pseudo,
    "EstimatedDischDateHospProvSpell" as estimated_disch_date_hosp_prov_spell,
    "PlannedDischDateHospProvSpell" as planned_disch_date_hosp_prov_spell,
    "PlannedDestDisch" as planned_dest_disch,
    "PlannedDischDestCode" as planned_disch_dest_code,
    "DischDateHospProvSpell" as disch_date_hosp_prov_spell,
    "DischTimeHospProvSpell" as disch_time_hosp_prov_spell,
    "MethOfDischMHHospProvSpell" as meth_of_disch_mh_hosp_prov_spell,
    "DischMethCodeHospProvSpell" as disch_meth_code_hosp_prov_spell,
    "DestOfDischHospProvSpell" as dest_of_disch_hosp_prov_spell,
    "DischDestCodeHospProvSpell" as disch_dest_code_hosp_prov_spell,
    "PostcodeDischDestHospProvSpell Pseudo" as postcode_disch_dest_hosp_prov_spell_pseudo,
    "TransformingCareInd" as transforming_care_ind,
    "TransformingCareCategory" as transforming_care_category,
    "RecordNumber" as record_number,
    "MHS501UniqID" as mhs501_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "UniqHospProvSpellID" as uniq_hosp_prov_spell_id,
    "UniqHospProvSpellNum" as uniq_hosp_prov_spell_num,
    "PostcodeDistrictMainVisitor" as postcode_district_main_visitor,
    "PostcodeDistrictDischDest" as postcode_district_disch_dest,
    "UniqMonthID" as uniq_month_id,
    "RecordStartDate" as record_start_date,
    "RecordEndDate" as record_end_date,
    "InactTimeHPS" as inact_time_hps,
    "LOSDischHosSpell" as los_disch_hos_spell,
    "LOSHosSpellEoRP" as los_hos_spell_eo_rp,
    "TimeEstDischDate" as time_est_disch_date,
    "TimePlanDischDate" as time_plan_disch_date,
    "EFFECTIVE_FROM" as effective_from,
    "AgeHospStartDate" as age_hosp_start_date,
    "AgeHospDischDate" as age_hosp_disch_date,
    "NHSEValidatedPostcodeMainVisitor Pseudo" as nhse_validated_postcode_main_visitor_pseudo,
    "NHSEValidatedPostcodeDischDestHospProvSpell Pseudo" as nhse_validated_postcode_disch_dest_hosp_prov_spell_pseudo,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS501HospProvSpell') }}
