{{
    config(
        description="Raw layer (Community services dataset). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.CSDS.CYP101Referral \ndbt: source(''csds'', ''CYP101Referral'') \nColumns:\n  SK -> sk\n  SERVICE REQUEST IDENTIFIER -> service_request_identifier\n  LOCAL PATIENT IDENTIFIER (EXTENDED) -> local_patient_identifier_extended\n  ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) -> organisation_identifier_code_of_commissioner\n  ORGANISATION CODE (CODE OF COMMISSIONER) -> organisation_code_code_of_commissioner\n  REFERRAL REQUEST RECEIVED DATE -> referral_request_received_date\n  REFERRAL REQUEST RECEIVED TIME -> referral_request_received_time\n  NHS SERVICE AGREEMENT LINE IDENTIFIER -> nhs_service_agreement_line_identifier\n  NHS SERVICE AGREEMENT LINE NUMBER -> nhs_service_agreement_line_number\n  SOURCE OF REFERRAL FOR COMMUNITY -> source_of_referral_for_community\n  ORGANISATION IDENTIFIER (REFERRING ORGANISATION) -> organisation_identifier_referring_organisation\n  ORGANISATION IDENTIFIER (REFERRING) -> organisation_identifier_referring\n  REFERRING ORGANISATION CODE -> referring_organisation_code\n  REFERRING CARE PROFESSIONAL STAFF GROUP (COMMUNITY CARE) -> referring_care_professional_staff_group_community_care\n  REFERRING CARE PROFESSIONAL STAFF GROUP (MENTAL HEALTH AND COMMUNITY CARE) -> referring_care_professional_staff_group_mental_health_and_community_care\n  PRIORITY TYPE CODE -> priority_type_code\n  PRIMARY REASON FOR REFERRAL (COMMUNITY CARE) -> primary_reason_for_referral_community_care\n  SERVICE DISCHARGE DATE -> service_discharge_date\n  DISCHARGE LETTER ISSUED DATE (COMMUNITY CARE) -> discharge_letter_issued_date_community_care\n  DISCHARGE LETTER ISSUED DATE (MENTAL HEALTH AND COMMUNITY CARE) -> discharge_letter_issued_date_mental_health_and_community_care\n  EFFECTIVE FROM -> effective_from\n  RECORD NUMBER -> record_number\n  CYP101 UNIQUE ID -> cyp101_unique_id\n  ORGANISATION IDENTIFIER (CODE OF PROVIDER) -> organisation_identifier_code_of_provider\n  ORGANISATION CODE (PROVIDER) -> organisation_code_provider\n  PERSON ID -> person_id\n  UNIQUE CSDS ID (PATIENT) -> unique_csds_id_patient\n  UNIQUE SUBMISSION ID -> unique_submission_id\n  BSP UNIQUE ID -> bsp_unique_id\n  UNIQUE SERVICE REQUEST IDENTIFIER -> unique_service_request_identifier\n  AGE AT SERVICE REFERRAL RECEIVED DATE -> age_at_service_referral_received_date\n  AGE AT SERVICE REFERRAL DISCHARGE -> age_at_service_referral_discharge\n  AGE AT SERVICE REFERRAL RECEIVED DATE (YEARS) -> age_at_service_referral_received_date_years\n  IC_AGE_AT_SERVICE_REFERRAL_RECEIVED_DATE -> ic_age_at_service_referral_received_date\n  AGE AT SERVICE REFERRAL DISCHARGE (YEARS) -> age_at_service_referral_discharge_years\n  IC_AGE_AT_SERVICE_REFERRAL_DISCHARGE -> ic_age_at_service_referral_discharge\n  RECORD START DATE -> record_start_date\n  RECORD END DATE -> record_end_date\n  UNIQUE MONTH ID -> unique_month_id\n  AGE GROUP (REFERRAL RECEIVED DATE) -> age_group_referral_received_date\n  AGE GROUP (SERVICE DISCHARGE DATE) -> age_group_service_discharge_date\n  AGE BAND (REFERRAL RECEIVED DATE) -> age_band_referral_received_date\n  AGE BAND (SERVICE DISCHARGE DATE) -> age_band_service_discharge_date\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicCCG -> dmic_ccg\n  Unique_LocalPatientId -> unique_local_patient_id\n  UniqueCYPHS_ID_Patient -> unique_cyphs_id_patient\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason\n  FILE TYPE -> file_type\n  REPORTING PERIOD START DATE -> reporting_period_start_date\n  REPORTING PERIOD END DATE -> reporting_period_end_date"
    )
}}
select
    "SK" as sk,
    "SERVICE REQUEST IDENTIFIER" as service_request_identifier,
    "LOCAL PATIENT IDENTIFIER (EXTENDED)" as local_patient_identifier_extended,
    "ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)" as organisation_identifier_code_of_commissioner,
    "ORGANISATION CODE (CODE OF COMMISSIONER)" as organisation_code_code_of_commissioner,
    "REFERRAL REQUEST RECEIVED DATE" as referral_request_received_date,
    "REFERRAL REQUEST RECEIVED TIME" as referral_request_received_time,
    "NHS SERVICE AGREEMENT LINE IDENTIFIER" as nhs_service_agreement_line_identifier,
    "NHS SERVICE AGREEMENT LINE NUMBER" as nhs_service_agreement_line_number,
    "SOURCE OF REFERRAL FOR COMMUNITY" as source_of_referral_for_community,
    "ORGANISATION IDENTIFIER (REFERRING ORGANISATION)" as organisation_identifier_referring_organisation,
    "ORGANISATION IDENTIFIER (REFERRING)" as organisation_identifier_referring,
    "REFERRING ORGANISATION CODE" as referring_organisation_code,
    "REFERRING CARE PROFESSIONAL STAFF GROUP (COMMUNITY CARE)" as referring_care_professional_staff_group_community_care,
    "REFERRING CARE PROFESSIONAL STAFF GROUP (MENTAL HEALTH AND COMMUNITY CARE)" as referring_care_professional_staff_group_mental_health_and_community_care,
    "PRIORITY TYPE CODE" as priority_type_code,
    "PRIMARY REASON FOR REFERRAL (COMMUNITY CARE)" as primary_reason_for_referral_community_care,
    "SERVICE DISCHARGE DATE" as service_discharge_date,
    "DISCHARGE LETTER ISSUED DATE (COMMUNITY CARE)" as discharge_letter_issued_date_community_care,
    "DISCHARGE LETTER ISSUED DATE (MENTAL HEALTH AND COMMUNITY CARE)" as discharge_letter_issued_date_mental_health_and_community_care,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP101 UNIQUE ID" as cyp101_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UNIQUE SERVICE REQUEST IDENTIFIER" as unique_service_request_identifier,
    "AGE AT SERVICE REFERRAL RECEIVED DATE" as age_at_service_referral_received_date,
    "AGE AT SERVICE REFERRAL DISCHARGE" as age_at_service_referral_discharge,
    "AGE AT SERVICE REFERRAL RECEIVED DATE (YEARS)" as age_at_service_referral_received_date_years,
    "IC_AGE_AT_SERVICE_REFERRAL_RECEIVED_DATE" as ic_age_at_service_referral_received_date,
    "AGE AT SERVICE REFERRAL DISCHARGE (YEARS)" as age_at_service_referral_discharge_years,
    "IC_AGE_AT_SERVICE_REFERRAL_DISCHARGE" as ic_age_at_service_referral_discharge,
    "RECORD START DATE" as record_start_date,
    "RECORD END DATE" as record_end_date,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (REFERRAL RECEIVED DATE)" as age_group_referral_received_date,
    "AGE GROUP (SERVICE DISCHARGE DATE)" as age_group_service_discharge_date,
    "AGE BAND (REFERRAL RECEIVED DATE)" as age_band_referral_received_date,
    "AGE BAND (SERVICE DISCHARGE DATE)" as age_band_service_discharge_date,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP101Referral') }}
