-- Raw layer model for mhsds.MHS204IndirectActivity
-- Source: "DATA_LAKE"."MHSDS"
-- Description: Mental Health Services Data Set (MHSDS)
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "ServiceRequestId" as service_request_id,
    "IndirectActDate" as indirect_act_date,
    "OtherCareProfTeamLocalID" as other_care_prof_team_local_id,
    "CareProfTeamLocalId" as care_prof_team_local_id,
    "IndirectActTime" as indirect_act_time,
    "IndActPersCons" as ind_act_pers_cons,
    "DurationIndirectAct" as duration_indirect_act,
    "OrgIDComm" as org_id_comm,
    "CareProfLocalId" as care_prof_local_id,
    "IndActProcedure" as ind_act_procedure,
    "CodeProcAndProcStatus" as code_proc_and_proc_status,
    "CodeIndActProcAndProcStatus" as code_ind_act_proc_and_proc_status,
    "FindSchemeInUse" as find_scheme_in_use,
    "Finding" as finding,
    "CodeFind" as code_find,
    "RecordNumber" as record_number,
    "MHS204UniqID" as mhs204_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "UniqCareProfLocalID" as uniq_care_prof_local_id,
    "UniqMonthID" as uniq_month_id,
    "EFFECTIVE_FROM" as effective_from,
    "MasterSnomedCTFindingCode" as master_snomed_ct_finding_code,
    "AgeAtIndirectActivity" as age_at_indirect_activity,
    "UniqOtherCareProfTeamLocalID" as uniq_other_care_prof_team_local_id,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS204IndirectActivity') }}
