-- Raw layer model for mhsds.MHS202CareActivity
-- Source: "DATA_LAKE"."MHSDS"
-- Description: Mental Health Services Data Set (MHSDS)
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "CareActId" as care_act_id,
    "CareContactId" as care_contact_id,
    "CareProfLocalId" as care_prof_local_id,
    "ClinContactDurOfCareAct" as clin_contact_dur_of_care_act,
    "Procedure" as procedure,
    "CodeProcAndProcStatus" as code_proc_and_proc_status,
    "FindSchemeInUse" as find_scheme_in_use,
    "Finding" as finding,
    "CodeFind" as code_find,
    "Observation" as observation,
    "CodeObs" as code_obs,
    "ObsValue" as obs_value,
    "UnitOfMeasurement_UCUM" as unit_of_measurement_ucum,
    "UnitMeasure" as unit_measure,
    "RecordNumber" as record_number,
    "MHS202UniqID" as mhs202_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "UniqCareContID" as uniq_care_cont_id,
    "UniqCareActID" as uniq_care_act_id,
    "UniqCareProfLocalID" as uniq_care_prof_local_id,
    "UniqMonthID" as uniq_month_id,
    "EFFECTIVE_FROM" as effective_from,
    "MasterSnomedCTFindingCode" as master_snomed_ct_finding_code,
    "MasterSnomedCTObsCode" as master_snomed_ct_obs_code,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicActivityDate" as dmic_activity_date,
    "ServiceRequestId" as service_request_id,
    "ObsSchemeInUse" as obs_scheme_in_use,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS202CareActivity') }}
