{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS502WardStay \ndbt: source(''mhsds'', ''MHS502WardStay'') \nColumns:\n  SK -> sk\n  WardStayId -> ward_stay_id\n  WardCode -> ward_code\n  HospProvSpellID -> hosp_prov_spell_id\n  HospProvSpellNum -> hosp_prov_spell_num\n  StartDateWardStay -> start_date_ward_stay\n  StartTimeWardStay -> start_time_ward_stay\n  EndDateMHTrialLeave -> end_date_mh_trial_leave\n  EndDateWardStay -> end_date_ward_stay\n  EndTimeWardStay -> end_time_ward_stay\n  MHAdmittedPatientClass -> mh_admitted_patient_class\n  SiteIDOfTreat -> site_id_of_treat\n  WardType -> ward_type\n  WardAge -> ward_age\n  WardIntendedSex -> ward_intended_sex\n  WardSexTypeCode -> ward_sex_type_code\n  WardIntendedClinCareMH -> ward_intended_clin_care_mh\n  IntendClinCareIntenCodeMH -> intend_clin_care_inten_code_mh\n  WardSecLevel -> ward_sec_level\n  LockedWardInd -> locked_ward_ind\n  HospitalBedTypeMH -> hospital_bed_type_mh\n  SpecialisedMHServiceCode -> specialised_mh_service_code\n  RecordNumber -> record_number\n  MHS502UniqID -> mhs502_uniq_id\n  OrgIDProv -> org_id_prov\n  Person_ID -> person_id\n  UniqSubmissionID -> uniq_submission_id\n  UniqServReqID -> uniq_serv_req_id\n  UniqHospProvSpellID -> uniq_hosp_prov_spell_id\n  UniqHospProvSpellNum -> uniq_hosp_prov_spell_num\n  UniqWardStayID -> uniq_ward_stay_id\n  WardLocDistanceHome -> ward_loc_distance_home\n  UniqMonthID -> uniq_month_id\n  RecordStartDate -> record_start_date\n  RecordEndDate -> record_end_date\n  InactTimeWS -> inact_time_ws\n  BedTypeAdultEndRP -> bed_type_adult_end_rp\n  BedTypeAdultDischarge -> bed_type_adult_discharge\n  BedDaysWSEndRP -> bed_days_ws_end_rp\n  EFFECTIVE_FROM -> effective_from\n  WardStayServiceAreasOpenEndRPAMH -> ward_stay_service_areas_open_end_rpamh\n  WardStayServiceAreasOpenEndRPCYP -> ward_stay_service_areas_open_end_rpcyp\n  WardStayServiceAreasStartingInRPLDA -> ward_stay_service_areas_starting_in_rplda\n  WardStayServiceAreasStartingInRPAMH -> ward_stay_service_areas_starting_in_rpamh\n  WardStayServiceAreasStartingInRPCYP -> ward_stay_service_areas_starting_in_rpcyp\n  SpecialisedMHServiceName -> specialised_mh_service_name\n  WardStayBedTypesLkup -> ward_stay_bed_types_lkup\n  HospitalBedTypeName -> hospital_bed_type_name\n  WardStayServiceAreasOpenEndRPLDA -> ward_stay_service_areas_open_end_rplda\n  UniqWardCode -> uniq_ward_code\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicWardStayArea -> dmic_ward_stay_area\n  dmicWardStayAreaEndRP -> dmic_ward_stay_area_end_rp\n  dmicWardStayAreaDischarge -> dmic_ward_stay_area_discharge\n  dmicCYPAtStartIndicator -> dmic_cyp_at_start_indicator\n  AMHServiceWSDischarge -> amh_service_ws_discharge\n  CYPServiceWSDischarge -> cyp_service_ws_discharge\n  LDAServiceWSDischarge -> lda_service_ws_discharge\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "WardStayId" as ward_stay_id,
    "WardCode" as ward_code,
    "HospProvSpellID" as hosp_prov_spell_id,
    "HospProvSpellNum" as hosp_prov_spell_num,
    "StartDateWardStay" as start_date_ward_stay,
    "StartTimeWardStay" as start_time_ward_stay,
    "EndDateMHTrialLeave" as end_date_mh_trial_leave,
    "EndDateWardStay" as end_date_ward_stay,
    "EndTimeWardStay" as end_time_ward_stay,
    "MHAdmittedPatientClass" as mh_admitted_patient_class,
    "SiteIDOfTreat" as site_id_of_treat,
    "WardType" as ward_type,
    "WardAge" as ward_age,
    "WardIntendedSex" as ward_intended_sex,
    "WardSexTypeCode" as ward_sex_type_code,
    "WardIntendedClinCareMH" as ward_intended_clin_care_mh,
    "IntendClinCareIntenCodeMH" as intend_clin_care_inten_code_mh,
    "WardSecLevel" as ward_sec_level,
    "LockedWardInd" as locked_ward_ind,
    "HospitalBedTypeMH" as hospital_bed_type_mh,
    "SpecialisedMHServiceCode" as specialised_mh_service_code,
    "RecordNumber" as record_number,
    "MHS502UniqID" as mhs502_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "UniqHospProvSpellID" as uniq_hosp_prov_spell_id,
    "UniqHospProvSpellNum" as uniq_hosp_prov_spell_num,
    "UniqWardStayID" as uniq_ward_stay_id,
    "WardLocDistanceHome" as ward_loc_distance_home,
    "UniqMonthID" as uniq_month_id,
    "RecordStartDate" as record_start_date,
    "RecordEndDate" as record_end_date,
    "InactTimeWS" as inact_time_ws,
    "BedTypeAdultEndRP" as bed_type_adult_end_rp,
    "BedTypeAdultDischarge" as bed_type_adult_discharge,
    "BedDaysWSEndRP" as bed_days_ws_end_rp,
    "EFFECTIVE_FROM" as effective_from,
    "WardStayServiceAreasOpenEndRPAMH" as ward_stay_service_areas_open_end_rpamh,
    "WardStayServiceAreasOpenEndRPCYP" as ward_stay_service_areas_open_end_rpcyp,
    "WardStayServiceAreasStartingInRPLDA" as ward_stay_service_areas_starting_in_rplda,
    "WardStayServiceAreasStartingInRPAMH" as ward_stay_service_areas_starting_in_rpamh,
    "WardStayServiceAreasStartingInRPCYP" as ward_stay_service_areas_starting_in_rpcyp,
    "SpecialisedMHServiceName" as specialised_mh_service_name,
    "WardStayBedTypesLkup" as ward_stay_bed_types_lkup,
    "HospitalBedTypeName" as hospital_bed_type_name,
    "WardStayServiceAreasOpenEndRPLDA" as ward_stay_service_areas_open_end_rplda,
    "UniqWardCode" as uniq_ward_code,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicWardStayArea" as dmic_ward_stay_area,
    "dmicWardStayAreaEndRP" as dmic_ward_stay_area_end_rp,
    "dmicWardStayAreaDischarge" as dmic_ward_stay_area_discharge,
    "dmicCYPAtStartIndicator" as dmic_cyp_at_start_indicator,
    "AMHServiceWSDischarge" as amh_service_ws_discharge,
    "CYPServiceWSDischarge" as cyp_service_ws_discharge,
    "LDAServiceWSDischarge" as lda_service_ws_discharge,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS502WardStay') }}
