-- Raw layer model for mhsds.MHS102ServiceTypeReferredTo
-- Source: "DATA_LAKE"."MHSDS"
-- Description: Mental Health Services Data Set (MHSDS)
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "ServiceRequestId" as service_request_id,
    "OtherCareProfTeamLocalID" as other_care_prof_team_local_id,
    "CareProfTeamLocalId" as care_prof_team_local_id,
    "ReferClosureDate" as refer_closure_date,
    "ReferClosureTime" as refer_closure_time,
    "ReferRejectionDate" as refer_rejection_date,
    "ReferRejectionTime" as refer_rejection_time,
    "ReferRejectReason" as refer_reject_reason,
    "ReferClosReason" as refer_clos_reason,
    "RecordNumber" as record_number,
    "MHS102UniqID" as mhs102_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "AgeServReferClosure" as age_serv_refer_closure,
    "AgeServReferRejection" as age_serv_refer_rejection,
    "UniqMonthID" as uniq_month_id,
    "RecordStartDate" as record_start_date,
    "RecordEndDate" as record_end_date,
    "InactTimeST" as inact_time_st,
    "EFFECTIVE_FROM" as effective_from,
    "TeamTypePredominantAgeU18" as team_type_predominant_age_u18,
    "ServTeamTypeRefToMH" as serv_team_type_ref_to_mh,
    "ServiceTypeName" as service_type_name,
    "UniqOtherCareProfTeamLocalId" as uniq_other_care_prof_team_local_id,
    "UniqCareProfTeamID" as uniq_care_prof_team_id,
    "ServTeamIntAgeGroup" as serv_team_int_age_group,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicIsCYPServiceTypeIndicator" as dmic_is_cyp_service_type_indicator,
    "dmicIsLDAServiceTypeIndicator" as dmic_is_lda_service_type_indicator,
    "dmicIsAMHServiceTypeIndicator" as dmic_is_amh_service_type_indicator,
    "dmicUniqCareProfTeamIdPercentUnder18" as dmic_uniq_care_prof_team_id_percent_under18,
    "CAMHSTier" as camhs_tier,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS102ServiceTypeReferredTo') }}
