{{
    config(
        description="Raw layer (Community services dataset). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.CSDS.CYP104RTT \ndbt: source(''csds'', ''CYP104RTT'') \nColumns:\n  SK -> sk\n  SERVICE REQUEST IDENTIFIER -> service_request_identifier\n  BookingReference Pseudo -> booking_reference_pseudo\n  PatientPathwayID Pseudo -> patient_pathway_id_pseudo\n  ORGANISATION IDENTIFIER (PATIENT PATHWAY IDENTIFIER ISSUER) -> organisation_identifier_patient_pathway_identifier_issuer\n  ORGANISATION CODE (PATIENT PATHWAY IDENTIFIER ISSUER) -> organisation_code_patient_pathway_identifier_issuer\n  WAITING TIME MEASUREMENT TYPE (COMMUNITY CARE) -> waiting_time_measurement_type_community_care\n  WAITING TIME MEASUREMENT TYPE -> waiting_time_measurement_type\n  REFERRAL TO TREATMENT PERIOD START DATE -> referral_to_treatment_period_start_date\n  REFERRAL TO TREATMENT PERIOD START TIME -> referral_to_treatment_period_start_time\n  REFERRAL TO TREATMENT PERIOD END DATE -> referral_to_treatment_period_end_date\n  REFERRAL TO TREATMENT PERIOD END TIME -> referral_to_treatment_period_end_time\n  REFERRAL TO TREATMENT PERIOD STATUS -> referral_to_treatment_period_status\n  EFFECTIVE FROM -> effective_from\n  RECORD NUMBER -> record_number\n  CYP104 UNIQUE ID -> cyp104_unique_id\n  ORGANISATION IDENTIFIER (CODE OF PROVIDER) -> organisation_identifier_code_of_provider\n  ORGANISATION CODE (PROVIDER) -> organisation_code_provider\n  PERSON ID -> person_id\n  UNIQUE CSDS ID (PATIENT) -> unique_csds_id_patient\n  UNIQUE SUBMISSION ID -> unique_submission_id\n  BSP UNIQUE ID -> bsp_unique_id\n  UNIQUE SERVICE REQUEST IDENTIFIER -> unique_service_request_identifier\n  AGE AT REFERRAL TO TREATMENT START DATE -> age_at_referral_to_treatment_start_date\n  AGE AT REFERRAL TO TREATMENT END DATE -> age_at_referral_to_treatment_end_date\n  TIME BETWEEN REFERRAL TO TREATMENT START AND END DATE -> time_between_referral_to_treatment_start_and_end_date\n  AGE AT REFERRAL TO TREATMENT START DATE (YEARS) -> age_at_referral_to_treatment_start_date_years\n  IC_AGE_AT_REFERRAL_TO_TREATMENT_START_DATE -> ic_age_at_referral_to_treatment_start_date\n  AGE AT REFERRAL TO TREATMENT END DATE (YEARS) -> age_at_referral_to_treatment_end_date_years\n  IC_AGE_AT_REFERRAL_TO_TREATMENT_END_DATE -> ic_age_at_referral_to_treatment_end_date\n  RECORD START DATE -> record_start_date\n  RECORD END DATE -> record_end_date\n  DERIVED WAITING TIME -> derived_waiting_time\n  DERIVED WAITING TIME (NIGHT) -> derived_waiting_time_night\n  RESPONSE STANDARD MET -> response_standard_met\n  UNIQUE MONTH ID -> unique_month_id\n  AGE GROUP (RTT START DATE) -> age_group_rtt_start_date\n  AGE GROUP (RTT END DATE) -> age_group_rtt_end_date\n  AGE BAND (RTT START DATE) -> age_band_rtt_start_date\n  AGE BAND (RTT END DATE) -> age_band_rtt_end_date\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicCCG -> dmic_ccg\n  UniqueCYPHS_ID_Patient -> unique_cyphs_id_patient\n  FILE TYPE -> file_type\n  REPORTING PERIOD START DATE -> reporting_period_start_date\n  REPORTING PERIOD END DATE -> reporting_period_end_date"
    )
}}
select
    "SK" as sk,
    "SERVICE REQUEST IDENTIFIER" as service_request_identifier,
    "BookingReference Pseudo" as booking_reference_pseudo,
    "PatientPathwayID Pseudo" as patient_pathway_id_pseudo,
    "ORGANISATION IDENTIFIER (PATIENT PATHWAY IDENTIFIER ISSUER)" as organisation_identifier_patient_pathway_identifier_issuer,
    "ORGANISATION CODE (PATIENT PATHWAY IDENTIFIER ISSUER)" as organisation_code_patient_pathway_identifier_issuer,
    "WAITING TIME MEASUREMENT TYPE (COMMUNITY CARE)" as waiting_time_measurement_type_community_care,
    "WAITING TIME MEASUREMENT TYPE" as waiting_time_measurement_type,
    "REFERRAL TO TREATMENT PERIOD START DATE" as referral_to_treatment_period_start_date,
    "REFERRAL TO TREATMENT PERIOD START TIME" as referral_to_treatment_period_start_time,
    "REFERRAL TO TREATMENT PERIOD END DATE" as referral_to_treatment_period_end_date,
    "REFERRAL TO TREATMENT PERIOD END TIME" as referral_to_treatment_period_end_time,
    "REFERRAL TO TREATMENT PERIOD STATUS" as referral_to_treatment_period_status,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP104 UNIQUE ID" as cyp104_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UNIQUE SERVICE REQUEST IDENTIFIER" as unique_service_request_identifier,
    "AGE AT REFERRAL TO TREATMENT START DATE" as age_at_referral_to_treatment_start_date,
    "AGE AT REFERRAL TO TREATMENT END DATE" as age_at_referral_to_treatment_end_date,
    "TIME BETWEEN REFERRAL TO TREATMENT START AND END DATE" as time_between_referral_to_treatment_start_and_end_date,
    "AGE AT REFERRAL TO TREATMENT START DATE (YEARS)" as age_at_referral_to_treatment_start_date_years,
    "IC_AGE_AT_REFERRAL_TO_TREATMENT_START_DATE" as ic_age_at_referral_to_treatment_start_date,
    "AGE AT REFERRAL TO TREATMENT END DATE (YEARS)" as age_at_referral_to_treatment_end_date_years,
    "IC_AGE_AT_REFERRAL_TO_TREATMENT_END_DATE" as ic_age_at_referral_to_treatment_end_date,
    "RECORD START DATE" as record_start_date,
    "RECORD END DATE" as record_end_date,
    "DERIVED WAITING TIME" as derived_waiting_time,
    "DERIVED WAITING TIME (NIGHT)" as derived_waiting_time_night,
    "RESPONSE STANDARD MET" as response_standard_met,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (RTT START DATE)" as age_group_rtt_start_date,
    "AGE GROUP (RTT END DATE)" as age_group_rtt_end_date,
    "AGE BAND (RTT START DATE)" as age_band_rtt_start_date,
    "AGE BAND (RTT END DATE)" as age_band_rtt_end_date,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP104RTT') }}
