{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS202CareActivity \ndbt: source(''mhsds'', ''MHS202CareActivity'') \nColumns:\n  SK -> sk\n  CareActId -> care_act_id\n  CareContactId -> care_contact_id\n  CareProfLocalId -> care_prof_local_id\n  ClinContactDurOfCareAct -> clin_contact_dur_of_care_act\n  Procedure -> procedure\n  CodeProcAndProcStatus -> code_proc_and_proc_status\n  FindSchemeInUse -> find_scheme_in_use\n  Finding -> finding\n  CodeFind -> code_find\n  Observation -> observation\n  CodeObs -> code_obs\n  ObsValue -> obs_value\n  UnitOfMeasurement_UCUM -> unit_of_measurement_ucum\n  UnitMeasure -> unit_measure\n  RecordNumber -> record_number\n  MHS202UniqID -> mhs202_uniq_id\n  OrgIDProv -> org_id_prov\n  Person_ID -> person_id\n  UniqSubmissionID -> uniq_submission_id\n  UniqServReqID -> uniq_serv_req_id\n  UniqCareContID -> uniq_care_cont_id\n  UniqCareActID -> uniq_care_act_id\n  UniqCareProfLocalID -> uniq_care_prof_local_id\n  UniqMonthID -> uniq_month_id\n  EFFECTIVE_FROM -> effective_from\n  MasterSnomedCTFindingCode -> master_snomed_ct_finding_code\n  MasterSnomedCTObsCode -> master_snomed_ct_obs_code\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicActivityDate -> dmic_activity_date\n  ServiceRequestId -> service_request_id\n  ObsSchemeInUse -> obs_scheme_in_use\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "CareActId" as care_act_id,
    "CareContactId" as care_contact_id,
    "CareProfLocalId" as care_prof_local_id,
    "ClinContactDurOfCareAct" as clin_contact_dur_of_care_act,
    "Procedure" as procedure,
    "CodeProcAndProcStatus" as code_proc_and_proc_status,
    "FindSchemeInUse" as find_scheme_in_use,
    "Finding" as finding,
    "CodeFind" as code_find,
    "Observation" as observation,
    "CodeObs" as code_obs,
    "ObsValue" as obs_value,
    "UnitOfMeasurement_UCUM" as unit_of_measurement_ucum,
    "UnitMeasure" as unit_measure,
    "RecordNumber" as record_number,
    "MHS202UniqID" as mhs202_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "UniqCareContID" as uniq_care_cont_id,
    "UniqCareActID" as uniq_care_act_id,
    "UniqCareProfLocalID" as uniq_care_prof_local_id,
    "UniqMonthID" as uniq_month_id,
    "EFFECTIVE_FROM" as effective_from,
    "MasterSnomedCTFindingCode" as master_snomed_ct_finding_code,
    "MasterSnomedCTObsCode" as master_snomed_ct_obs_code,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicActivityDate" as dmic_activity_date,
    "ServiceRequestId" as service_request_id,
    "ObsSchemeInUse" as obs_scheme_in_use,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS202CareActivity') }}
