{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS302MHDropInContact \ndbt: source(''mhsds'', ''MHS302MHDropInContact'') \nColumns:\n  SK -> sk\n  MHDropInContactId -> mh_drop_in_contact_id\n  CareContactDateMHDropInContact -> care_contact_date_mh_drop_in_contact\n  OrgIDComm -> org_id_comm\n  MHDropInContactServiceType -> mh_drop_in_contact_service_type\n  StartTimeDropInContact -> start_time_drop_in_contact\n  EndTimeDropInContact -> end_time_drop_in_contact\n  LocalPatientId -> local_patient_id\n  NHSNumber Pseudo -> nhs_number_pseudo\n  PersonBirthDate Pseudo -> person_birth_date_pseudo\n  GenderIDCode -> gender_id_code\n  GenderSameAtBirth -> gender_same_at_birth\n  EthnicCategory -> ethnic_category\n  EthnicCategory2021 -> ethnic_category2021\n  ConsMechanismMH -> cons_mechanism_mh\n  CareProfLocalId -> care_prof_local_id\n  MHDropInContactOutcome -> mh_drop_in_contact_outcome\n  OrgIDReceiving -> org_id_receiving\n  MHS302UniqID -> mhs302_uniq_id\n  OrgIDProv -> org_id_prov\n  UniqSubmissionID -> uniq_submission_id\n  UniqCareProfLocalID -> uniq_care_prof_local_id\n  AgeRepPeriodStart -> age_rep_period_start\n  AgeRepPeriodEnd -> age_rep_period_end\n  UniqMonthID -> uniq_month_id\n  NHSDEthnicity -> nhsd_ethnicity\n  EFFECTIVE_FROM -> effective_from\n  UniqMHDropInContactId -> uniq_mh_drop_in_contact_id\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  Unique_LocalPatientId -> unique_local_patient_id\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "MHDropInContactId" as mh_drop_in_contact_id,
    "CareContactDateMHDropInContact" as care_contact_date_mh_drop_in_contact,
    "OrgIDComm" as org_id_comm,
    "MHDropInContactServiceType" as mh_drop_in_contact_service_type,
    "StartTimeDropInContact" as start_time_drop_in_contact,
    "EndTimeDropInContact" as end_time_drop_in_contact,
    "LocalPatientId" as local_patient_id,
    "NHSNumber Pseudo" as nhs_number_pseudo,
    "PersonBirthDate Pseudo" as person_birth_date_pseudo,
    "GenderIDCode" as gender_id_code,
    "GenderSameAtBirth" as gender_same_at_birth,
    "EthnicCategory" as ethnic_category,
    "EthnicCategory2021" as ethnic_category2021,
    "ConsMechanismMH" as cons_mechanism_mh,
    "CareProfLocalId" as care_prof_local_id,
    "MHDropInContactOutcome" as mh_drop_in_contact_outcome,
    "OrgIDReceiving" as org_id_receiving,
    "MHS302UniqID" as mhs302_uniq_id,
    "OrgIDProv" as org_id_prov,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqCareProfLocalID" as uniq_care_prof_local_id,
    "AgeRepPeriodStart" as age_rep_period_start,
    "AgeRepPeriodEnd" as age_rep_period_end,
    "UniqMonthID" as uniq_month_id,
    "NHSDEthnicity" as nhsd_ethnicity,
    "EFFECTIVE_FROM" as effective_from,
    "UniqMHDropInContactId" as uniq_mh_drop_in_contact_id,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS302MHDropInContact') }}
