-- Raw layer model for mhsds.MHS302MHDropInContact
-- Source: "DATA_LAKE"."MHSDS"
-- Description: Mental Health Services Data Set (MHSDS)
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "MHDropInContactId" as mh_drop_in_contact_id,
    "CareContactDateMHDropInContact" as care_contact_date_mh_drop_in_contact,
    "OrgIDComm" as org_id_comm,
    "MHDropInContactServiceType" as mh_drop_in_contact_service_type,
    "StartTimeDropInContact" as start_time_drop_in_contact,
    "EndTimeDropInContact" as end_time_drop_in_contact,
    "LocalPatientId" as local_patient_id,
    "NHSNumber Pseudo" as nhs_number_pseudo,
    "PersonBirthDate Pseudo" as person_birth_date_pseudo,
    "GenderIDCode" as gender_id_code,
    "GenderSameAtBirth" as gender_same_at_birth,
    "EthnicCategory" as ethnic_category,
    "EthnicCategory2021" as ethnic_category2021,
    "ConsMechanismMH" as cons_mechanism_mh,
    "CareProfLocalId" as care_prof_local_id,
    "MHDropInContactOutcome" as mh_drop_in_contact_outcome,
    "OrgIDReceiving" as org_id_receiving,
    "MHS302UniqID" as mhs302_uniq_id,
    "OrgIDProv" as org_id_prov,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqCareProfLocalID" as uniq_care_prof_local_id,
    "AgeRepPeriodStart" as age_rep_period_start,
    "AgeRepPeriodEnd" as age_rep_period_end,
    "UniqMonthID" as uniq_month_id,
    "NHSDEthnicity" as nhsd_ethnicity,
    "EFFECTIVE_FROM" as effective_from,
    "UniqMHDropInContactId" as uniq_mh_drop_in_contact_id,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS302MHDropInContact') }}
