-- Raw layer model for mhsds.MHS001MPI
-- Source: "DATA_LAKE"."MHSDS"
-- Description: Mental Health Services Data Set (MHSDS)
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "LocalPatientId" as local_patient_id,
    "OrgIDLocalPatientId" as org_id_local_patient_id,
    "OrgIDResidenceResp" as org_id_residence_resp,
    "OrgIDEduEstab" as org_id_edu_estab,
    "NHSNumber Pseudo" as nhs_number_pseudo,
    "NHSNumberStatus" as nhs_number_status,
    "PersonBirthDate Pseudo" as person_birth_date_pseudo,
    "Postcode Pseudo" as postcode_pseudo,
    "GenderIDCode" as gender_id_code,
    "GenderSameAtBirth" as gender_same_at_birth,
    "Gender" as gender,
    "MaritalStatus" as marital_status,
    "EthnicCategory" as ethnic_category,
    "EthnicCategory2021" as ethnic_category2021,
    "LanguageCodePreferred" as language_code_preferred,
    "PersDeathDate" as pers_death_date,
    "RecordNumber" as record_number,
    "MHS001UniqID" as mhs001_uniq_id,
    "OrgIDProv" as org_id_prov,
    "OrgIDCCGRes" as org_idccg_res,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "AgeRepPeriodStart" as age_rep_period_start,
    "AgeRepPeriodEnd" as age_rep_period_end,
    "AgeDeath" as age_death,
    "PostcodeDistrict" as postcode_district,
    "DefaultPostcode Pseudo" as default_postcode_pseudo,
    "LSOA2011" as lsoa2011,
    "LSOA" as lsoa,
    "LSOA2021" as lsoa2021,
    "LADistrictAuth" as la_district_auth,
    "County" as county,
    "ElectoralWard" as electoral_ward,
    "UniqMonthID" as uniq_month_id,
    "NHSDEthnicity" as nhsd_ethnicity,
    "PatMRecInRP" as pat_mrec_in_rp,
    "RecordStartDate" as record_start_date,
    "RecordEndDate" as record_end_date,
    "CCGGPRes" as ccggp_res,
    "IMDQuart" as imd_quart,
    "EFFECTIVE_FROM" as effective_from,
    "OrgIDICBRes" as org_idicb_res,
    "OrgIDICSRes" as org_idics_res,
    "EthnicityHigher" as ethnicity_higher,
    "EthnicityLow" as ethnicity_low,
    "LDAFlag" as lda_flag,
    "STPICRECCCG" as stpicrecccg,
    "RegionICRECCCG" as region_icrecccg,
    "EmploymentNationalLatest" as employment_national_latest,
    "EmploymentProviderLatest" as employment_provider_latest,
    "AccommodationNationalLatest" as accommodation_national_latest,
    "AccommodationProviderLatest" as accommodation_provider_latest,
    "OrgIDSubICBLocResidence" as org_id_sub_icb_loc_residence,
    "ICRECSUBICB" as icrecsubicb,
    "ICRECCCG" as icrecccg,
    "ICRECSUBICBNAME" as icrecsubicbname,
    "ICRECCCGNAME" as icrecccgname,
    "RegionICRECSUBICB" as region_icrecsubicb,
    "RegionICRECSUBICBName" as region_icrecsubicb_name,
    "ICRECICB" as icrecicb,
    "ICRECICBName" as icrecicb_name,
    "NHSEValidatedPostcode Pseudo" as nhse_validated_postcode_pseudo,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicOrgIDCCGGPPractice" as dmic_org_idccggp_practice,
    "dmicEthnicCategoryGroup" as dmic_ethnic_category_group,
    "dmicAgeGroupRPEndDate" as dmic_age_group_rp_end_date,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "dmIcbRegistrationSubmitted" as dm_icb_registration_submitted,
    "dmSubIcbRegistrationSubmitted" as dm_sub_icb_registration_submitted,
    "dmIcbResidenceSubmitted" as dm_icb_residence_submitted,
    "dmSubIcbResidenceSubmitted" as dm_sub_icb_residence_submitted,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS001MPI') }}
