{{
    config(
        description="Raw layer (SUS Monthly admitted patient care episodes and procedures). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.SUS_AE.EncounterBilling \ndbt: source(''sus_apc_monthly'', ''EncounterBilling'') \nColumns:\n  SK_EncounterID -> sk_encounter_id\n  SK_EncounterID -> sk_encounter_id_1\n  SK_ServiceProviderID -> sk_service_provider_id\n  SK_ServiceProviderID -> sk_service_provider_id_1\n  SK_CommissionerID -> sk_commissioner_id\n  SK_CommissionerID -> sk_commissioner_id_1\n  ScheduleCode -> schedule_code\n  ScheduleCode -> schedule_code_1\n  ContractSuffix -> contract_suffix\n  ContractSuffix -> contract_suffix_1\n  EncounterRowID -> encounter_row_id\n  EncounterRowID -> encounter_row_id_1\n  TotalCost -> total_cost\n  TotalCost -> total_cost_1\n  MFFApplied -> mff_applied\n  MFFApplied -> mff_applied_1\n  IsShortStay -> is_short_stay\n  IsShortStay -> is_short_stay_1\n  LongStayPayment -> long_stay_payment\n  LongStayPayment -> long_stay_payment_1\n  ServiceAdjustmentApplied -> service_adjustment_applied\n  ServiceAdjustmentApplied -> service_adjustment_applied_1\n  CriticalCareDayCount -> critical_care_day_count\n  CriticalCareDayCount -> critical_care_day_count_1\n  ApplicableTariff -> applicable_tariff\n  ApplicableTariff -> applicable_tariff_1\n  SK_Date -> sk_date\n  SK_Date -> sk_date_1\n  BaseCost -> base_cost\n  BaseCost -> base_cost_1\n  Schedule_Description -> schedule_description\n  Schedule_Description -> schedule_description_1\n  POD_Description -> pod_description\n  POD_Description -> pod_description_1\n  LocalCostCode -> local_cost_code\n  LocalCostCode -> local_cost_code_1\n  PBR_FINAL_TARIFF -> pbr_final_tariff\n  PBR_FINAL_TARIFF -> pbr_final_tariff_1\n  SK_TariffTypeID -> sk_tariff_type_id\n  SK_TariffTypeID -> sk_tariff_type_id_1\n  Is_Pbr -> is_pbr\n  Is_Pbr -> is_pbr_1\n  HRG_Code -> hrg_code\n  HRG_Code -> hrg_code_1\n  ActivityPeriod -> activity_period\n  ActivityPeriod -> activity_period_1"
    )
}}
select
    "SK_EncounterID" as sk_encounter_id,
    "SK_EncounterID" as sk_encounter_id_1,
    "SK_ServiceProviderID" as sk_service_provider_id,
    "SK_ServiceProviderID" as sk_service_provider_id_1,
    "SK_CommissionerID" as sk_commissioner_id,
    "SK_CommissionerID" as sk_commissioner_id_1,
    "ScheduleCode" as schedule_code,
    "ScheduleCode" as schedule_code_1,
    "ContractSuffix" as contract_suffix,
    "ContractSuffix" as contract_suffix_1,
    "EncounterRowID" as encounter_row_id,
    "EncounterRowID" as encounter_row_id_1,
    "TotalCost" as total_cost,
    "TotalCost" as total_cost_1,
    "MFFApplied" as mff_applied,
    "MFFApplied" as mff_applied_1,
    "IsShortStay" as is_short_stay,
    "IsShortStay" as is_short_stay_1,
    "LongStayPayment" as long_stay_payment,
    "LongStayPayment" as long_stay_payment_1,
    "ServiceAdjustmentApplied" as service_adjustment_applied,
    "ServiceAdjustmentApplied" as service_adjustment_applied_1,
    "CriticalCareDayCount" as critical_care_day_count,
    "CriticalCareDayCount" as critical_care_day_count_1,
    "ApplicableTariff" as applicable_tariff,
    "ApplicableTariff" as applicable_tariff_1,
    "SK_Date" as sk_date,
    "SK_Date" as sk_date_1,
    "BaseCost" as base_cost,
    "BaseCost" as base_cost_1,
    "Schedule_Description" as schedule_description,
    "Schedule_Description" as schedule_description_1,
    "POD_Description" as pod_description,
    "POD_Description" as pod_description_1,
    "LocalCostCode" as local_cost_code,
    "LocalCostCode" as local_cost_code_1,
    "PBR_FINAL_TARIFF" as pbr_final_tariff,
    "PBR_FINAL_TARIFF" as pbr_final_tariff_1,
    "SK_TariffTypeID" as sk_tariff_type_id,
    "SK_TariffTypeID" as sk_tariff_type_id_1,
    "Is_Pbr" as is_pbr,
    "Is_Pbr" as is_pbr_1,
    "HRG_Code" as hrg_code,
    "HRG_Code" as hrg_code_1,
    "ActivityPeriod" as activity_period,
    "ActivityPeriod" as activity_period_1
from {{ source('sus_apc_monthly', 'EncounterBilling') }}
