{{
    config(
        description="Raw layer (Waiting lists and patient pathway data). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.WL.WL_OpenPathways_Data \ndbt: source(''wl'', ''WL_OpenPathways_Data'') \nColumns:\n  DATE_AND_TIME_DATA_SET_CREATED -> date_and_time_data_set_created\n  Week_Ending_Date -> week_ending_date\n  Waiting_List_Type -> waiting_list_type\n  Pseudo NHS_NUMBER -> pseudo_nhs_number\n  LOCAL_PATIENT_IDENTIFIER -> local_patient_identifier\n  PERSON_BIRTH_DATE -> person_birth_date\n  PERSON_STATED_GENDER_CODE -> person_stated_gender_code\n  ETHNIC_CATEGORY -> ethnic_category\n  REFERRAL_REQUEST_RECEIVED_DATE -> referral_request_received_date\n  Referral_Identifier -> referral_identifier\n  PATIENT_PATHWAY_IDENTIFIER -> patient_pathway_identifier\n  ORGANISATION_CODE_PATIENT_PATHWAY_IDENTIFIER_ISSUER -> organisation_code_patient_pathway_identifier_issuer\n  SOURCE_OF_REFERRAL -> source_of_referral\n  ORGANISATION_IDENTIFIER_CODE_OF_PROVIDER -> organisation_identifier_code_of_provider\n  ORGANISATION_SITE_IDENTIFIER_OF_TREATMENT -> organisation_site_identifier_of_treatment\n  MAIN_SPECIALTY_CODE -> main_specialty_code\n  ACTIVITY_TREATMENT_FUNCTION_CODE -> activity_treatment_function_code\n  CONSULTANT_CODE -> consultant_code\n  REFERRAL_TO_TREATMENT_PERIOD_START_DATE -> referral_to_treatment_period_start_date\n  Current_Pathway_Period_Start_Date -> current_pathway_period_start_date\n  Outpatient_Future_Appointment_Date -> outpatient_future_appointment_date\n  Due_Date -> due_date\n  Outpatient_Appointment_Date -> outpatient_appointment_date\n  Date_Last_Attended -> date_last_attended\n  Last_DNA_Date -> last_dna_date\n  Cancellation_Date -> cancellation_date\n  OUTCOME_OF_ATTENDANCE_CODE -> outcome_of_attendance_code\n  Local_Outcome_Of_Attendance -> local_outcome_of_attendance\n  TCI_Date -> tci_date\n  REFERRAL_TO_TREATMENT_PERIOD_STATUS -> referral_to_treatment_period_status\n  Local_RTT_Status_Code -> local_rtt_status_code\n  DECISION_TO_ADMIT_DATE -> decision_to_admit_date\n  Proposed_Procedure_OPCS_Code -> proposed_procedure_opcs_code\n  ORGANISATION_IDENTIFIER_CODE_OF_COMMISSIONER -> organisation_identifier_code_of_commissioner\n  ADMISSION_METHOD_CODE_HOSPITAL_PROVIDER_SPELL -> admission_method_code_hospital_provider_spell\n  PRIORITY_TYPE_CODE -> priority_type_code\n  REFERRAL_TO_TREATMENT_PERIOD_END_DATE -> referral_to_treatment_period_end_date\n  Procedure_Priority_Code -> procedure_priority_code\n  Diagnostic_Priority_Code -> diagnostic_priority_code\n  Outpatient_Priority_Code -> outpatient_priority_code\n  Date_Of_Last_Priority_Review -> date_of_last_priority_review\n  Last_PAS_Validation_Performed_By -> last_pas_validation_performed_by\n  Last_PAS_Validation_Date -> last_pas_validation_date\n  Last_PAS_Validation_Comments -> last_pas_validation_comments\n  Inclusion_On_Cancer_PTL -> inclusion_on_cancer_ptl\n  derSubmissionId -> der_submission_id\n  derRowId -> der_row_id\n  Der_Age_WeekEndingDate -> der_age_week_ending_date\n  Der_Age_at_Referral_To_Treatment_Period_Start_Date -> der_age_at_referral_to_treatment_period_start_date\n  Der_AgeBand_WeekEndingDate -> der_age_band_week_ending_date\n  Der_AgeBand_at_Referral_To_Treatment_Period_Start_Date -> der_age_band_at_referral_to_treatment_period_start_date\n  derCCGofPractice -> der_ccg_of_practice\n  derCCGofResidence -> der_ccg_of_residence\n  derPracticeCode -> der_practice_code\n  derLSOA -> der_lsoa\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  INTENDED_MANAGEMENT_CODE -> intended_management_code\n  Capacity_Status -> capacity_status\n  Requires_Alternative_Capacity -> requires_alternative_capacity\n  ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE -> asa_physical_status_classification_system_code\n  Outcome_Of_Patient_Contact -> outcome_of_patient_contact\n  Transfer_Status -> transfer_status\n  Mutual_Aid_Accepting_Provider -> mutual_aid_accepting_provider\n  FIRST_ACTIVITY_DATE -> first_activity_date\n  FIRST_ACTIVITY_TYPE -> first_activity_type\n  DECISION_TO_TREAT_DATE -> decision_to_treat_date\n  TCI_Date_Provided -> tci_date_provided\n  Preliminary_Screening_And_Risk_Assessment_Date -> preliminary_screening_and_risk_assessment_date\n  Action_Following_Preliminary_Screening_And_Risk_Assessment -> action_following_preliminary_screening_and_risk_assessment\n  derLSOA2021 -> der_lsoa2021\n  ORIGINAL_REFERRAL_REQUEST_RECEIVED_DATE -> original_referral_request_received_date\n  ORGANISATION_IDENTIFIER_REFERRING_ORGANISATION -> organisation_identifier_referring_organisation\n  UNIQUE_BOOKING_REFERENCE_NUMBER -> unique_booking_reference_number"
    )
}}
select
    "DATE_AND_TIME_DATA_SET_CREATED" as date_and_time_data_set_created,
    "Week_Ending_Date" as week_ending_date,
    "Waiting_List_Type" as waiting_list_type,
    "Pseudo NHS_NUMBER" as pseudo_nhs_number,
    "LOCAL_PATIENT_IDENTIFIER" as local_patient_identifier,
    "PERSON_BIRTH_DATE" as person_birth_date,
    "PERSON_STATED_GENDER_CODE" as person_stated_gender_code,
    "ETHNIC_CATEGORY" as ethnic_category,
    "REFERRAL_REQUEST_RECEIVED_DATE" as referral_request_received_date,
    "Referral_Identifier" as referral_identifier,
    "PATIENT_PATHWAY_IDENTIFIER" as patient_pathway_identifier,
    "ORGANISATION_CODE_PATIENT_PATHWAY_IDENTIFIER_ISSUER" as organisation_code_patient_pathway_identifier_issuer,
    "SOURCE_OF_REFERRAL" as source_of_referral,
    "ORGANISATION_IDENTIFIER_CODE_OF_PROVIDER" as organisation_identifier_code_of_provider,
    "ORGANISATION_SITE_IDENTIFIER_OF_TREATMENT" as organisation_site_identifier_of_treatment,
    "MAIN_SPECIALTY_CODE" as main_specialty_code,
    "ACTIVITY_TREATMENT_FUNCTION_CODE" as activity_treatment_function_code,
    "CONSULTANT_CODE" as consultant_code,
    "REFERRAL_TO_TREATMENT_PERIOD_START_DATE" as referral_to_treatment_period_start_date,
    "Current_Pathway_Period_Start_Date" as current_pathway_period_start_date,
    "Outpatient_Future_Appointment_Date" as outpatient_future_appointment_date,
    "Due_Date" as due_date,
    "Outpatient_Appointment_Date" as outpatient_appointment_date,
    "Date_Last_Attended" as date_last_attended,
    "Last_DNA_Date" as last_dna_date,
    "Cancellation_Date" as cancellation_date,
    "OUTCOME_OF_ATTENDANCE_CODE" as outcome_of_attendance_code,
    "Local_Outcome_Of_Attendance" as local_outcome_of_attendance,
    "TCI_Date" as tci_date,
    "REFERRAL_TO_TREATMENT_PERIOD_STATUS" as referral_to_treatment_period_status,
    "Local_RTT_Status_Code" as local_rtt_status_code,
    "DECISION_TO_ADMIT_DATE" as decision_to_admit_date,
    "Proposed_Procedure_OPCS_Code" as proposed_procedure_opcs_code,
    "ORGANISATION_IDENTIFIER_CODE_OF_COMMISSIONER" as organisation_identifier_code_of_commissioner,
    "ADMISSION_METHOD_CODE_HOSPITAL_PROVIDER_SPELL" as admission_method_code_hospital_provider_spell,
    "PRIORITY_TYPE_CODE" as priority_type_code,
    "REFERRAL_TO_TREATMENT_PERIOD_END_DATE" as referral_to_treatment_period_end_date,
    "Procedure_Priority_Code" as procedure_priority_code,
    "Diagnostic_Priority_Code" as diagnostic_priority_code,
    "Outpatient_Priority_Code" as outpatient_priority_code,
    "Date_Of_Last_Priority_Review" as date_of_last_priority_review,
    "Last_PAS_Validation_Performed_By" as last_pas_validation_performed_by,
    "Last_PAS_Validation_Date" as last_pas_validation_date,
    "Last_PAS_Validation_Comments" as last_pas_validation_comments,
    "Inclusion_On_Cancer_PTL" as inclusion_on_cancer_ptl,
    "derSubmissionId" as der_submission_id,
    "derRowId" as der_row_id,
    "Der_Age_WeekEndingDate" as der_age_week_ending_date,
    "Der_Age_at_Referral_To_Treatment_Period_Start_Date" as der_age_at_referral_to_treatment_period_start_date,
    "Der_AgeBand_WeekEndingDate" as der_age_band_week_ending_date,
    "Der_AgeBand_at_Referral_To_Treatment_Period_Start_Date" as der_age_band_at_referral_to_treatment_period_start_date,
    "derCCGofPractice" as der_ccg_of_practice,
    "derCCGofResidence" as der_ccg_of_residence,
    "derPracticeCode" as der_practice_code,
    "derLSOA" as der_lsoa,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "INTENDED_MANAGEMENT_CODE" as intended_management_code,
    "Capacity_Status" as capacity_status,
    "Requires_Alternative_Capacity" as requires_alternative_capacity,
    "ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE" as asa_physical_status_classification_system_code,
    "Outcome_Of_Patient_Contact" as outcome_of_patient_contact,
    "Transfer_Status" as transfer_status,
    "Mutual_Aid_Accepting_Provider" as mutual_aid_accepting_provider,
    "FIRST_ACTIVITY_DATE" as first_activity_date,
    "FIRST_ACTIVITY_TYPE" as first_activity_type,
    "DECISION_TO_TREAT_DATE" as decision_to_treat_date,
    "TCI_Date_Provided" as tci_date_provided,
    "Preliminary_Screening_And_Risk_Assessment_Date" as preliminary_screening_and_risk_assessment_date,
    "Action_Following_Preliminary_Screening_And_Risk_Assessment" as action_following_preliminary_screening_and_risk_assessment,
    "derLSOA2021" as der_lsoa2021,
    "ORIGINAL_REFERRAL_REQUEST_RECEIVED_DATE" as original_referral_request_received_date,
    "ORGANISATION_IDENTIFIER_REFERRING_ORGANISATION" as organisation_identifier_referring_organisation,
    "UNIQUE_BOOKING_REFERENCE_NUMBER" as unique_booking_reference_number
from {{ source('wl', 'WL_OpenPathways_Data') }}
