{{
    config(
        description="Raw layer (Community services dataset). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.CSDS.CYP000Header \ndbt: source(''csds'', ''CYP000Header'') \nColumns:\n  DATA SET VERSION NUMBER -> data_set_version_number\n  ORGANISATION IDENTIFIER (CODE OF PROVIDER) -> organisation_identifier_code_of_provider\n  ORGANISATION CODE (CODE OF PROVIDER) -> organisation_code_code_of_provider\n  ORGANISATION IDENTIFIER (CODE OF SUBMITTING ORGANISATION) -> organisation_identifier_code_of_submitting_organisation\n  ORGANISATION CODE (CODE OF SUBMITTING ORGANISATION) -> organisation_code_code_of_submitting_organisation\n  REPORTING PERIOD START DATE -> reporting_period_start_date\n  REPORTING PERIOD END DATE -> reporting_period_end_date\n  DATE AND TIME DATA SET CREATED -> date_and_time_data_set_created\n  PRIMARY DATA COLLECTION SYSTEM IN USE -> primary_data_collection_system_in_use\n  EFFECTIVE FROM -> effective_from\n  END PROCESSING DATE TIME -> end_processing_date_time\n  CYP000 UNIQUE ID -> cyp000_unique_id\n  UNIQUE SUBMISSION ID -> unique_submission_id\n  BSP UNIQUE ID -> bsp_unique_id\n  UPLOAD DATE TIME -> upload_date_time\n  FILE TYPE -> file_type\n  UNIQUE MONTH ID -> unique_month_id\n  TOTAL CYP001 POST PROCESSING ROW COUNT -> total_cyp001_post_processing_row_count\n  TOTAL CYP002 POST PROCESSING ROW COUNT -> total_cyp002_post_processing_row_count\n  TOTAL CYP003 POST PROCESSING ROW COUNT -> total_cyp003_post_processing_row_count\n  TOTAL CYP004 POST PROCESSING ROW COUNT -> total_cyp004_post_processing_row_count\n  TOTAL CYP005 POST PROCESSING ROW COUNT -> total_cyp005_post_processing_row_count\n  TOTAL CYP006 POST PROCESSING ROW COUNT -> total_cyp006_post_processing_row_count\n  TOTAL CYP007 POST PROCESSING ROW COUNT -> total_cyp007_post_processing_row_count\n  TOTAL CYP101 POST PROCESSING ROW COUNT -> total_cyp101_post_processing_row_count\n  TOTAL CYP102 POST PROCESSING ROW COUNT -> total_cyp102_post_processing_row_count\n  TOTAL CYP103 POST PROCESSING ROW COUNT -> total_cyp103_post_processing_row_count\n  TOTAL CYP104 POST PROCESSING ROW COUNT -> total_cyp104_post_processing_row_count\n  TOTAL CYP105 POST PROCESSING ROW COUNT -> total_cyp105_post_processing_row_count\n  TOTAL CYP201 POST PROCESSING ROW COUNT -> total_cyp201_post_processing_row_count\n  TOTAL CYP202 POST PROCESSING ROW COUNT -> total_cyp202_post_processing_row_count\n  TOTAL CYP301 POST PROCESSING ROW COUNT -> total_cyp301_post_processing_row_count\n  TOTAL CYP401 POST PROCESSING ROW COUNT -> total_cyp401_post_processing_row_count\n  TOTAL CYP402 POST PROCESSING ROW COUNT -> total_cyp402_post_processing_row_count\n  TOTAL CYP403 POST PROCESSING ROW COUNT -> total_cyp403_post_processing_row_count\n  TOTAL CYP404 POST PROCESSING ROW COUNT -> total_cyp404_post_processing_row_count\n  TOTAL CYP501 POST PROCESSING ROW COUNT -> total_cyp501_post_processing_row_count\n  TOTAL CYP502 POST PROCESSING ROW COUNT -> total_cyp502_post_processing_row_count\n  TOTAL CYP601 POST PROCESSING ROW COUNT -> total_cyp601_post_processing_row_count\n  TOTAL CYP602 POST PROCESSING ROW COUNT -> total_cyp602_post_processing_row_count\n  TOTAL CYP603 POST PROCESSING ROW COUNT -> total_cyp603_post_processing_row_count\n  TOTAL CYP604 POST PROCESSING ROW COUNT -> total_cyp604_post_processing_row_count\n  TOTAL CYP605 POST PROCESSING ROW COUNT -> total_cyp605_post_processing_row_count\n  TOTAL CYP606 POST PROCESSING ROW COUNT -> total_cyp606_post_processing_row_count\n  TOTAL CYP607 POST PROCESSING ROW COUNT -> total_cyp607_post_processing_row_count\n  TOTAL CYP608 POST PROCESSING ROW COUNT -> total_cyp608_post_processing_row_count\n  TOTAL CYP609 POST PROCESSING ROW COUNT -> total_cyp609_post_processing_row_count\n  TOTAL CYP610 POST PROCESSING ROW COUNT -> total_cyp610_post_processing_row_count\n  TOTAL CYP611 POST PROCESSING ROW COUNT -> total_cyp611_post_processing_row_count\n  TOTAL CYP612 POST PROCESSING ROW COUNT -> total_cyp612_post_processing_row_count\n  TOTAL CYP613 POST PROCESSING ROW COUNT -> total_cyp613_post_processing_row_count\n  TOTAL CYP901 POST PROCESSING ROW COUNT -> total_cyp901_post_processing_row_count\n  TOTAL RECORDS -> total_records\n  CYPHS SUBMISSION RECORD COUNT -> cyphs_submission_record_count\n  TOTAL CYP008 POST PROCESSING ROW COUNT -> total_cyp008_post_processing_row_count\n  dmicImportLogId -> dmic_import_log_id\n  dmicMonthId -> dmic_month_id\n  dmicSystemId -> dmic_system_id\n  dmicCCG -> dmic_ccg"
    )
}}
select
    "DATA SET VERSION NUMBER" as data_set_version_number,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (CODE OF PROVIDER)" as organisation_code_code_of_provider,
    "ORGANISATION IDENTIFIER (CODE OF SUBMITTING ORGANISATION)" as organisation_identifier_code_of_submitting_organisation,
    "ORGANISATION CODE (CODE OF SUBMITTING ORGANISATION)" as organisation_code_code_of_submitting_organisation,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date,
    "DATE AND TIME DATA SET CREATED" as date_and_time_data_set_created,
    "PRIMARY DATA COLLECTION SYSTEM IN USE" as primary_data_collection_system_in_use,
    "EFFECTIVE FROM" as effective_from,
    "END PROCESSING DATE TIME" as end_processing_date_time,
    "CYP000 UNIQUE ID" as cyp000_unique_id,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UPLOAD DATE TIME" as upload_date_time,
    "FILE TYPE" as file_type,
    "UNIQUE MONTH ID" as unique_month_id,
    "TOTAL CYP001 POST PROCESSING ROW COUNT" as total_cyp001_post_processing_row_count,
    "TOTAL CYP002 POST PROCESSING ROW COUNT" as total_cyp002_post_processing_row_count,
    "TOTAL CYP003 POST PROCESSING ROW COUNT" as total_cyp003_post_processing_row_count,
    "TOTAL CYP004 POST PROCESSING ROW COUNT" as total_cyp004_post_processing_row_count,
    "TOTAL CYP005 POST PROCESSING ROW COUNT" as total_cyp005_post_processing_row_count,
    "TOTAL CYP006 POST PROCESSING ROW COUNT" as total_cyp006_post_processing_row_count,
    "TOTAL CYP007 POST PROCESSING ROW COUNT" as total_cyp007_post_processing_row_count,
    "TOTAL CYP101 POST PROCESSING ROW COUNT" as total_cyp101_post_processing_row_count,
    "TOTAL CYP102 POST PROCESSING ROW COUNT" as total_cyp102_post_processing_row_count,
    "TOTAL CYP103 POST PROCESSING ROW COUNT" as total_cyp103_post_processing_row_count,
    "TOTAL CYP104 POST PROCESSING ROW COUNT" as total_cyp104_post_processing_row_count,
    "TOTAL CYP105 POST PROCESSING ROW COUNT" as total_cyp105_post_processing_row_count,
    "TOTAL CYP201 POST PROCESSING ROW COUNT" as total_cyp201_post_processing_row_count,
    "TOTAL CYP202 POST PROCESSING ROW COUNT" as total_cyp202_post_processing_row_count,
    "TOTAL CYP301 POST PROCESSING ROW COUNT" as total_cyp301_post_processing_row_count,
    "TOTAL CYP401 POST PROCESSING ROW COUNT" as total_cyp401_post_processing_row_count,
    "TOTAL CYP402 POST PROCESSING ROW COUNT" as total_cyp402_post_processing_row_count,
    "TOTAL CYP403 POST PROCESSING ROW COUNT" as total_cyp403_post_processing_row_count,
    "TOTAL CYP404 POST PROCESSING ROW COUNT" as total_cyp404_post_processing_row_count,
    "TOTAL CYP501 POST PROCESSING ROW COUNT" as total_cyp501_post_processing_row_count,
    "TOTAL CYP502 POST PROCESSING ROW COUNT" as total_cyp502_post_processing_row_count,
    "TOTAL CYP601 POST PROCESSING ROW COUNT" as total_cyp601_post_processing_row_count,
    "TOTAL CYP602 POST PROCESSING ROW COUNT" as total_cyp602_post_processing_row_count,
    "TOTAL CYP603 POST PROCESSING ROW COUNT" as total_cyp603_post_processing_row_count,
    "TOTAL CYP604 POST PROCESSING ROW COUNT" as total_cyp604_post_processing_row_count,
    "TOTAL CYP605 POST PROCESSING ROW COUNT" as total_cyp605_post_processing_row_count,
    "TOTAL CYP606 POST PROCESSING ROW COUNT" as total_cyp606_post_processing_row_count,
    "TOTAL CYP607 POST PROCESSING ROW COUNT" as total_cyp607_post_processing_row_count,
    "TOTAL CYP608 POST PROCESSING ROW COUNT" as total_cyp608_post_processing_row_count,
    "TOTAL CYP609 POST PROCESSING ROW COUNT" as total_cyp609_post_processing_row_count,
    "TOTAL CYP610 POST PROCESSING ROW COUNT" as total_cyp610_post_processing_row_count,
    "TOTAL CYP611 POST PROCESSING ROW COUNT" as total_cyp611_post_processing_row_count,
    "TOTAL CYP612 POST PROCESSING ROW COUNT" as total_cyp612_post_processing_row_count,
    "TOTAL CYP613 POST PROCESSING ROW COUNT" as total_cyp613_post_processing_row_count,
    "TOTAL CYP901 POST PROCESSING ROW COUNT" as total_cyp901_post_processing_row_count,
    "TOTAL RECORDS" as total_records,
    "CYPHS SUBMISSION RECORD COUNT" as cyphs_submission_record_count,
    "TOTAL CYP008 POST PROCESSING ROW COUNT" as total_cyp008_post_processing_row_count,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicMonthId" as dmic_month_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCG" as dmic_ccg
from {{ source('csds', 'CYP000Header') }}
