{{
    config(
        description="Raw layer (Mental Health Services Data Set (MHSDS)). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.MHSDS.MHS201CareContact \ndbt: source(''mhsds'', ''MHS201CareContact'') \nColumns:\n  SK -> sk\n  CareContactId -> care_contact_id\n  ServiceRequestId -> service_request_id\n  CareContDate -> care_cont_date\n  CareContTime -> care_cont_time\n  OtherCareProfTeamLocalID -> other_care_prof_team_local_id\n  CareProfTeamLocalId -> care_prof_team_local_id\n  OrgIDComm -> org_id_comm\n  AdminCatCode -> admin_cat_code\n  SpecialisedMHServiceCode -> specialised_mh_service_code\n  ClinContDurOfCareCont -> clin_cont_dur_of_care_cont\n  ConsType -> cons_type\n  CareContSubj -> care_cont_subj\n  ConsMechanismMH -> cons_mechanism_mh\n  ConsMediumUsed -> cons_medium_used\n  ActLocTypeCode -> act_loc_type_code\n  PlaceOfSafetyInd -> place_of_safety_ind\n  SiteIDOfTreat -> site_id_of_treat\n  GroupTherapyInd -> group_therapy_ind\n  LanguageCodeTreat -> language_code_treat\n  InterpreterPresentInd -> interpreter_present_ind\n  ComPeriMHPartAssessOfferInd -> com_peri_mh_part_assess_offer_ind\n  PlannedCareContIndicator -> planned_care_cont_indicator\n  CareContPatientTherMode -> care_cont_patient_ther_mode\n  AttendStatus -> attend_status\n  AttendOrDNACode -> attend_or_dna_code\n  EarliestReasonOfferDate -> earliest_reason_offer_date\n  EarliestClinAppDate -> earliest_clin_app_date\n  CareContCancelDate -> care_cont_cancel_date\n  CareContCancelReas -> care_cont_cancel_reas\n  RepApptOfferDate -> rep_appt_offer_date\n  RepApptBookDate -> rep_appt_book_date\n  ReasonableAdjustmentMade -> reasonable_adjustment_made\n  ReasonPatientNoIMCA -> reason_patient_no_imca\n  ReasonPatientNoIMHA -> reason_patient_no_imha\n  RecordNumber -> record_number\n  MHS201UniqID -> mhs201_uniq_id\n  OrgIDProv -> org_id_prov\n  Person_ID -> person_id\n  UniqSubmissionID -> uniq_submission_id\n  UniqServReqID -> uniq_serv_req_id\n  UniqCareContID -> uniq_care_cont_id\n  AgeCareContDate -> age_care_cont_date\n  ContLocDistanceHome -> cont_loc_distance_home\n  TimeReferAndCareContact -> time_refer_and_care_contact\n  UniqMonthID -> uniq_month_id\n  EFFECTIVE_FROM -> effective_from\n  UniqOtherCareProfTeamLocalID -> uniq_other_care_prof_team_local_id\n  UniqCareProfTeamID -> uniq_care_prof_team_id\n  RowNumber -> row_number\n  dmicImportLogId -> dmic_import_log_id\n  dmicMinContactDate -> dmic_min_contact_date\n  dmicMaxContactDate -> dmic_max_contact_date\n  dmicSystemId -> dmic_system_id\n  dmicCCGCode -> dmic_ccg_code\n  dmicDateAdded -> dmic_date_added\n  dmIcbCommissioner -> dm_icb_commissioner\n  dmSubIcbCommissioner -> dm_sub_icb_commissioner\n  dmCommissionerDerivationReason -> dm_commissioner_derivation_reason\n  FileType -> file_type\n  ReportingPeriodStartDate -> reporting_period_start_date\n  ReportingPeriodEndDate -> reporting_period_end_date\n  dmicDataset -> dmic_dataset"
    )
}}
select
    "SK" as sk,
    "CareContactId" as care_contact_id,
    "ServiceRequestId" as service_request_id,
    "CareContDate" as care_cont_date,
    "CareContTime" as care_cont_time,
    "OtherCareProfTeamLocalID" as other_care_prof_team_local_id,
    "CareProfTeamLocalId" as care_prof_team_local_id,
    "OrgIDComm" as org_id_comm,
    "AdminCatCode" as admin_cat_code,
    "SpecialisedMHServiceCode" as specialised_mh_service_code,
    "ClinContDurOfCareCont" as clin_cont_dur_of_care_cont,
    "ConsType" as cons_type,
    "CareContSubj" as care_cont_subj,
    "ConsMechanismMH" as cons_mechanism_mh,
    "ConsMediumUsed" as cons_medium_used,
    "ActLocTypeCode" as act_loc_type_code,
    "PlaceOfSafetyInd" as place_of_safety_ind,
    "SiteIDOfTreat" as site_id_of_treat,
    "GroupTherapyInd" as group_therapy_ind,
    "LanguageCodeTreat" as language_code_treat,
    "InterpreterPresentInd" as interpreter_present_ind,
    "ComPeriMHPartAssessOfferInd" as com_peri_mh_part_assess_offer_ind,
    "PlannedCareContIndicator" as planned_care_cont_indicator,
    "CareContPatientTherMode" as care_cont_patient_ther_mode,
    "AttendStatus" as attend_status,
    "AttendOrDNACode" as attend_or_dna_code,
    "EarliestReasonOfferDate" as earliest_reason_offer_date,
    "EarliestClinAppDate" as earliest_clin_app_date,
    "CareContCancelDate" as care_cont_cancel_date,
    "CareContCancelReas" as care_cont_cancel_reas,
    "RepApptOfferDate" as rep_appt_offer_date,
    "RepApptBookDate" as rep_appt_book_date,
    "ReasonableAdjustmentMade" as reasonable_adjustment_made,
    "ReasonPatientNoIMCA" as reason_patient_no_imca,
    "ReasonPatientNoIMHA" as reason_patient_no_imha,
    "RecordNumber" as record_number,
    "MHS201UniqID" as mhs201_uniq_id,
    "OrgIDProv" as org_id_prov,
    "Person_ID" as person_id,
    "UniqSubmissionID" as uniq_submission_id,
    "UniqServReqID" as uniq_serv_req_id,
    "UniqCareContID" as uniq_care_cont_id,
    "AgeCareContDate" as age_care_cont_date,
    "ContLocDistanceHome" as cont_loc_distance_home,
    "TimeReferAndCareContact" as time_refer_and_care_contact,
    "UniqMonthID" as uniq_month_id,
    "EFFECTIVE_FROM" as effective_from,
    "UniqOtherCareProfTeamLocalID" as uniq_other_care_prof_team_local_id,
    "UniqCareProfTeamID" as uniq_care_prof_team_id,
    "RowNumber" as row_number,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicMinContactDate" as dmic_min_contact_date,
    "dmicMaxContactDate" as dmic_max_contact_date,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicDateAdded" as dmic_date_added,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FileType" as file_type,
    "ReportingPeriodStartDate" as reporting_period_start_date,
    "ReportingPeriodEndDate" as reporting_period_end_date,
    "dmicDataset" as dmic_dataset
from {{ source('mhsds', 'MHS201CareContact') }}
