{{
    config(
        description="Raw layer (SUS Monthly admitted patient care episodes and procedures). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.SUS_IP.EncounterDetail \ndbt: source(''sus_apc_monthly'', ''EncounterDetail'') \nColumns:\n  SK_EncounterID -> sk_encounter_id\n  StartDate -> start_date\n  EndDate -> end_date\n  SK_AdmissionMethodID -> sk_admission_method_id\n  SK_AdmissionSourceID -> sk_admission_source_id\n  PASHospitalNumber -> pas_hospital_number\n  HospitalProviderSpellNumber -> hospital_provider_spell_number\n  SpellEpisodeID4 -> spell_episode_id4\n  ExcessBedDays -> excess_bed_days\n  CoreSpellHRG -> core_spell_hrg\n  ExtractType -> extract_type\n  PrimaryProcedure -> primary_procedure\n  PrimaryDiagnosis -> primary_diagnosis\n  SK_SpecialtyID -> sk_specialty_id\n  SK_ConsultantID -> sk_consultant_id\n  UniqueCDSIdentifier -> unique_cds_identifier\n  FCEHRG -> fcehrg\n  DateOfPrimaryProcedure -> date_of_primary_procedure\n  HRG35Code -> hrg35_code\n  HRG4Code -> hrg4_code\n  SK_TreatmentFunctionCode -> sk_treatment_function_code\n  EncounterSequenceNumber -> encounter_sequence_number\n  SK_ServiceProviderID -> sk_service_provider_id\n  SK_PatientID -> sk_patient_id\n  SK_StaffID -> sk_staff_id\n  EncounterStartDateTime -> encounter_start_date_time\n  EncounterEndDateTime -> encounter_end_date_time\n  SK_AdminCategoryID -> sk_admin_category_id\n  AdmissionDate -> admission_date\n  DischargeDate -> discharge_date\n  SK_DischargeMethodID -> sk_discharge_method_id\n  SK_DischargeDestinationID -> sk_discharge_destination_id\n  SK_PatientClassificationID -> sk_patient_classification_id\n  DeleteEncounter -> delete_encounter\n  SK_AgeBandID -> sk_age_band_id\n  PbROrSEM_NotUsed -> pb_ror_sem_not_used\n  Referrer_Code -> referrer_code\n  Referring_Org_Code -> referring_org_code\n  Date_of_Decision_to_Admit -> date_of_decision_to_admit\n  Is_SpCommissioner -> is_sp_commissioner\n  SK_CommissionerID -> sk_commissioner_id\n  SK_Commissioner_PCTID -> sk_commissioner_pctid\n  PROVIDER_REFERENCE_NO -> provider_reference_no\n  AGREEMENT_LINE_NO -> agreement_line_no\n  SC_Service_Line_Code_National -> sc_service_line_code_national\n  SC_Service_Line_Code_National_Spell -> sc_service_line_code_national_spell\n  SC_Service_Line_Code_Local -> sc_service_line_code_local\n  SC_Service_Line_Code_Local_Spell -> sc_service_line_code_local_spell\n  COMMISSIONER_SERIAL_NO -> commissioner_serial_no\n  Age_Group_Intended_at_Epiend -> age_group_intended_at_epiend\n  Ready_For_Discharge_Date -> ready_for_discharge_date\n  Local_Site_Code -> local_site_code\n  Spell_Discharge_Time -> spell_discharge_time\n  Spell_Start_Time -> spell_start_time\n  Local_Sub_Specialty_Code -> local_sub_specialty_code\n  Neonatal_Level_Of_Care -> neonatal_level_of_care\n  SK_Org_CommissionerID -> sk_org_commissioner_id\n  SK_Org_ServiceProviderID -> sk_org_service_provider_id\n  SK_RTTPeriodStatusID -> sk_rtt_period_status_id\n  SK_LegalStatusID -> sk_legal_status_id\n  SK_IntendedManagementID -> sk_intended_management_id\n  RTT_Period_Start_Date -> rtt_period_start_date\n  RTT_Period_End_Date -> rtt_period_end_date\n  Programme_Budget_Code -> programme_budget_code\n  Patient_Pathway_ID -> patient_pathway_id\n  PbROrSEM -> pb_ror_sem\n  Commissioner_Reference_Number -> commissioner_reference_number\n  SK_OperationStatusID -> sk_operation_status_id\n  WardCode_At_Episode_Start -> ward_code_at_episode_start\n  WardCode_At_Episode_End -> ward_code_at_episode_end\n  Spell_Identifier -> spell_identifier"
    )
}}
select
    "SK_EncounterID" as sk_encounter_id,
    "StartDate" as start_date,
    "EndDate" as end_date,
    "SK_AdmissionMethodID" as sk_admission_method_id,
    "SK_AdmissionSourceID" as sk_admission_source_id,
    "PASHospitalNumber" as pas_hospital_number,
    "HospitalProviderSpellNumber" as hospital_provider_spell_number,
    "SpellEpisodeID4" as spell_episode_id4,
    "ExcessBedDays" as excess_bed_days,
    "CoreSpellHRG" as core_spell_hrg,
    "ExtractType" as extract_type,
    "PrimaryProcedure" as primary_procedure,
    "PrimaryDiagnosis" as primary_diagnosis,
    "SK_SpecialtyID" as sk_specialty_id,
    "SK_ConsultantID" as sk_consultant_id,
    "UniqueCDSIdentifier" as unique_cds_identifier,
    "FCEHRG" as fcehrg,
    "DateOfPrimaryProcedure" as date_of_primary_procedure,
    "HRG35Code" as hrg35_code,
    "HRG4Code" as hrg4_code,
    "SK_TreatmentFunctionCode" as sk_treatment_function_code,
    "EncounterSequenceNumber" as encounter_sequence_number,
    "SK_ServiceProviderID" as sk_service_provider_id,
    "SK_PatientID" as sk_patient_id,
    "SK_StaffID" as sk_staff_id,
    "EncounterStartDateTime" as encounter_start_date_time,
    "EncounterEndDateTime" as encounter_end_date_time,
    "SK_AdminCategoryID" as sk_admin_category_id,
    "AdmissionDate" as admission_date,
    "DischargeDate" as discharge_date,
    "SK_DischargeMethodID" as sk_discharge_method_id,
    "SK_DischargeDestinationID" as sk_discharge_destination_id,
    "SK_PatientClassificationID" as sk_patient_classification_id,
    "DeleteEncounter" as delete_encounter,
    "SK_AgeBandID" as sk_age_band_id,
    "PbROrSEM_NotUsed" as pb_ror_sem_not_used,
    "Referrer_Code" as referrer_code,
    "Referring_Org_Code" as referring_org_code,
    "Date_of_Decision_to_Admit" as date_of_decision_to_admit,
    "Is_SpCommissioner" as is_sp_commissioner,
    "SK_CommissionerID" as sk_commissioner_id,
    "SK_Commissioner_PCTID" as sk_commissioner_pctid,
    "PROVIDER_REFERENCE_NO" as provider_reference_no,
    "AGREEMENT_LINE_NO" as agreement_line_no,
    "SC_Service_Line_Code_National" as sc_service_line_code_national,
    "SC_Service_Line_Code_National_Spell" as sc_service_line_code_national_spell,
    "SC_Service_Line_Code_Local" as sc_service_line_code_local,
    "SC_Service_Line_Code_Local_Spell" as sc_service_line_code_local_spell,
    "COMMISSIONER_SERIAL_NO" as commissioner_serial_no,
    "Age_Group_Intended_at_Epiend" as age_group_intended_at_epiend,
    "Ready_For_Discharge_Date" as ready_for_discharge_date,
    "Local_Site_Code" as local_site_code,
    "Spell_Discharge_Time" as spell_discharge_time,
    "Spell_Start_Time" as spell_start_time,
    "Local_Sub_Specialty_Code" as local_sub_specialty_code,
    "Neonatal_Level_Of_Care" as neonatal_level_of_care,
    "SK_Org_CommissionerID" as sk_org_commissioner_id,
    "SK_Org_ServiceProviderID" as sk_org_service_provider_id,
    "SK_RTTPeriodStatusID" as sk_rtt_period_status_id,
    "SK_LegalStatusID" as sk_legal_status_id,
    "SK_IntendedManagementID" as sk_intended_management_id,
    "RTT_Period_Start_Date" as rtt_period_start_date,
    "RTT_Period_End_Date" as rtt_period_end_date,
    "Programme_Budget_Code" as programme_budget_code,
    "Patient_Pathway_ID" as patient_pathway_id,
    "PbROrSEM" as pb_ror_sem,
    "Commissioner_Reference_Number" as commissioner_reference_number,
    "SK_OperationStatusID" as sk_operation_status_id,
    "WardCode_At_Episode_Start" as ward_code_at_episode_start,
    "WardCode_At_Episode_End" as ward_code_at_episode_end,
    "Spell_Identifier" as spell_identifier
from {{ source('sus_apc_monthly', 'EncounterDetail') }}
