-- Raw layer model for olids.MEDICATION_STATEMENT
-- Source: "DATA_LAKE"."OLIDS"
-- Description: OLIDS stable layer - cleaned and filtered patient records
-- This is a 1:1 passthrough from source with standardized column names
select
    "LDS_RECORD_ID" as lds_record_id,
    "ID" as id,
    "ORGANISATION_ID" as organisation_id,
    "PERSON_ID" as person_id,
    "PATIENT_ID" as patient_id,
    "ENCOUNTER_ID" as encounter_id,
    "PRACTITIONER_ID" as practitioner_id,
    "OBSERVATION_ID" as observation_id,
    "ALLERGY_INTOLERANCE_ID" as allergy_intolerance_id,
    "DIAGNOSTIC_ORDER_ID" as diagnostic_order_id,
    "REFERRAL_REQUEST_ID" as referral_request_id,
    "AUTHORISATION_TYPE_CONCEPT_ID" as authorisation_type_concept_id,
    "DATE_PRECISION_CONCEPT_ID" as date_precision_concept_id,
    "MEDICATION_STATEMENT_SOURCE_CONCEPT_ID" as medication_statement_source_concept_id,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "CANCELLATION_DATE" as cancellation_date,
    "DOSE" as dose,
    "QUANTITY_VALUE_DESCRIPTION" as quantity_value_description,
    "QUANTITY_VALUE" as quantity_value,
    "QUANTITY_UNIT" as quantity_unit,
    "MEDICATION_NAME" as medication_name,
    "BNF_REFERENCE" as bnf_reference,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "ISSUE_METHOD" as issue_method,
    "DATE_RECORDED" as date_recorded,
    "IS_ACTIVE" as is_active,
    "IS_CONFIDENTIAL" as is_confidential,
    "IS_DELETED" as is_deleted,
    "EXPIRY_DATE" as expiry_date,
    "LDS_ID" as lds_id,
    "LDS_BUSINESS_KEY" as lds_business_key,
    "LDS_DATASET_ID" as lds_dataset_id,
    "LDS_CDM_EVENT_ID" as lds_cdm_event_id,
    "LDS_VERSIONER_EVENT_ID" as lds_versioner_event_id,
    "RECORD_OWNER_ORGANISATION_CODE" as record_owner_organisation_code,
    "LDS_DATETIME_DATA_ACQUIRED" as lds_datetime_data_acquired,
    "LDS_INITIAL_DATA_RECEIVED_DATE" as lds_initial_data_received_date,
    "LDS_IS_DELETED" as lds_is_deleted,
    "LDS_START_DATE_TIME" as lds_start_date_time,
    "LDS_LAKEHOUSE_DATE_PROCESSED" as lds_lakehouse_date_processed,
    "LDS_LAKEHOUSE_DATETIME_UPDATED" as lds_lakehouse_datetime_updated
from {{ source('olids', 'MEDICATION_STATEMENT') }}
