{{
    config(
        materialized='view'
    )
}}

select
    visit_occurrence_id
    , sk_patient_id
    , source
    , local_patient_identifier
    , cds_unique_identifier
    , provider_reference_number
    , organisation_id
    , organisation_name
    , site_id
    , site_name
    , pod
    , department_type
    , urgent_care_setting_type
    , start_date
    , start_time
    , financial_year
    , financial_month
    , end_date
    , end_time
    , duration
    , initial_assessment_date
    , initial_assessment_time
    , initial_assessment_time_since_arrival
    , seen_for_treatment_date
    , seen_for_treatment_time
    , seen_for_treatment_time_since_arrival
    , conclusion_date
    , conclusion_time
    , conclusion_time_since_arrival
    , decided_to_admit_date
    , decided_to_admit_time
    , decided_to_admit_time_since_arrival
    , clinically_ready_to_proceed_at
    , clinically_ready_to_proceed_time_since_arrival
    , expected_treatment_time
    , chief_complaint_code
    , chief_complaint_desc
    , chief_complaint_ecds_group1
    , is_injury_related
    , acuity
    , injury_intent_code
    , injury_intent_desc
    , injury_mechanism_code
    , injury_mechanism_desc
    , place_of_injury_code
    , place_of_injury_desc
    , injury_date
    , injury_time
    , disease_notification_code
    , injury_alcohol_drug_involvement_code
    , primary_diagnosis_code_snomed
    , primary_diagnosis_desc_snomed
    , primary_diagnosis_code_icd10
    , primary_diagnosis_desc_icd10
    , primary_diagnosis_desc_ecds_group1
    , secondary_diagnosis_1_code_snomed
    , secondary_diagnosis_2_code_snomed
    , secondary_diagnosis_3_code_snomed
    , secondary_diagnosis_4_code_snomed
    , secondary_diagnosis_5_code_snomed
    , secondary_diagnosis_6_code_snomed
    , secondary_diagnosis_7_code_snomed
    , secondary_diagnosis_8_code_snomed
    , secondary_diagnosis_9_code_snomed
    , secondary_diagnosis_10_code_snomed
    , secondary_diagnosis_11_code_snomed
    , secondary_diagnosis_12_code_snomed
    , primary_treatment
    , primary_treatment_desc_snomed
    , primary_treatment_desc_ecds_group1
    , treatment_1_code_snomed
    , treatment_2_code_snomed
    , treatment_3_code_snomed
    , treatment_4_code_snomed
    , treatment_5_code_snomed
    , treatment_6_code_snomed
    , treatment_7_code_snomed
    , treatment_8_code_snomed
    , treatment_9_code_snomed
    , treatment_10_code_snomed
    , treatment_11_code_snomed
    , treatment_12_code_snomed
    , primary_investigation
    , primary_investigation_desc_snomed
    , primary_investigation_desc_ecds_group1
    , clinical_investigation_1_code_snomed
    , clinical_investigation_2_code_snomed
    , clinical_investigation_3_code_snomed
    , clinical_investigation_4_code_snomed
    , clinical_investigation_5_code_snomed
    , clinical_investigation_6_code_snomed
    , clinical_investigation_7_code_snomed
    , clinical_investigation_8_code_snomed
    , clinical_investigation_9_code_snomed
    , clinical_investigation_10_code_snomed
    , clinical_investigation_11_code_snomed
    , clinical_investigation_12_code_snomed
    , comorbidity_1_code_snomed
    , comorbidity_2_code_snomed
    , comorbidity_3_code_snomed
    , comorbidity_4_code_snomed
    , comorbidity_5_code_snomed
    , comorbidity_6_code_snomed
    , comorbidity_7_code_snomed
    , comorbidity_8_code_snomed
    , comorbidity_9_code_snomed
    , comorbidity_10_code_snomed
    , arrival_mode_code
    , arrival_mode_desc
    , attendance_category_code
    , attendance_category_desc
    , is_arrival_planned
    , ambulance_incident_number
    , conveying_ambulance_trust_code
    , conveying_ambulance_trust_name
    , ambulance_care_contact_identifier
    , attendance_source_code
    , attendance_source_desc
    , attendance_source_organisation_site_identifier
    , attendance_source_organisation_site_name
    , discharge_destination_code
    , discharge_destination_desc
    , discharge_status_code
    , discharge_status_desc
    , discharge_follow_up_code
    , discharge_follow_up_desc
    , discharge_information_given_code
    , decided_to_admit_treatment_function_code
    , decided_to_admit_treatment_function_desc
    , receiving_site_id
    , receiving_site_name
    , main_specialty_code
    , main_specialty_name
    , hrg_code
    , core_hrg_desc
    , core_hrg_chapter
    , core_hrg_chapter_desc
    , cost
    , applicable_costing_period
    , is_national_tariff_excluded
    , national_tariff
    , national_tariff_final_price
    , mff_factor
    , mff_adjustment
    , residence_commissioner_code_at_event
    , residence_commissioner_name_at_event
    , registrant_commissioner_code_at_event
    , registrant_commissioner_name_at_event
    , age_at_event
    , patient_type_code
    , patient_type_desc
    , gender_at_event
    , gender_desc_at_event
    , ethnicity_at_event
    , ethnicity_desc_at_event
    , postcode_district_at_event
    , lsoa_11_at_event
    , lad_at_event
    , imd_at_event
    , reg_practice_at_event
    , general_practitioner_code
    , visit_occurrence_type
    , patient_pathway_identifier
    , referral_to_treatment_status_code
    , referral_to_treatment_period_start_date
    , referral_to_treatment_period_end_date
    , waiting_time_measurement_type_code
    , referred_to_service_code
    , referred_to_service_assessment_date
    , referred_to_service_assessment_time
    , mental_health_legal_status_code
from {{ ref('int_sus_uec_encounter') }}
