-- Raw layer model for pds.PDS_Address_CareHomeSimilarity
-- Source: "DATA_LAKE"."PDS"
-- Description: Personal Demographics Service data
-- This is a 1:1 passthrough from source with standardized column names
select
    "RowID" as row_id,
    "Pseudo NHS Number" as pseudo_nhs_number,
    "derPostcodeSector" as der_postcode_sector,
    "Usual Address Business Effective From Date" as usual_address_business_effective_from_date,
    "Usual Address Business Effective To Date" as usual_address_business_effective_to_date,
    "derCqcCareHomeCode" as der_cqc_care_home_code,
    "derCcgOfResidence" as der_ccg_of_residence,
    "derLocalAuthorityOfResidence" as der_local_authority_of_residence,
    "derCurrentCcgOfResidence" as der_current_ccg_of_residence,
    "derCurrentLaOfResidence" as der_current_la_of_residence,
    "derCurrentyr2011LSOAofResidence_FromPostcode" as der_currentyr2011_lsoa_of_residence_from_postcode,
    "derCurrentyr2021LSOAofResidence_FromPostcode" as der_currentyr2021_lsoa_of_residence_from_postcode,
    "dmicPostcodeTypeId" as dmic_postcode_type_id,
    "dmicPostcodeWellbeingTypeId" as dmic_postcode_wellbeing_type_id,
    "derIcbOfResidence" as der_icb_of_residence,
    "derCurrentIcbOfResidence" as der_current_icb_of_residence,
    "derCurrentyr2021ElectoralWardOfResidence_FromPostcode" as der_currentyr2021_electoral_ward_of_residence_from_postcode,
    "PDSAddr1Addr2_ContainsString" as pds_addr1_addr2_contains_string,
    "Jaccard_CQCOrgName_PDSAddr1_CQCCareHomeCode" as jaccard_cqc_org_name_pds_addr1_cqc_care_home_code,
    "Jaccard_CQCOrgName_PDSAddr1_Similarity" as jaccard_cqc_org_name_pds_addr1_similarity,
    "Jaccard_CQCOrgName_PDSAddr2_CQCCareHomeCode" as jaccard_cqc_org_name_pds_addr2_cqc_care_home_code,
    "Jaccard_CQCOrgName_PDSAddr2_Similarity" as jaccard_cqc_org_name_pds_addr2_similarity,
    "Jaccard_CQCAddr1_PDSAddr1_CQCCareHomeCode" as jaccard_cqc_addr1_pds_addr1_cqc_care_home_code,
    "Jaccard_CQCAddr1_PDSAddr1_Similarity" as jaccard_cqc_addr1_pds_addr1_similarity,
    "Jaccard_CQCAddr1_PDSAddr2_CQCCareHomeCode" as jaccard_cqc_addr1_pds_addr2_cqc_care_home_code,
    "Jaccard_CQCAddr1_PDSAddr2_Similarity" as jaccard_cqc_addr1_pds_addr2_similarity,
    "Jaccard_CQCAddr2_PDSAddr1_CQCCareHomeCode" as jaccard_cqc_addr2_pds_addr1_cqc_care_home_code,
    "Jaccard_CQCAddr2_PDSAddr1_Similarity" as jaccard_cqc_addr2_pds_addr1_similarity,
    "Jaccard_CQCAddr2_PDSAddr2_CQCCareHomeCode" as jaccard_cqc_addr2_pds_addr2_cqc_care_home_code,
    "Jaccard_CQCAddr2_PDSAddr2_Similarity" as jaccard_cqc_addr2_pds_addr2_similarity,
    "JaroWinkler_CQCOrgName_PDSAddr1_CQCCareHomeCode" as jaro_winkler_cqc_org_name_pds_addr1_cqc_care_home_code,
    "JaroWinkler_CQCOrgName_PDSAddr1_Similarity" as jaro_winkler_cqc_org_name_pds_addr1_similarity,
    "JaroWinkler_CQCOrgName_PDSAddr2_CQCCareHomeCode" as jaro_winkler_cqc_org_name_pds_addr2_cqc_care_home_code,
    "JaroWinkler_CQCOrgName_PDSAddr2_Similarity" as jaro_winkler_cqc_org_name_pds_addr2_similarity,
    "JaroWinkler_CQCAddr1_PDSAddr1_CQCCareHomeCode" as jaro_winkler_cqc_addr1_pds_addr1_cqc_care_home_code,
    "JaroWinkler_CQCAddr1_PDSAddr1_Similarity" as jaro_winkler_cqc_addr1_pds_addr1_similarity,
    "JaroWinkler_CQCAddr1_PDSAddr2_CQCCareHomeCode" as jaro_winkler_cqc_addr1_pds_addr2_cqc_care_home_code,
    "JaroWinkler_CQCAddr1_PDSAddr2_Similarity" as jaro_winkler_cqc_addr1_pds_addr2_similarity,
    "JaroWinkler_CQCAddr2_PDSAddr1_CQCCareHomeCode" as jaro_winkler_cqc_addr2_pds_addr1_cqc_care_home_code,
    "JaroWinkler_CQCAddr2_PDSAddr1_Similarity" as jaro_winkler_cqc_addr2_pds_addr1_similarity,
    "JaroWinkler_CQCAddr2_PDSAddr2_CQCCareHomeCode" as jaro_winkler_cqc_addr2_pds_addr2_cqc_care_home_code,
    "JaroWinkler_CQCAddr2_PDSAddr2_Similarity" as jaro_winkler_cqc_addr2_pds_addr2_similarity,
    "Jaccard_CQCuprn_PDSuprn_CQCCareHomeCode" as jaccard_cq_cuprn_pd_suprn_cqc_care_home_code,
    "Jaccard_CQCuprn_PDSuprn_Similarity" as jaccard_cq_cuprn_pd_suprn_similarity,
    "JaroWinkler_CQCuprn_PDSuprn_CQCCareHomeCode" as jaro_winkler_cq_cuprn_pd_suprn_cqc_care_home_code,
    "JaroWinkler_CQCuprn_PDSuprn_Similarity" as jaro_winkler_cq_cuprn_pd_suprn_similarity
from {{ source('pds', 'PDS_Address_CareHomeSimilarity') }}
