-- Raw layer model for olids.OBSERVATION
-- Source: "DATA_LAKE"."OLIDS"
-- Description: OLIDS stable layer - cleaned and filtered patient records
-- This is a 1:1 passthrough from source with standardized column names
select
    "LDS_RECORD_ID" as lds_record_id,
    "ID" as id,
    "PATIENT_ID" as patient_id,
    "PERSON_ID" as person_id,
    "ENCOUNTER_ID" as encounter_id,
    "PRACTITIONER_ID" as practitioner_id,
    "PARENT_OBSERVATION_ID" as parent_observation_id,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "DATE_PRECISION_CONCEPT_ID" as date_precision_concept_id,
    "RESULT_VALUE" as result_value,
    "RESULT_VALUE_UNITS_CONCEPT_ID" as result_value_units_concept_id,
    "RESULT_DATE" as result_date,
    "RESULT_TEXT" as result_text,
    "IS_PROBLEM" as is_problem,
    "IS_REVIEW" as is_review,
    "PROBLEM_END_DATE" as problem_end_date,
    "OBSERVATION_SOURCE_CONCEPT_ID" as observation_source_concept_id,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "EPISODICITY_CONCEPT_ID" as episodicity_concept_id,
    "IS_PRIMARY" as is_primary,
    "DATE_RECORDED" as date_recorded,
    "IS_PROBLEM_DELETED" as is_problem_deleted,
    "IS_CONFIDENTIAL" as is_confidential,
    "LDS_ID" as lds_id,
    "LDS_BUSINESS_KEY" as lds_business_key,
    "LDS_DATASET_ID" as lds_dataset_id,
    "LDS_CDM_EVENT_ID" as lds_cdm_event_id,
    "LDS_VERSIONER_EVENT_ID" as lds_versioner_event_id,
    "RECORD_OWNER_ORGANISATION_CODE" as record_owner_organisation_code,
    "LDS_DATETIME_DATA_ACQUIRED" as lds_datetime_data_acquired,
    "LDS_INITIAL_DATA_RECEIVED_DATE" as lds_initial_data_received_date,
    "LDS_START_DATE_TIME" as lds_start_date_time,
    "LDS_LAKEHOUSE_DATE_PROCESSED" as lds_lakehouse_date_processed,
    "LDS_LAKEHOUSE_DATETIME_UPDATED" as lds_lakehouse_datetime_updated,
    "MAPPED_CONCEPT_ID" as mapped_concept_id,
    "MAPPED_CONCEPT_CODE" as mapped_concept_code,
    "MAPPED_CONCEPT_DISPLAY" as mapped_concept_display,
    "RESULT_UNIT_CODE" as result_unit_code,
    "RESULT_UNIT_DISPLAY" as result_unit_display
from {{ source('olids', 'OBSERVATION') }}
