-- Raw layer model for olids.APPOINTMENT
-- Source: "DATA_LAKE"."OLIDS"
-- Description: OLIDS stable layer - cleaned and filtered patient records
-- This is a 1:1 passthrough from source with standardized column names
select
    "LDS_RECORD_ID" as lds_record_id,
    "ID" as id,
    "ORGANISATION_ID" as organisation_id,
    "PATIENT_ID" as patient_id,
    "PERSON_ID" as person_id,
    "PRACTITIONER_IN_ROLE_ID" as practitioner_in_role_id,
    "SCHEDULE_ID" as schedule_id,
    "START_DATE" as start_date,
    "PLANNED_DURATION" as planned_duration,
    "ACTUAL_DURATION" as actual_duration,
    "APPOINTMENT_STATUS_CONCEPT_ID" as appointment_status_concept_id,
    "PATIENT_WAIT" as patient_wait,
    "PATIENT_DELAY" as patient_delay,
    "DATE_TIME_BOOKED" as date_time_booked,
    "DATE_TIME_SENT_IN" as date_time_sent_in,
    "DATE_TIME_LEFT" as date_time_left,
    "CANCELLED_DATE" as cancelled_date,
    "TYPE" as type,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "BOOKING_METHOD_CONCEPT_ID" as booking_method_concept_id,
    "CONTACT_MODE_CONCEPT_ID" as contact_mode_concept_id,
    "IS_BLOCKED" as is_blocked,
    "NATIONAL_SLOT_CATEGORY_NAME" as national_slot_category_name,
    "CONTEXT_TYPE" as context_type,
    "SERVICE_SETTING" as service_setting,
    "NATIONAL_SLOT_CATEGORY_DESCRIPTION" as national_slot_category_description,
    "CSDS_CARE_CONTACT_IDENTIFIER" as csds_care_contact_identifier,
    "LDS_ID" as lds_id,
    "LDS_BUSINESS_KEY" as lds_business_key,
    "LDS_DATASET_ID" as lds_dataset_id,
    "LDS_CDM_EVENT_ID" as lds_cdm_event_id,
    "LDS_VERSIONER_EVENT_ID" as lds_versioner_event_id,
    "RECORD_OWNER_ORGANISATION_CODE" as record_owner_organisation_code,
    "LDS_DATETIME_DATA_ACQUIRED" as lds_datetime_data_acquired,
    "LDS_INITIAL_DATA_RECEIVED_DATE" as lds_initial_data_received_date,
    "LDS_IS_DELETED" as lds_is_deleted,
    "LDS_START_DATE_TIME" as lds_start_date_time,
    "LDS_LAKEHOUSE_DATE_PROCESSED" as lds_lakehouse_date_processed,
    "LDS_LAKEHOUSE_DATETIME_UPDATED" as lds_lakehouse_datetime_updated
from {{ source('olids', 'APPOINTMENT') }}
