{{
    config(
        description="Raw layer (OLIDS stable layer - cleaned and filtered patient records). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.OLIDS.MEDICATION_STATEMENT \ndbt: source(''olids'', ''MEDICATION_STATEMENT'') \nColumns:\n  LDS_SOURCE_RECORD_ID -> lds_source_record_id\n  ID -> id\n  PROVIDER_ORGANISATION_ID -> provider_organisation_id\n  PERSON_ID -> person_id\n  PATIENT_ID -> patient_id\n  ENCOUNTER_ID -> encounter_id\n  PRACTITIONER_ID -> practitioner_id\n  OBSERVATION_ID -> observation_id\n  ALLERGY_INTOLERANCE_ID -> allergy_intolerance_id\n  DIAGNOSTIC_ORDER_ID -> diagnostic_order_id\n  REFERRAL_REQUEST_ID -> referral_request_id\n  AUTHORISATION_TYPE_SOURCE_CONCEPT_ID -> authorisation_type_source_concept_id\n  AUTHORISATION_TYPE_SOURCE_CODE -> authorisation_type_source_code\n  AUTHORISATION_TYPE_SOURCE_DISPLAY -> authorisation_type_source_display\n  AUTHORISATION_TYPE_CODE -> authorisation_type_code\n  AUTHORISATION_TYPE_DISPLAY -> authorisation_type_display\n  CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID -> clinical_effective_date_precision_source_concept_id\n  DATE_PRECISION_SOURCE_CODE -> date_precision_source_code\n  DATE_PRECISION_SOURCE_DISPLAY -> date_precision_source_display\n  DATE_PRECISION_CODE -> date_precision_code\n  DATE_PRECISION_DISPLAY -> date_precision_display\n  MEDICATION_STATEMENT_SOURCE_CONCEPT_ID -> medication_statement_source_concept_id\n  MAPPED_CONCEPT_ID -> mapped_concept_id\n  MAPPED_CONCEPT_CODE -> mapped_concept_code\n  MAPPED_CONCEPT_DISPLAY -> mapped_concept_display\n  SOURCE_CODE -> source_code\n  SOURCE_DISPLAY -> source_display\n  SOURCE_SYSTEM -> source_system\n  TARGET_SYSTEM -> target_system\n  BNF_CHAPTER -> bnf_chapter\n  BNF_SECTION -> bnf_section\n  BNF_CODE -> bnf_code\n  BNF_NAME -> bnf_name\n  CLINICAL_EFFECTIVE_DATE -> clinical_effective_date\n  CANCELLATION_DATE -> cancellation_date\n  DOSE -> dose\n  QUANTITY_VALUE_DESCRIPTION -> quantity_value_description\n  QUANTITY_VALUE -> quantity_value\n  QUANTITY_UNIT -> quantity_unit\n  MEDICATION_NAME -> medication_name\n  BNF_REFERENCE -> bnf_reference\n  AGE_AT_EVENT -> age_at_event\n  AGE_AT_EVENT_BABY -> age_at_event_baby\n  AGE_AT_EVENT_NEONATE -> age_at_event_neonate\n  ISSUE_METHOD -> issue_method\n  DATE_RECORDED -> date_recorded\n  IS_ACTIVE -> is_active\n  IS_CONFIDENTIAL -> is_confidential\n  EXPIRY_DATE -> expiry_date\n  PUBLISHER_ORGANISATION_ID -> publisher_organisation_id\n  AUTHOR_ORGANISATION_ID -> author_organisation_id\n  PUBLISHER_ORGANISATION_CODE -> publisher_organisation_code\n  PATIENT_SHARD_ID -> patient_shard_id\n  PERSON_SHARD_ID -> person_shard_id\n  LDS_SOURCE_RECORD_SHARD_ID -> lds_source_record_shard_id\n  LDS_ID -> lds_id\n  LDS_BUSINESS_KEY -> lds_business_key\n  LDS_SOURCE_DATASET_ID -> lds_source_dataset_id\n  LDS_CDM_EVENT_ID -> lds_cdm_event_id\n  LDS_VERSIONER_EVENT_ID -> lds_versioner_event_id\n  LDS_DATETIME_FIRST_ACQUIRED -> lds_datetime_first_acquired\n  LDS_DATETIME_UPDATE_ACQUIRED -> lds_datetime_update_acquired\n  LDS_IS_DELETED -> lds_is_deleted\n  LDS_START_DATETIME -> lds_start_datetime\n  LDS_LAKEHOUSE_DATE_PROCESSED -> lds_lakehouse_date_processed\n  LDS_LAKEHOUSE_DATETIME_UPDATED -> lds_lakehouse_datetime_updated"
    )
}}
select
    "LDS_SOURCE_RECORD_ID" as lds_source_record_id,
    "ID" as id,
    "PROVIDER_ORGANISATION_ID" as provider_organisation_id,
    "PERSON_ID" as person_id,
    "PATIENT_ID" as patient_id,
    "ENCOUNTER_ID" as encounter_id,
    "PRACTITIONER_ID" as practitioner_id,
    "OBSERVATION_ID" as observation_id,
    "ALLERGY_INTOLERANCE_ID" as allergy_intolerance_id,
    "DIAGNOSTIC_ORDER_ID" as diagnostic_order_id,
    "REFERRAL_REQUEST_ID" as referral_request_id,
    "AUTHORISATION_TYPE_SOURCE_CONCEPT_ID" as authorisation_type_source_concept_id,
    "AUTHORISATION_TYPE_SOURCE_CODE" as authorisation_type_source_code,
    "AUTHORISATION_TYPE_SOURCE_DISPLAY" as authorisation_type_source_display,
    "AUTHORISATION_TYPE_CODE" as authorisation_type_code,
    "AUTHORISATION_TYPE_DISPLAY" as authorisation_type_display,
    "CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID" as clinical_effective_date_precision_source_concept_id,
    "DATE_PRECISION_SOURCE_CODE" as date_precision_source_code,
    "DATE_PRECISION_SOURCE_DISPLAY" as date_precision_source_display,
    "DATE_PRECISION_CODE" as date_precision_code,
    "DATE_PRECISION_DISPLAY" as date_precision_display,
    "MEDICATION_STATEMENT_SOURCE_CONCEPT_ID" as medication_statement_source_concept_id,
    "MAPPED_CONCEPT_ID" as mapped_concept_id,
    "MAPPED_CONCEPT_CODE" as mapped_concept_code,
    "MAPPED_CONCEPT_DISPLAY" as mapped_concept_display,
    "SOURCE_CODE" as source_code,
    "SOURCE_DISPLAY" as source_display,
    "SOURCE_SYSTEM" as source_system,
    "TARGET_SYSTEM" as target_system,
    "BNF_CHAPTER" as bnf_chapter,
    "BNF_SECTION" as bnf_section,
    "BNF_CODE" as bnf_code,
    "BNF_NAME" as bnf_name,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "CANCELLATION_DATE" as cancellation_date,
    "DOSE" as dose,
    "QUANTITY_VALUE_DESCRIPTION" as quantity_value_description,
    "QUANTITY_VALUE" as quantity_value,
    "QUANTITY_UNIT" as quantity_unit,
    "MEDICATION_NAME" as medication_name,
    "BNF_REFERENCE" as bnf_reference,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "ISSUE_METHOD" as issue_method,
    "DATE_RECORDED" as date_recorded,
    "IS_ACTIVE" as is_active,
    "IS_CONFIDENTIAL" as is_confidential,
    "EXPIRY_DATE" as expiry_date,
    "PUBLISHER_ORGANISATION_ID" as publisher_organisation_id,
    "AUTHOR_ORGANISATION_ID" as author_organisation_id,
    "PUBLISHER_ORGANISATION_CODE" as publisher_organisation_code,
    "PATIENT_SHARD_ID" as patient_shard_id,
    "PERSON_SHARD_ID" as person_shard_id,
    "LDS_SOURCE_RECORD_SHARD_ID" as lds_source_record_shard_id,
    "LDS_ID" as lds_id,
    "LDS_BUSINESS_KEY" as lds_business_key,
    "LDS_SOURCE_DATASET_ID" as lds_source_dataset_id,
    "LDS_CDM_EVENT_ID" as lds_cdm_event_id,
    "LDS_VERSIONER_EVENT_ID" as lds_versioner_event_id,
    "LDS_DATETIME_FIRST_ACQUIRED" as lds_datetime_first_acquired,
    "LDS_DATETIME_UPDATE_ACQUIRED" as lds_datetime_update_acquired,
    "LDS_IS_DELETED" as lds_is_deleted,
    "LDS_START_DATETIME" as lds_start_datetime,
    "LDS_LAKEHOUSE_DATE_PROCESSED" as lds_lakehouse_date_processed,
    "LDS_LAKEHOUSE_DATETIME_UPDATED" as lds_lakehouse_datetime_updated
from {{ source('olids', 'MEDICATION_STATEMENT') }}
