{{
    config(
        description="Raw layer (OLIDS stable layer - cleaned and filtered patient records). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.OLIDS.MEDICATION_ORDER \ndbt: source(''olids'', ''MEDICATION_ORDER'') \nColumns:\n  LDS_RECORD_ID -> lds_record_id\n  ID -> id\n  ORGANISATION_ID -> organisation_id\n  PERSON_ID -> person_id\n  PATIENT_ID -> patient_id\n  MEDICATION_STATEMENT_ID -> medication_statement_id\n  ENCOUNTER_ID -> encounter_id\n  PRACTITIONER_ID -> practitioner_id\n  OBSERVATION_ID -> observation_id\n  ALLERGY_INTOLERANCE_ID -> allergy_intolerance_id\n  DIAGNOSTIC_ORDER_ID -> diagnostic_order_id\n  REFERRAL_REQUEST_ID -> referral_request_id\n  CLINICAL_EFFECTIVE_DATE -> clinical_effective_date\n  DATE_PRECISION_CONCEPT_ID -> date_precision_concept_id\n  DATE_PRECISION_SOURCE_CODE -> date_precision_source_code\n  DATE_PRECISION_SOURCE_DISPLAY -> date_precision_source_display\n  DATE_PRECISION_CODE -> date_precision_code\n  DATE_PRECISION_DISPLAY -> date_precision_display\n  DOSE -> dose\n  QUANTITY_VALUE -> quantity_value\n  QUANTITY_UNIT -> quantity_unit\n  DURATION_DAYS -> duration_days\n  ESTIMATED_COST -> estimated_cost\n  MEDICATION_NAME -> medication_name\n  MEDICATION_ORDER_SOURCE_CONCEPT_ID -> medication_order_source_concept_id\n  BNF_REFERENCE -> bnf_reference\n  AGE_AT_EVENT -> age_at_event\n  AGE_AT_EVENT_BABY -> age_at_event_baby\n  AGE_AT_EVENT_NEONATE -> age_at_event_neonate\n  ISSUE_METHOD -> issue_method\n  DATE_RECORDED -> date_recorded\n  IS_CONFIDENTIAL -> is_confidential\n  ISSUE_METHOD_DESCRIPTION -> issue_method_description\n  LDS_ID -> lds_id\n  LDS_BUSINESS_KEY -> lds_business_key\n  LDS_DATASET_ID -> lds_dataset_id\n  LDS_CDM_EVENT_ID -> lds_cdm_event_id\n  LDS_VERSIONER_EVENT_ID -> lds_versioner_event_id\n  RECORD_OWNER_ORGANISATION_CODE -> record_owner_organisation_code\n  LDS_DATETIME_DATA_ACQUIRED -> lds_datetime_data_acquired\n  LDS_INITIAL_DATA_RECEIVED_DATE -> lds_initial_data_received_date\n  LDS_IS_DELETED -> lds_is_deleted\n  LDS_START_DATE_TIME -> lds_start_date_time\n  LDS_LAKEHOUSE_DATE_PROCESSED -> lds_lakehouse_date_processed\n  LDS_LAKEHOUSE_DATETIME_UPDATED -> lds_lakehouse_datetime_updated\n  MEDICATION_STATEMENT_SOURCE_CONCEPT_ID -> medication_statement_source_concept_id\n  STATEMENT_MEDICATION_NAME -> statement_medication_name\n  MAPPED_CONCEPT_ID -> mapped_concept_id\n  MAPPED_CONCEPT_CODE -> mapped_concept_code\n  MAPPED_CONCEPT_DISPLAY -> mapped_concept_display\n  SOURCE_CODE -> source_code\n  SOURCE_DISPLAY -> source_display\n  SOURCE_SYSTEM -> source_system\n  TARGET_SYSTEM -> target_system"
    )
}}
select
    "LDS_RECORD_ID" as lds_record_id,
    "ID" as id,
    "ORGANISATION_ID" as organisation_id,
    "PERSON_ID" as person_id,
    "PATIENT_ID" as patient_id,
    "MEDICATION_STATEMENT_ID" as medication_statement_id,
    "ENCOUNTER_ID" as encounter_id,
    "PRACTITIONER_ID" as practitioner_id,
    "OBSERVATION_ID" as observation_id,
    "ALLERGY_INTOLERANCE_ID" as allergy_intolerance_id,
    "DIAGNOSTIC_ORDER_ID" as diagnostic_order_id,
    "REFERRAL_REQUEST_ID" as referral_request_id,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "DATE_PRECISION_CONCEPT_ID" as date_precision_concept_id,
    "DATE_PRECISION_SOURCE_CODE" as date_precision_source_code,
    "DATE_PRECISION_SOURCE_DISPLAY" as date_precision_source_display,
    "DATE_PRECISION_CODE" as date_precision_code,
    "DATE_PRECISION_DISPLAY" as date_precision_display,
    "DOSE" as dose,
    "QUANTITY_VALUE" as quantity_value,
    "QUANTITY_UNIT" as quantity_unit,
    "DURATION_DAYS" as duration_days,
    "ESTIMATED_COST" as estimated_cost,
    "MEDICATION_NAME" as medication_name,
    "MEDICATION_ORDER_SOURCE_CONCEPT_ID" as medication_order_source_concept_id,
    "BNF_REFERENCE" as bnf_reference,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "ISSUE_METHOD" as issue_method,
    "DATE_RECORDED" as date_recorded,
    "IS_CONFIDENTIAL" as is_confidential,
    "ISSUE_METHOD_DESCRIPTION" as issue_method_description,
    "LDS_ID" as lds_id,
    "LDS_BUSINESS_KEY" as lds_business_key,
    "LDS_DATASET_ID" as lds_dataset_id,
    "LDS_CDM_EVENT_ID" as lds_cdm_event_id,
    "LDS_VERSIONER_EVENT_ID" as lds_versioner_event_id,
    "RECORD_OWNER_ORGANISATION_CODE" as record_owner_organisation_code,
    "LDS_DATETIME_DATA_ACQUIRED" as lds_datetime_data_acquired,
    "LDS_INITIAL_DATA_RECEIVED_DATE" as lds_initial_data_received_date,
    "LDS_IS_DELETED" as lds_is_deleted,
    "LDS_START_DATE_TIME" as lds_start_date_time,
    "LDS_LAKEHOUSE_DATE_PROCESSED" as lds_lakehouse_date_processed,
    "LDS_LAKEHOUSE_DATETIME_UPDATED" as lds_lakehouse_datetime_updated,
    "MEDICATION_STATEMENT_SOURCE_CONCEPT_ID" as medication_statement_source_concept_id,
    "STATEMENT_MEDICATION_NAME" as statement_medication_name,
    "MAPPED_CONCEPT_ID" as mapped_concept_id,
    "MAPPED_CONCEPT_CODE" as mapped_concept_code,
    "MAPPED_CONCEPT_DISPLAY" as mapped_concept_display,
    "SOURCE_CODE" as source_code,
    "SOURCE_DISPLAY" as source_display,
    "SOURCE_SYSTEM" as source_system,
    "TARGET_SYSTEM" as target_system
from {{ source('olids', 'MEDICATION_ORDER') }}
