{{
    config(
        description="Raw layer (OLIDS stable layer - cleaned and filtered patient records). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.OLIDS.OBSERVATION \ndbt: source(''olids'', ''OBSERVATION'') \nColumns:\n  LDS_SOURCE_RECORD_ID -> lds_source_record_id\n  ID -> id\n  PATIENT_ID -> patient_id\n  PERSON_ID -> person_id\n  ENCOUNTER_ID -> encounter_id\n  PRACTITIONER_ID -> practitioner_id\n  PARENT_OBSERVATION_ID -> parent_observation_id\n  CLINICAL_EFFECTIVE_DATE -> clinical_effective_date\n  CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID -> clinical_effective_date_precision_source_concept_id\n  RESULT_VALUE -> result_value\n  RESULT_UNITS_SOURCE_CONCEPT_ID -> result_units_source_concept_id\n  RESULT_UNIT_CODE -> result_unit_code\n  RESULT_UNIT_DISPLAY -> result_unit_display\n  RESULT_DATE -> result_date\n  RESULT_TEXT -> result_text\n  IS_PROBLEM -> is_problem\n  IS_REVIEW -> is_review\n  PROBLEM_END_DATE -> problem_end_date\n  OBSERVATION_SOURCE_CONCEPT_ID -> observation_source_concept_id\n  MAPPED_CONCEPT_ID -> mapped_concept_id\n  MAPPED_CONCEPT_CODE -> mapped_concept_code\n  MAPPED_CONCEPT_DISPLAY -> mapped_concept_display\n  SOURCE_CODE -> source_code\n  SOURCE_DISPLAY -> source_display\n  SOURCE_SYSTEM -> source_system\n  TARGET_SYSTEM -> target_system\n  AGE_AT_EVENT -> age_at_event\n  AGE_AT_EVENT_BABY -> age_at_event_baby\n  AGE_AT_EVENT_NEONATE -> age_at_event_neonate\n  EPISODICITY_SOURCE_CONCEPT_ID -> episodicity_source_concept_id\n  IS_PRIMARY -> is_primary\n  DATE_RECORDED -> date_recorded\n  IS_PROBLEM_DELETED -> is_problem_deleted\n  IS_CONFIDENTIAL -> is_confidential\n  PUBLISHER_ORGANISATION_ID -> publisher_organisation_id\n  PROVIDER_ORGANISATION_ID -> provider_organisation_id\n  AUTHOR_ORGANISATION_ID -> author_organisation_id\n  PUBLISHER_ORGANISATION_CODE -> publisher_organisation_code\n  PATIENT_SHARD_ID -> patient_shard_id\n  PERSON_SHARD_ID -> person_shard_id\n  LDS_SOURCE_RECORD_SHARD_ID -> lds_source_record_shard_id\n  LDS_IS_DELETED -> lds_is_deleted\n  LDS_ID -> lds_id\n  LDS_BUSINESS_KEY -> lds_business_key\n  LDS_SOURCE_DATASET_ID -> lds_source_dataset_id\n  LDS_CDM_EVENT_ID -> lds_cdm_event_id\n  LDS_VERSIONER_EVENT_ID -> lds_versioner_event_id\n  LDS_DATETIME_FIRST_ACQUIRED -> lds_datetime_first_acquired\n  LDS_DATETIME_UPDATE_ACQUIRED -> lds_datetime_update_acquired\n  LDS_START_DATETIME -> lds_start_datetime\n  LDS_LAKEHOUSE_DATE_PROCESSED -> lds_lakehouse_date_processed\n  LDS_LAKEHOUSE_DATETIME_UPDATED -> lds_lakehouse_datetime_updated"
    )
}}
select
    "LDS_SOURCE_RECORD_ID" as lds_source_record_id,
    "ID" as id,
    "PATIENT_ID" as patient_id,
    "PERSON_ID" as person_id,
    "ENCOUNTER_ID" as encounter_id,
    "PRACTITIONER_ID" as practitioner_id,
    "PARENT_OBSERVATION_ID" as parent_observation_id,
    "CLINICAL_EFFECTIVE_DATE" as clinical_effective_date,
    "CLINICAL_EFFECTIVE_DATE_PRECISION_SOURCE_CONCEPT_ID" as clinical_effective_date_precision_source_concept_id,
    "RESULT_VALUE" as result_value,
    "RESULT_UNITS_SOURCE_CONCEPT_ID" as result_units_source_concept_id,
    "RESULT_UNIT_CODE" as result_unit_code,
    "RESULT_UNIT_DISPLAY" as result_unit_display,
    "RESULT_DATE" as result_date,
    "RESULT_TEXT" as result_text,
    "IS_PROBLEM" as is_problem,
    "IS_REVIEW" as is_review,
    "PROBLEM_END_DATE" as problem_end_date,
    "OBSERVATION_SOURCE_CONCEPT_ID" as observation_source_concept_id,
    "MAPPED_CONCEPT_ID" as mapped_concept_id,
    "MAPPED_CONCEPT_CODE" as mapped_concept_code,
    "MAPPED_CONCEPT_DISPLAY" as mapped_concept_display,
    "SOURCE_CODE" as source_code,
    "SOURCE_DISPLAY" as source_display,
    "SOURCE_SYSTEM" as source_system,
    "TARGET_SYSTEM" as target_system,
    "AGE_AT_EVENT" as age_at_event,
    "AGE_AT_EVENT_BABY" as age_at_event_baby,
    "AGE_AT_EVENT_NEONATE" as age_at_event_neonate,
    "EPISODICITY_SOURCE_CONCEPT_ID" as episodicity_source_concept_id,
    "IS_PRIMARY" as is_primary,
    "DATE_RECORDED" as date_recorded,
    "IS_PROBLEM_DELETED" as is_problem_deleted,
    "IS_CONFIDENTIAL" as is_confidential,
    "PUBLISHER_ORGANISATION_ID" as publisher_organisation_id,
    "PROVIDER_ORGANISATION_ID" as provider_organisation_id,
    "AUTHOR_ORGANISATION_ID" as author_organisation_id,
    "PUBLISHER_ORGANISATION_CODE" as publisher_organisation_code,
    "PATIENT_SHARD_ID" as patient_shard_id,
    "PERSON_SHARD_ID" as person_shard_id,
    "LDS_SOURCE_RECORD_SHARD_ID" as lds_source_record_shard_id,
    "LDS_IS_DELETED" as lds_is_deleted,
    "LDS_ID" as lds_id,
    "LDS_BUSINESS_KEY" as lds_business_key,
    "LDS_SOURCE_DATASET_ID" as lds_source_dataset_id,
    "LDS_CDM_EVENT_ID" as lds_cdm_event_id,
    "LDS_VERSIONER_EVENT_ID" as lds_versioner_event_id,
    "LDS_DATETIME_FIRST_ACQUIRED" as lds_datetime_first_acquired,
    "LDS_DATETIME_UPDATE_ACQUIRED" as lds_datetime_update_acquired,
    "LDS_START_DATETIME" as lds_start_datetime,
    "LDS_LAKEHOUSE_DATE_PROCESSED" as lds_lakehouse_date_processed,
    "LDS_LAKEHOUSE_DATETIME_UPDATED" as lds_lakehouse_datetime_updated
from {{ source('olids', 'OBSERVATION') }}
