-- Raw layer model for csds.CYP501CodedImm
-- Source: "DATA_LAKE"."CSDS"
-- Description: Community services dataset
-- This is a 1:1 passthrough from source with standardized column names
select
    "SK" as sk,
    "LOCAL PATIENT IDENTIFIER (EXTENDED)" as local_patient_identifier_extended,
    "IMMUNISATION DATE" as immunisation_date,
    "PROCEDURE SCHEME IN USE (COMMUNITY CARE)" as procedure_scheme_in_use_community_care,
    "PROCEDURE SCHEME IN USE" as procedure_scheme_in_use,
    "IMMUNISATION PROCEDURE (CLINICAL TERMINOLOGY)" as immunisation_procedure_clinical_terminology,
    "ORGANISATION IDENTIFIER (IMMUNISATION RESPONSIBLE ORGANISATION)" as organisation_identifier_immunisation_responsible_organisation,
    "ORGANISATION CODE (IMMUNISATION RESPONSIBLE ORGANISATION)" as organisation_code_immunisation_responsible_organisation,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP501 UNIQUE ID" as cyp501_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "AGE AT IMMUNISATION DATE" as age_at_immunisation_date,
    "SCHOOL YEAR AT IMMUNISATION DATE" as school_year_at_immunisation_date,
    "AGE AT IMMUNISATION DATE (YEARS)" as age_at_immunisation_date_years,
    "IC_AGE_AT_IMMUNISATION_DATE" as ic_age_at_immunisation_date,
    "RECORD START DATE" as record_start_date,
    "RECORD END DATE" as record_end_date,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (IMMUNISATION DATE)" as age_group_immunisation_date,
    "AGE BAND (IMMUNISATION DATE)" as age_band_immunisation_date,
    "MAPPED SNOMED CT PROCEDURE CODE" as mapped_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE CODE" as master_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE PREFERRED TERM" as master_snomed_ct_procedure_preferred_term,
    "MAPPED OPCS-4 PROCEDURE CODE" as mapped_opcs_4_procedure_code,
    "MAPPED OPCS-4 PROCEDURE DESCRIPTION" as mapped_opcs_4_procedure_description,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP501CodedImm') }}
