version: 2
sources:
- name: c_ltcs
  database: 'DEV__PUBLISHED_REPORTING__DIRECT_CARE' # Update to PROD database when moving to production
  schema: 'C_LTCS'
  description: C-LTCS tables
  tables:
  - name: 'MDT_LOOKUP'
    identifier: 'MDT_LOOKUP'
    columns:
    - name: PCN_CODE
      data_type: TEXT
    - name: DATE
      data_type: DATE
  - name: 'STATUS_LOG'
    identifier: 'STATUS_LOG'
    columns:
    - name: 	PATIENT_ID
      data_type: NUMBER
    - name: PCN_CODE
      data_type: TEXT
    - name: DATE
      data_type: DATE
    - name: ACTION
      data_type: TEXT
    - name: ACTION_DATE
      data_type: TIMESTAMP_TZ
    - name: CRITERIA
      data_type: TEXT
  - name: 'OP_OE_RATIO'
    identifier: 'OP_OE_RATIO'
    columns:
    - name: 	PATIENT_ID
      data_type: NUMBER
    - name: OE_RATIO
      data_type: NUMBER
    - name: PREDICTED
      data_type: NUMBER
    - name: OP_ATT_TOT_12MO
      data_type: NUMBER
