
SELECT
        PSEUDO_NHS_NUMBER,
        LA_CODE,
        LA_PERSON_UNIQUE_IDENTIFIER,
    	GP_PRACTICE_NAME,
    	GP_PRACTICE_CODE,
    	GENDER,
    	ETHNICITY,
    	CLIENT_TYPE,
    	PRIMARY_SUPPORT_REASON,
    	ACCOMMODATION_STATUS,
    	EMPLOYMENT_STATUS,
    	HAS_UNPAID_CARER,
    	AUTISM_SPECTRUM_DISORDER_ASD,
    	VISUAL_IMPAIRMENT,
    	HEARING_IMPAIRMENT,
    	DEMENTIA,
    	CLIENT_FUNDING_STATUS


    from {{ ref('raw_asc_cld_adult_social_care_cld') }}
