select
    age_bands,
    cost_centre_ods_code,
    cost_centre_sub_type,
    dispensed_pharmacy_lsoa,
    dispensed_pharmacy_ods_code,
    dispensed_pharmacy_type,
    exemption_code,
    item_actual_cost, --NB: raw cost is in pence
    item_count,
    item_id,
    item_nic,
    maternity_exemption_flag,
    dmic_pseudo_nhs_number as sk_patient_id,
    not_dispensed_indicator,
    paid_bnf_code,
    paid_bnf_name,
    paid_drug_strength,
    paid_quantity,
    paid_supplier_name,
    patient_age,
    patient_gpods,
    patient_gender,
    patient_la,
    patient_lsoa,
    prescriber_id,
    prescriber_type,
    private_prescription_indicator,
    processing_period_date
from {{ref('raw_epd_pc_meds')}}