SELECT SK_PATIENT_ID
 ,BOROUGH_RESIDENT AS BOROUGH_REGISTERED_OR_RESIDENT
FROM {{ref('dim_person_demographics')}} res
WHERE BOROUGH_RESIDENT IS NOT NULL

UNION

SELECT SK_PATIENT_ID
 ,BOROUGH_REGISTERED AS BOROUGH_REGISTERED_OR_RESIDENT
FROM {{ref('dim_person_demographics')}} res
WHERE BOROUGH_REGISTERED IS NOT NULL