-- Staging model for sus_ae.EncounterDetail
-- Source: "DATA_LAKE"."SUS_AE"
-- Description: SUS emergency care attendances and activity

select
    "SK_EncounterID" as sk_encounterid,
    "StartDate" as startdate,
    "EndDate" as enddate,
    "SK_ArrivalModeID" as sk_arrivalmodeid,
    "SK_AttendanceCategoryID" as sk_attendancecategoryid,
    "SK_AttendanceDisposalID" as sk_attendancedisposalid,
    "SK_IncidentLocationTypeID" as sk_incidentlocationtypeid,
    "SK_SourceOfReferralID" as sk_sourceofreferralid,
    "InitialAssessmentTime" as initialassessmenttime,
    "TreatmentTime" as treatmenttime,
    "AttendanceConclusionTime" as attendanceconclusiontime,
    "SK_AandEDepartmentNameID" as sk_aandedepartmentnameid,
    "PrimaryInvestigation" as primaryinvestigation,
    "PrimaryDiagnosis" as primarydiagnosis,
    "PrimaryTreatment" as primarytreatment,
    "DiagnosisSchemeICD" as diagnosisschemeicd,
    "PrimaryDiagnosisICD" as primarydiagnosisicd,
    "DiagnosisSchemeRead" as diagnosisschemeread,
    "PrimaryDiagnosisRead" as primarydiagnosisread,
    "DiagType" as diagtype,
    "InvestigationType" as investigationtype,
    "TreatmentType" as treatmenttype,
    "SK_ServiceProviderID" as sk_serviceproviderid,
    "SK_PatientID" as sk_patientid,
    "SK_StaffID" as sk_staffid,
    "EncounterStartDateTime" as encounterstartdatetime,
    "EncounterEndDateTime" as encounterenddatetime,
    "SK_CommissionerID" as sk_commissionerid,
    "Patient_group" as patient_group,
    "HRG4_Code" as hrg4_code,
    "DeleteEncounter" as deleteencounter,
    "SK_AgeBandID" as sk_agebandid,
    "SK_Commissioner_PCTID" as sk_commissioner_pctid,
    "Staff_Member_Code" as staff_member_code,
    "Unique_CDS_Identifier" as unique_cds_identifier,
    "SK_DepartmentTypeID" as sk_departmenttypeid,
    "PASHospitalNumber" as pashospitalnumber,
    "COMMISSIONER_SERIAL_NO" as commissioner_serial_no,
    "PROVIDER_REFERENCE_NO" as provider_reference_no,
    "AGREEMENT_LINE_NO" as agreement_line_no,
    "Local_Site_Code" as local_site_code,
    "AE_Attendance_No" as ae_attendance_no,
    "SK_Org_CommissionerID" as sk_org_commissionerid,
    "SK_Org_ServiceProviderID" as sk_org_serviceproviderid,
    "PbROrSEM" as pbrorsem,
    "CDS_Record_Type" as cds_record_type
from {{ source('sus_ae', 'EncounterDetail') }}
