-- Staging model for sus_apc.spell.critical_care_consolidated
-- Source: "DATA_LAKE"."SUS_UNIFIED_APC"
-- Description: SUS admitted patient care episodes and procedures

select
    "ROWNUMBER_ID" as rownumber_id,
    "PRIMARYKEY_ID" as primarykey_id,
    "CRITICAL_CARE_CONSOLIDATED_ID" as critical_care_consolidated_id,
    "identifier.local_identifier" as identifier_local_identifier,
    "identifier.sus_cc_period" as identifier_sus_cc_period,
    "identifier.submitted_on_episode" as identifier_submitted_on_episode,
    "identifier.cc_period_type" as identifier_cc_period_type,
    "identifier.cc_period_type_numeric" as identifier_cc_period_type_numeric,
    "admission.date" as admission_date,
    "admission.time" as admission_time,
    "admission.unit_function" as admission_unit_function,
    "admission.unit_bed_configuration" as admission_unit_bed_configuration,
    "admission.source" as admission_source,
    "admission.source_location" as admission_source_location,
    "discharge.date" as discharge_date,
    "discharge.time" as discharge_time,
    "discharge.status" as discharge_status,
    "discharge.location" as discharge_location,
    "organ_support_days.advanced_respiratory" as organ_support_days_advanced_respiratory,
    "organ_support_days.basic_respiratory" as organ_support_days_basic_respiratory,
    "organ_support_days.advanced_cardiovascular" as organ_support_days_advanced_cardiovascular,
    "organ_support_days.basic_cardiovascular" as organ_support_days_basic_cardiovascular,
    "organ_support_days.renal" as organ_support_days_renal,
    "organ_support_days.neurological" as organ_support_days_neurological,
    "organ_support_days.gastro_intestinal" as organ_support_days_gastro_intestinal,
    "organ_support_days.dermatological" as organ_support_days_dermatological,
    "organ_support_days.liver" as organ_support_days_liver,
    "organ_support_days.maximum_systems" as organ_support_days_maximum_systems,
    "intensity_support_days.level_2" as intensity_support_days_level_2,
    "intensity_support_days.level_3" as intensity_support_days_level_3,
    "admission.gestation_length_at_delivery" as admission_gestation_length_at_delivery,
    "admission.type" as admission_type,
    "discharge.ready_date" as discharge_ready_date,
    "discharge.ready_time" as discharge_ready_time,
    "discharge.destination" as discharge_destination,
    "dmicImportLogId" as dmicimportlogid
from {{ source('sus_apc', 'spell.critical_care_consolidated') }}
