-- Staging model for csds_simple.tblPatient
-- Source: "DATA_LAKE"."CSDS_SIMPLE"
-- Description: Community services dataset (simple)

select
    "Person_ID" as person_id,
    "Unique_service_request_identifier" as unique_service_request_identifier,
    "Pseudo_NHS_Number" as pseudo_nhs_number,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "NHS_number_status_indicator_code" as nhs_number_status_indicator_code,
    "Person_stated_gender_code" as person_stated_gender_code,
    "Age_of_patient_at_reporting_period_start_(Years)" as age_of_patient_at_reporting_period_start_years,
    "Age_of_patient_at_reporting_period_end_(Years)" as age_of_patient_at_reporting_period_end_years,
    "Ethnic_category" as ethnic_category,
    "Language_code_(Preferred)" as language_code_preferred,
    "Person_relationship_(Main_carer)" as person_relationship_main_carer,
    "Health_visitor_first_antenatal_visit_date" as health_visitor_first_antenatal_visit_date,
    "Looked_aftert_child_indicator" as looked_aftert_child_indicator,
    "Safeguarding_vulnerability_factors_indicator" as safeguarding_vulnerability_factors_indicator,
    "Constant_supervision_and_care_required_due_to_disability_indicator" as constant_supervision_and_care_required_due_to_disability_indicator,
    "Educational_assessment_outcome" as educational_assessment_outcome,
    "Preferred_death_location_discussed_indicator" as preferred_death_location_discussed_indicator,
    "Death_location_type_code_(Preferred)" as death_location_type_code_preferred,
    "Person_death_date" as person_death_date,
    "Death_location_type_code_(Actual)" as death_location_type_code_actual,
    "Death_not_at_preferred_location_reason" as death_not_at_preferred_location_reason,
    "NHS_number_status_indicator_code_(Mother)" as nhs_number_status_indicator_code_mother,
    "Postcode_district" as postcode_district,
    "Lower_super_output_area_(Residence)" as lower_super_output_area_residence,
    "Census_year" as census_year,
    "Local_authority_district_unitary_authority" as local_authority_district_unitary_authority,
    "County" as county,
    "Electoral_ward_of_usual_address" as electoral_ward_of_usual_address,
    "Organisation_code_(CCG_of_residence)" as organisation_code_ccg_of_residence,
    "Organisation_code_(Local_patient)" as organisation_code_local_patient,
    "Organisation_code_(Residence_responsibility)" as organisation_code_residence_responsibility,
    "Organisation_code_(Educational_establishment)" as organisation_code_educational_establishment,
    "Organisation_code_(Provider)" as organisation_code_provider,
    "ORGANISATION IDENTIFIER (SUB ICB LOCATION OF RESIDENCE)" as organisation_identifier_sub_icb_location_of_residence,
    "ORGANISATION IDENTIFIER (ICB OF RESIDENCE)" as organisation_identifier_icb_of_residence,
    "Valid_NHS_Number_Flag" as valid_nhs_number_flag,
    "Valid_Postcode_Flag" as valid_postcode_flag,
    "Record_Number" as record_number,
    "GP_Practice_(Latest)_DV" as gp_practice_latest_dv,
    "Accommodation_Status_Code_(Latest)_DV" as accommodation_status_code_latest_dv,
    "Accommodation_Status_Recorded_Date_(Latest)_DV" as accommodation_status_recorded_date_latest_dv,
    "Care_Plan_Type_(List)_DV" as care_plan_type_list_dv,
    "Care_Plan_Create_Date_(Latest)_DV" as care_plan_create_date_latest_dv,
    "Care_Plan_Implementation_Date_(Latest)_DV" as care_plan_implementation_date_latest_dv,
    "Care_Plan_Updated_Date_(Latest)_DV" as care_plan_updated_date_latest_dv,
    "Care_Plan_Agreed_By_(List)_DV" as care_plan_agreed_by_list_dv,
    "Care_Plan_Agreed_Date_(Latest)_DV" as care_plan_agreed_date_latest_dv,
    "Employment_Status_(Latest)_DV" as employment_status_latest_dv,
    "Employment_Status_Recorded_Date_(Latest)_DV" as employment_status_recorded_date_latest_dv,
    "Immunisations_Date_(Earliest)_DV" as immunisations_date_earliest_dv,
    "Immunisations_Date_(Latest)_DV" as immunisations_date_latest_dv,
    "Count_of_Immunisations_DV" as count_of_immunisations_dv,
    "Unique_count_of_Immunisation_date_recorded_DV" as unique_count_of_immunisation_date_recorded_dv,
    "Unique_count_of_clinical_coded_Immunisation_DV" as unique_count_of_clinical_coded_immunisation_dv,
    "Child_Immunisation_date_(Earliest)_DV" as child_immunisation_date_earliest_dv,
    "Child_Immunisation_date_(Latest)_DV" as child_immunisation_date_latest_dv,
    "Child_Count_of_Immunisations_DV" as child_count_of_immunisations_dv,
    "Child_Unique_count_of_Immunisation_date_recorded_DV" as child_unique_count_of_immunisation_date_recorded_dv,
    "Child_Unique_count_of_Immunisation_Type/Service_recorded_DV" as child_unique_count_of_immunisation_type_service_recorded_dv,
    "Special_Educational_Types_(List)_DV" as special_educational_types_list_dv,
    "Has_Special_Educational_Needs_DV" as has_special_educational_needs_dv,
    "Safeguarding_Vulnerability_Factors_Type_(List)_DV" as safeguarding_vulnerability_factors_type_list_dv,
    "Has Safeguarding Vulnerability Factors" as has_safeguarding_vulnerability_factors,
    "Child_Protection_Plan_Start_Date_(Latest)_DV" as child_protection_plan_start_date_latest_dv,
    "Child_Protection_Plan_End_Date_(Latest)_DV" as child_protection_plan_end_date_latest_dv,
    "Care_Protection_Plan_Status_DV" as care_protection_plan_status_dv,
    "Disability_Codes_(List)_DV" as disability_codes_list_dv,
    "Disability_Status_DV" as disability_status_dv,
    "Has_Recording_of_SocPerCircumstances_DV" as has_recording_of_soc_per_circumstances_dv
from {{ source('csds_simple', 'tblPatient') }}
