-- Staging model for csds.CYP202CareActivity
-- Source: "DATA_LAKE"."CSDS"
-- Description: Community services dataset

select
    "SK" as sk,
    "CARE ACTIVITY IDENTIFIER" as care_activity_identifier,
    "CARE CONTACT IDENTIFIER" as care_contact_identifier,
    "COMMUNITY CARE ACTIVITY TYPE" as community_care_activity_type,
    "COMMUNITY CARE ACTIVITY TYPE CODE" as community_care_activity_type_code,
    "CARE PROFESSIONAL LOCAL IDENTIFIER" as care_professional_local_identifier,
    "CLINICAL CONTACT DURATION OF CARE ACTIVITY" as clinical_contact_duration_of_care_activity,
    "PROCEDURE SCHEME IN USE (COMMUNITY CARE)" as procedure_scheme_in_use_community_care,
    "PROCEDURE SCHEME IN USE" as procedure_scheme_in_use,
    "CODED PROCEDURE (CLINICAL TERMINOLOGY)" as coded_procedure_clinical_terminology,
    "FINDING SCHEME IN USE (COMMUNITY CARE)" as finding_scheme_in_use_community_care,
    "FINDING SCHEME IN USE" as finding_scheme_in_use,
    "CODED FINDING (CODED CLINICAL ENTRY)" as coded_finding_coded_clinical_entry,
    "OBSERVATION SCHEME IN USE (COMMUNITY CARE)" as observation_scheme_in_use_community_care,
    "OBSERVATION SCHEME IN USE" as observation_scheme_in_use,
    "CODED OBSERVATION (CLINICAL TERMINOLOGY)" as coded_observation_clinical_terminology,
    "OBSERVATION VALUE" as observation_value,
    "UCUM UNIT OF MEASUREMENT" as ucum_unit_of_measurement,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP202 UNIQUE ID" as cyp202_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UNIQUE CARE CONTACT IDENTIFIER" as unique_care_contact_identifier,
    "UNIQUE CARE ACTIVITY IDENTIFIER" as unique_care_activity_identifier,
    "UNIQUE MONTH ID" as unique_month_id,
    "DERIVED BREASTFEEDING STATUS (MASTER)" as derived_breastfeeding_status_master,
    "MAPPED SNOMED CT PROCEDURE CODE" as mapped_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE CODE" as master_snomed_ct_procedure_code,
    "MASTER SNOMED CT PROCEDURE PREFERRED TERM" as master_snomed_ct_procedure_preferred_term,
    "MAPPED OPCS-4 PROCEDURE CODE" as mapped_opcs_4_procedure_code,
    "MAPPED OPCS-4 PROCEDURE DESCRIPTION" as mapped_opcs_4_procedure_description,
    "MAPPED SNOMED CT FINDING CODE" as mapped_snomed_ct_finding_code,
    "MASTER SNOMED CT FINDING CODE" as master_snomed_ct_finding_code,
    "MASTER SNOMED CT FINDING PREFERRED TERM" as master_snomed_ct_finding_preferred_term,
    "MAPPED ICD-10 FINDING CODE" as mapped_icd_10_finding_code,
    "MASTER ICD-10 FINDING CODE" as master_icd_10_finding_code,
    "MASTER ICD-10 FINDING DESCRIPTION" as master_icd_10_finding_description,
    "MAPPED SNOMED CT OBSERVATION CODE" as mapped_snomed_ct_observation_code,
    "MASTER SNOMED CT OBSERVATION CODE" as master_snomed_ct_observation_code,
    "MASTER SNOMED CT OBSERVATION PREFERRED TERM" as master_snomed_ct_observation_preferred_term,
    "DERIVED PERSON HEIGHT" as derived_person_height,
    "DERIVED PERSON WEIGHT" as derived_person_weight,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicActivityDate" as dmic_activity_date,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "Unique_CareProfessionalId_Local" as unique_care_professional_id_local,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP202CareActivity') }}
