-- Staging model for csds.CYP201CareContact
-- Source: "DATA_LAKE"."CSDS"
-- Description: Community services dataset

select
    "SK" as sk,
    "CARE CONTACT IDENTIFIER" as care_contact_identifier,
    "SERVICE REQUEST IDENTIFIER" as service_request_identifier,
    "CARE PROFESSIONAL TEAM LOCAL IDENTIFIER" as care_professional_team_local_identifier,
    "CARE CONTACT DATE" as care_contact_date,
    "CARE CONTACT TIME" as care_contact_time,
    "ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)" as organisation_identifier_code_of_commissioner,
    "ORGANISATION CODE (CODE OF COMMISSIONER)" as organisation_code_code_of_commissioner,
    "ADMINISTRATIVE CATEGORY CODE" as administrative_category_code,
    "CLINICAL CONTACT DURATION OF CARE CONTACT" as clinical_contact_duration_of_care_contact,
    "CONSULTATION TYPE" as consultation_type,
    "CARE CONTACT SUBJECT" as care_contact_subject,
    "CONSULTATION MEDIUM USED" as consultation_medium_used,
    "CONSULTATION MECHANISM (COMMUNITY CARE)" as consultation_mechanism_community_care,
    "ACTIVITY LOCATION TYPE CODE" as activity_location_type_code,
    "ORGANISATION SITE IDENTIFIER (OF TREATMENT)" as organisation_site_identifier_of_treatment,
    "SITE CODE (OF TREATMENT)" as site_code_of_treatment,
    "GROUP THERAPY INDICATOR" as group_therapy_indicator,
    "ATTENDED OR DID NOT ATTEND CODE" as attended_or_did_not_attend_code,
    "ATTENDANCE STATUS" as attendance_status,
    "EARLIEST REASONABLE OFFER DATE" as earliest_reasonable_offer_date,
    "EARLIEST CLINICALLY APPROPRIATE DATE" as earliest_clinically_appropriate_date,
    "CARE CONTACT CANCELLATION DATE" as care_contact_cancellation_date,
    "CARE CONTACT CANCELLATION REASON" as care_contact_cancellation_reason,
    "REPLACEMENT APPOINTMENT DATE OFFERED" as replacement_appointment_date_offered,
    "REPLACEMENT APPOINTMENT BOOKED DATE" as replacement_appointment_booked_date,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP201 UNIQUE ID" as cyp201_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UNIQUE SERVICE REQUEST IDENTIFIER" as unique_service_request_identifier,
    "UNIQUE CARE PROFESSIONAL TEAM LOCAL IDENTIFIER" as unique_care_professional_team_local_identifier,
    "UNIQUE CARE CONTACT IDENTIFIER" as unique_care_contact_identifier,
    "AGE AT CARE CONTACT DATE" as age_at_care_contact_date,
    "TIME BETWEEN REFERRAL AND CARE CONTACT" as time_between_referral_and_care_contact,
    "CONTACT LOCATION DISTANCE FROM HOME" as contact_location_distance_from_home,
    "AGE AT CARE CONTACT DATE (YEARS)" as age_at_care_contact_date_years,
    "IC_AGE_AT_CARE_CONTACT_DATE" as ic_age_at_care_contact_date,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (CARE CONTACT DATE)" as age_group_care_contact_date,
    "DERIVED BODY MASS INDEX" as derived_body_mass_index,
    "AGE BAND (CARE CONTACT DATE)" as age_band_care_contact_date,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP201CareContact') }}
