{{
    config(
        materialized='view'
    )
}}

SELECT
BASE.PERSON_ID,
GENDER AS GENDER,
AGE_BAND_10Y,
AGE_BAND_5Y,
CASE WHEN AGE_BAND_5Y = '0-4'THEN 1
    WHEN  AGE_BAND_5Y = '5-9' THEN 2
    WHEN AGE_BAND_5Y = '10-14' THEN 3
    WHEN AGE_BAND_5Y = '15-19' THEN 4
    WHEN AGE_BAND_5Y = '20-24' THEN 5
    WHEN AGE_BAND_5Y = '25-29' THEN 6
    WHEN AGE_BAND_5Y = '30-34' THEN 7
    WHEN AGE_BAND_5Y = '35-39' THEN 8
    WHEN AGE_BAND_5Y = '40-44' THEN 9
    WHEN AGE_BAND_5Y = '45-49' THEN 10
    WHEN AGE_BAND_5Y = '50-54' THEN 11
    WHEN AGE_BAND_5Y = '55-59' THEN 12
    WHEN AGE_BAND_5Y = '60-64' THEN 13
    WHEN AGE_BAND_5Y = '65-69' THEN 14
    WHEN AGE_BAND_5Y = '70-74' THEN 15
    WHEN AGE_BAND_5Y = '75-79' THEN 16
    WHEN AGE_BAND_5Y = '80-84' THEN 17
    WHEN AGE_BAND_5Y = '85+'   THEN 18
        END AS AGE_BAND_5Y_SORT_KEY,
ETHNICITY_CATEGORY,
CASE WHEN ETHNICITY_CATEGORY= 'Asian' THEN 1
        WHEN ETHNICITY_CATEGORY= 'Black' THEN 2
        WHEN ETHNICITY_CATEGORY= 'White' THEN 3
        WHEN ETHNICITY_CATEGORY= 'Mixed' THEN 4
        WHEN ETHNICITY_CATEGORY= 'Other' THEN 5
        WHEN ETHNICITY_CATEGORY= 'Unknown' THEN 6
            END AS ETHNICITY_CATEGORY_SORT_KEY,
ETHNICITY_SUBCATEGORY,
MAIN_LANGUAGE,
CASE WHEN PATIENT_LSOA IS NULL THEN 'Unknown' ELSE PATIENT_LSOA END AS PATIENT_LSOA,
PATIENT_IMD_DECILE_19,
CASE WHEN PATIENT_IMD_QUINTILE_19 IS NULL THEN 'Unknown' ELSE PATIENT_IMD_QUINTILE_19 END AS PATIENT_IMD_QUINTILE_19,
CASE WHEN PATIENT_IMD_QUINTILE_19 = 'Least Deprived' THEN 1
        WHEN PATIENT_IMD_QUINTILE_19 = 'Second Least Deprived' THEN 2
        WHEN PATIENT_IMD_QUINTILE_19 = 'Third Most Deprived' THEN 3
        WHEN PATIENT_IMD_QUINTILE_19 = 'Second Most Deprived' THEN 4
        WHEN PATIENT_IMD_QUINTILE_19 = 'Most Deprived' THEN 5
            END AS PATIENT_IMD_QUINTILE_19_SORT_KEY,
NEIGHBOURHOOD_RESIDENT AS PATIENT_NEIGHBOURHOOD,
NEIGHBOURHOOD_REGISTERED AS PRACTICE_NEIGHBOURHOOD,
BOROUGH_REGISTERED AS PRACTICE_BOROUGH,
PCN_NAME,
BASE.PRACTICE_CODE,
BASE.PRACTICE_NAME,
PRACTICE_LSOA,
WARD_CODE,
WARD_NAME,
PRACTICE_IMD_QUINTILE_19,
CASE WHEN TOTAL_CONDITIONS > 0 THEN 'LTC patients' ELSE 'Non-LTC patients' END AS CONDITION_NAME,
CASE WHEN BASE.SMOKING_STATUS = 'Current Smoker' OR
            BASE.ALCOHOL_STATUS IN ('Higher Risk','Historical Alcohol Misuse Disorder','Active Alcohol Misuse Disorder','Increasing Risk','Possible Dependence') OR
            BASE.BMI_CATEGORY IN ('Obese Class I','Overweight','Obese Class II','Obese Class III') 
                THEN 'Patients with risk factor' 
                    ELSE 'Patients without risk factor' 
                        END AS RISK_FACTOR,
CASE WHEN AGE > 18 THEN 'Yes' ELSE 'No' END AS IS_PATIENT_19_AND_OVER,
CASE WHEN IS_ACTIVE = 'TRUE' THEN 'Yes' ELSE 'No' END AS IS_ACTIVE,
LISTSIZE.PRACTICE_NORMALISED_WEIGHTED_LIST_SIZE,
TOTAL_CONDITIONS AS TOTAL_LTC_CONDITIONS,
RISK_FACTOR_COUNT


FROM {{ ref('population_health_needs_base') }} BASE

LEFT JOIN {{ ref('stg_reference_gp_weighted_list_size') }} LISTSIZE
ON BASE.PRACTICE_CODE = LISTSIZE.PRACTICE_CODE

WHERE IS_ACTIVE = 'TRUE' 

GROUP BY ALL