version: 2

models:
  - name: covid_flu_dashboard_base_secondary_use
    description: |
      COVID and Flu Dashboard base table for secondary use.
      Filtered to exclude patients with Type 1 opt-outs via dim_person_secondary_use_allowed.
      See covid_flu_dashboard_base in published_reporting_direct_care for full details.

  - name: ltc_lcs_cf_dashboard_base_secondary_use
    description: |
      LTC/LCS Case Finding Dashboard base table for secondary use.
      Filtered to exclude patients with Type 1 opt-outs via dim_person_secondary_use_allowed.
      See ltc_lcs_cf_dashboard_base in published_reporting_direct_care for full details.

  - name: population_health_needs_base_secondary_use
    description: |
      Population health needs base table for secondary use.
      Filtered to exclude patients with Type 1 opt-outs via dim_person_secondary_use_allowed.
      See population_health_needs_base in published_reporting_direct_care for full details.

  - name: population_health_needs_base_readable_secondary_use
    description: |
      Population health needs base readable table for secondary use.
      Filtered to exclude patients with Type 1 opt-outs via dim_person_secondary_use_allowed.
      See population_health_needs_base_readable in published_reporting_direct_care for full details.

  - name: childhood_imms_person_level_child_dm_secondary_use
    description: |
      Childhood immunisations person-level data for children, for secondary use.
      Filtered to exclude patients with Type 1 opt-outs via dim_person_secondary_use_allowed.
      See childhood_imms_person_level_child_dm in published_reporting_direct_care for full details.

  - name: childhood_imms_person_level_adolescent_dm_secondary_use
    description: |
      Childhood immunisations person-level data for adolescents, for secondary use.
      Filtered to exclude patients with Type 1 opt-outs via dim_person_secondary_use_allowed.
      See childhood_imms_person_level_adolescent_dm in published_reporting_direct_care for full details.

  - name: metadata_refresh_dates_secondary_use
    description: |
      Centralised metadata tracking for OLIDS data freshness and table update timestamps (secondary use).

      Provides two types of metrics:
      - **Global data refresh**: Consensus date where ≥150 practices have uploaded data (excludes future dates and filters out stale practices)
      - **Table refresh**: Last modified timestamps for all OLIDS tables in REPORTING and PUBLISHED_REPORTING databases

      Table timestamps are retrieved from Snowflake's INFORMATION_SCHEMA, ensuring accuracy regardless of partial dbt runs.

      See metadata_refresh_dates in published_reporting_direct_care for column documentation.
