-- Staging model for csds.CYP101Referral
-- Source: "DATA_LAKE"."CSDS"
-- Description: Community services dataset

select
    "SK" as sk,
    "SERVICE REQUEST IDENTIFIER" as service_request_identifier,
    "LOCAL PATIENT IDENTIFIER (EXTENDED)" as local_patient_identifier_extended,
    "ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)" as organisation_identifier_code_of_commissioner,
    "ORGANISATION CODE (CODE OF COMMISSIONER)" as organisation_code_code_of_commissioner,
    "REFERRAL REQUEST RECEIVED DATE" as referral_request_received_date,
    "REFERRAL REQUEST RECEIVED TIME" as referral_request_received_time,
    "NHS SERVICE AGREEMENT LINE IDENTIFIER" as nhs_service_agreement_line_identifier,
    "NHS SERVICE AGREEMENT LINE NUMBER" as nhs_service_agreement_line_number,
    "SOURCE OF REFERRAL FOR COMMUNITY" as source_of_referral_for_community,
    "ORGANISATION IDENTIFIER (REFERRING ORGANISATION)" as organisation_identifier_referring_organisation,
    "ORGANISATION IDENTIFIER (REFERRING)" as organisation_identifier_referring,
    "REFERRING ORGANISATION CODE" as referring_organisation_code,
    "REFERRING CARE PROFESSIONAL STAFF GROUP (COMMUNITY CARE)" as referring_care_professional_staff_group_community_care,
    "REFERRING CARE PROFESSIONAL STAFF GROUP (MENTAL HEALTH AND COMMUNITY CARE)" as referring_care_professional_staff_group_mental_health_and_community_care,
    "PRIORITY TYPE CODE" as priority_type_code,
    "PRIMARY REASON FOR REFERRAL (COMMUNITY CARE)" as primary_reason_for_referral_community_care,
    "SERVICE DISCHARGE DATE" as service_discharge_date,
    "DISCHARGE LETTER ISSUED DATE (COMMUNITY CARE)" as discharge_letter_issued_date_community_care,
    "DISCHARGE LETTER ISSUED DATE (MENTAL HEALTH AND COMMUNITY CARE)" as discharge_letter_issued_date_mental_health_and_community_care,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP101 UNIQUE ID" as cyp101_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "UNIQUE SERVICE REQUEST IDENTIFIER" as unique_service_request_identifier,
    "AGE AT SERVICE REFERRAL RECEIVED DATE" as age_at_service_referral_received_date,
    "AGE AT SERVICE REFERRAL DISCHARGE" as age_at_service_referral_discharge,
    "AGE AT SERVICE REFERRAL RECEIVED DATE (YEARS)" as age_at_service_referral_received_date_years,
    "IC_AGE_AT_SERVICE_REFERRAL_RECEIVED_DATE" as ic_age_at_service_referral_received_date,
    "AGE AT SERVICE REFERRAL DISCHARGE (YEARS)" as age_at_service_referral_discharge_years,
    "IC_AGE_AT_SERVICE_REFERRAL_DISCHARGE" as ic_age_at_service_referral_discharge,
    "RECORD START DATE" as record_start_date,
    "RECORD END DATE" as record_end_date,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (REFERRAL RECEIVED DATE)" as age_group_referral_received_date,
    "AGE GROUP (SERVICE DISCHARGE DATE)" as age_group_service_discharge_date,
    "AGE BAND (REFERRAL RECEIVED DATE)" as age_band_referral_received_date,
    "AGE BAND (SERVICE DISCHARGE DATE)" as age_band_service_discharge_date,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "dmIcbCommissioner" as dm_icb_commissioner,
    "dmSubIcbCommissioner" as dm_sub_icb_commissioner,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP101Referral') }}
