-- Staging model for reference_analyst_managed.EFI2_RULES
-- Source: "DATA_LAKE__NCL"."ANALYST_MANAGED"
-- Description: Analyst-managed reference datasets and business rules

select
    "CODE" as code,
    "DEFICIT" as deficit,
    "DEFICIT_TYPE" as deficit_type,
    "TIME_CONSTRAINT_DAYS" as time_constraint_days,
    "TIME_CONSTRAINT_TYPE" as time_constraint_type,
    "TIME_CONSTRAINT_DESCRIPTION" as time_constraint_description,
    "MIN_AGE" as min_age,
    "AGE_RESTRICTION_DESCRIPTION" as age_restriction_description,
    "CATEGORY_NAME" as category_name,
    "CATEGORY_ORDER" as category_order,
    "CATEGORY_RANGE_START" as category_range_start,
    "CATEGORY_RANGE_END" as category_range_end,
    "CATEGORY_DESCRIPTION" as category_description,
    "THRESHOLD_VALUE" as threshold_value,
    "THRESHOLD_COMPARATOR" as threshold_comparator,
    "THRESHOLD_DESCRIPTION" as threshold_description,
    "THRESHOLD_UNIT" as threshold_unit,
    "THRESHOLD_TYPE" as threshold_type,
    "READINGS_REQUIRED" as readings_required,
    "READINGS_TIMEFRAME" as readings_timeframe,
    "SUPERSEDES" as supersedes,
    "SUPERSEDED_BY" as superseded_by,
    "HIERARCHY_LEVEL" as hierarchy_level,
    "RESOLUTION_TEST" as resolution_test,
    "RESOLUTION_THRESHOLD" as resolution_threshold,
    "RESOLUTION_UNIT" as resolution_unit,
    "RESOLUTION_GENDER_SPECIFIC" as resolution_gender_specific,
    "RESOLUTION_MALE_THRESHOLD" as resolution_male_threshold,
    "RESOLUTION_FEMALE_THRESHOLD" as resolution_female_threshold,
    "VALIDATION_RULE" as validation_rule,
    "VALIDATION_DESCRIPTION" as validation_description,
    "EFI2_COEFFICIENT" as efi2_coefficient,
    "EFI2_TRANSFORMED_COEFFICIENT" as efi2_transformed_coefficient,
    "EFI_PLUS_FALLS_COEFFICIENT" as efi_plus_falls_coefficient,
    "EFI_PLUS_CARE_HOME_COEFFICIENT" as efi_plus_care_home_coefficient,
    "EFI_PLUS_MORTALITY_COEFFICIENT" as efi_plus_mortality_coefficient,
    "EFI_PLUS_HOME_CARE_COEFFICIENT" as efi_plus_home_care_coefficient,
    "SOURCE_INSTRUCTION" as source_instruction,
    "RULE_PRIORITY" as rule_priority
from {{ source('reference_analyst_managed', 'EFI2_RULES') }}
