-- Staging model for csds.CYP001MPI
-- Source: "DATA_LAKE"."CSDS"
-- Description: Community services dataset

select
    "SK" as sk,
    "LOCAL PATIENT IDENTIFIER (EXTENDED)" as local_patient_identifier_extended,
    "ORGANISATION IDENTIFIER (LOCAL PATIENT IDENTIFIER)" as organisation_identifier_local_patient_identifier,
    "ORGANISATION CODE (LOCAL PATIENT IDENTIFIER)" as organisation_code_local_patient_identifier,
    "ORGANISATION IDENTIFIER (RESIDENCE RESPONSIBILITY)" as organisation_identifier_residence_responsibility,
    "ORGANISATION CODE (RESIDENCE RESPONSIBILITY)" as organisation_code_residence_responsibility,
    "ORGANISATION IDENTIFIER (EDUCATIONAL ESTABLISHMENT)" as organisation_identifier_educational_establishment,
    "ORGANISATION CODE (EDUCATIONAL ESTABLISHMENT)" as organisation_code_educational_establishment,
    "NHS NUMBER STATUS INDICATOR CODE" as nhs_number_status_indicator_code,
    "DateOfBirth Pseudo" as date_of_birth_pseudo,
    "Postcode Pseudo" as postcode_pseudo,
    "PERSON STATED GENDER CODE" as person_stated_gender_code,
    "ETHNIC CATEGORY" as ethnic_category,
    "ETHNIC CATEGORY 2021" as ethnic_category_2021,
    "LANGUAGE CODE (PREFERRED)" as language_code_preferred,
    "PERSON RELATIONSHIP (MAIN CARER)" as person_relationship_main_carer,
    "HEALTH VISITOR FIRST ANTENATAL VISIT DATE" as health_visitor_first_antenatal_visit_date,
    "LOOKED AFTER CHILD INDICATOR" as looked_after_child_indicator,
    "SAFEGUARDING VULNERABILITY FACTORS INDICATOR" as safeguarding_vulnerability_factors_indicator,
    "CONSTANT SUPERVISION AND CARE REQUIRED DUE TO DISABILITY INDICATOR" as constant_supervision_and_care_required_due_to_disability_indicator,
    "EDUCATIONAL ASSESSMENT OUTCOME" as educational_assessment_outcome,
    "PREFERRED DEATH LOCATION DISCUSSED INDICATOR" as preferred_death_location_discussed_indicator,
    "PERSON AT RISK OF UNEXPECTED DEATH INDICATOR" as person_at_risk_of_unexpected_death_indicator,
    "DEATH LOCATION TYPE CODE (PREFERRED)" as death_location_type_code_preferred,
    "PERSON DEATH DATE" as person_death_date,
    "DEATH LOCATION TYPE CODE (ACTUAL)" as death_location_type_code_actual,
    "DEATH NOT AT PREFERRED LOCATION REASON" as death_not_at_preferred_location_reason,
    "NHS NUMBER STATUS INDICATOR CODE (MOTHER)" as nhs_number_status_indicator_code_mother,
    "EFFECTIVE FROM" as effective_from,
    "RECORD NUMBER" as record_number,
    "CYP001 UNIQUE ID" as cyp001_unique_id,
    "ORGANISATION IDENTIFIER (CODE OF PROVIDER)" as organisation_identifier_code_of_provider,
    "ORGANISATION CODE (PROVIDER)" as organisation_code_provider,
    "PERSON ID" as person_id,
    "UNIQUE CSDS ID (PATIENT)" as unique_csds_id_patient,
    "UNIQUE SUBMISSION ID" as unique_submission_id,
    "BSP UNIQUE ID" as bsp_unique_id,
    "VALID NHS NUMBER FLAG" as valid_nhs_number_flag,
    "VALID POSTCODE FLAG" as valid_postcode_flag,
    "POSTCODE DISTRICT" as postcode_district,
    "Postcode_Default Pseudo" as postcode_default_pseudo,
    "LOWER SUPER OUTPUT AREA (RESIDENCE)" as lower_super_output_area_residence,
    "LOWER SUPER OUTPUT AREA (RESIDENCE) 2011" as lower_super_output_area_residence_2011,
    "CENSUS YEAR" as census_year,
    "COUNTY" as county,
    "LOCAL AUTHORITY DISTRICT/UNITARY AUTHORITY" as local_authority_district_unitary_authority,
    "ELECTORAL WARD OF USUAL ADDRESS" as electoral_ward_of_usual_address,
    "AGE OF PATIENT AT REPORTING PERIOD START (DAYS)" as age_of_patient_at_reporting_period_start_days,
    "AGE OF PATIENT AT REPORTING PERIOD END (DAYS)" as age_of_patient_at_reporting_period_end_days,
    "AGE AT DEATH (DAYS)" as age_at_death_days,
    "ORGANISATION IDENTIFIER (CCG OF RESIDENCE)" as organisation_identifier_ccg_of_residence,
    "ORGANISATION CODE (CCG OF RESIDENCE)" as organisation_code_ccg_of_residence,
    "AGE OF PATIENT AT REPORTING PERIOD START (YEARS)" as age_of_patient_at_reporting_period_start_years,
    "IC_AGE_OF_PATIENT_AT_RP_START" as ic_age_of_patient_at_rp_start,
    "AGE OF PATIENT AT REPORTING PERIOD END (YEARS)" as age_of_patient_at_reporting_period_end_years,
    "IC_AGE_OF_PATIENT_AT_RP_END" as ic_age_of_patient_at_rp_end,
    "AGE AT DEATH (YEARS)" as age_at_death_years,
    "IC_AGE_AT_DEATH" as ic_age_at_death,
    "RECORD START DATE" as record_start_date,
    "RECORD END DATE" as record_end_date,
    "UNIQUE MONTH ID" as unique_month_id,
    "AGE GROUP (REPORTING PERIOD START DATE)" as age_group_reporting_period_start_date,
    "AGE GROUP (REPORTING PERIOD END DATE)" as age_group_reporting_period_end_date,
    "AGE GROUP (DEATH DATE)" as age_group_death_date,
    "AGE BAND (REPORTING PERIOD START DATE)" as age_band_reporting_period_start_date,
    "AGE BAND (REPORTING PERIOD END DATE)" as age_band_reporting_period_end_date,
    "AGE BAND (DEATH DATE)" as age_band_death_date,
    "ORGANISATION IDENTIFIER (SUB ICB LOCATION OF RESIDENCE)" as organisation_identifier_sub_icb_location_of_residence,
    "ORGANISATION IDENTIFIER (ICB OF RESIDENCE)" as organisation_identifier_icb_of_residence,
    "dmicImportLogId" as dmic_import_log_id,
    "dmicEthnicCategoryGroup" as dmic_ethnic_category_group,
    "dmicSystemId" as dmic_system_id,
    "dmicCCGCode" as dmic_ccg_code,
    "dmicCCG" as dmic_ccg,
    "Unique_LocalPatientId" as unique_local_patient_id,
    "UniqueCYPHS_ID_Patient" as unique_cyphs_id_patient,
    "dmIcbResidenceSubmitted" as dm_icb_residence_submitted,
    "dmSubIcbResidenceSubmitted" as dm_sub_icb_residence_submitted,
    "dmCommissionerDerivationReason" as dm_commissioner_derivation_reason,
    "FILE TYPE" as file_type,
    "REPORTING PERIOD START DATE" as reporting_period_start_date,
    "REPORTING PERIOD END DATE" as reporting_period_end_date
from {{ source('csds', 'CYP001MPI') }}
