-- Staging layer: ECDS emergency care attendances.
-- 1:1 with raw_sus_ecds_emergency_care - column renaming and light
-- standardisation only. Joins to the date dimension and to the ECDS child
-- tables (diagnoses, investigations, treatments, comorbidities, referrals,
-- alcohol/drug involvement, mental health legal status, expected treatment
-- times) are applied in int_ecds_consolidated.

SELECT

--Identifiers & Data Management Derived Fields
"PRIMARYKEY_ID" AS "Record_Identifier"
,"ROWNUMBER_ID" AS "Row_Number_ID"
,"PATIENT_NHS_NUMBER_VALUE_PSEUDO" AS "Patient_ID"
,"SYSTEM_TRANSACTION_CDS_UNIQUE_IDENTIFIER" AS "CDS_Unique_Identifier"
,"PATIENT_LOCAL_PATIENT_IDENTIFIER_VALUE" AS "Local_Patient_Identifier"
,"COMMISSIONING_SERVICE_AGREEMENT_PROVIDER_REFERENCE_NUMBER" AS "Provider_Reference_Number"
,"COMMISSIONING_NATIONAL_PRICING_COSTING_PERIOD" AS "Applicable_Costing_Period"

--Patient Detail Fields
,CASE
WHEN "PATIENT_PATIENT_TYPE" = 'ADU' THEN 'Adult'
WHEN "PATIENT_PATIENT_TYPE" = 'CHI' THEN 'Child'
ELSE "PATIENT_PATIENT_TYPE"
END AS "Patient_Type"
,"PATIENT_AGE_AT_ARRIVAL" AS "Age_At_Arrival"
,"PATIENT_USUAL_ADDRESS_INDEX_OF_MULTIPLE_DEPRIVATION_DECILE" AS "Index_Of_Multiple_Deprivation_Decile"
,"PATIENT_RESIDENCE_CCG_FROM_PATIENT_POSTCODE" AS "Commissioner_Code_From_Postcode"
,"PATIENT_STATED_GENDER" AS "Gender"
,"PATIENT_ETHNIC_CATEGORY" AS "Ethnic_Category"
,"PATIENT_GP_REGISTRATION_GENERAL_PRACTITIONER" AS "GP_Code"
,"PATIENT_GP_REGISTRATION_GENERAL_PRACTICE" AS "GP_Practice_Code"

--Attendance Fields
,LEFT("COMMISSIONING_SERVICE_AGREEMENT_PROVIDER", 3) AS "Provider_Code"
,"ATTENDANCE_LOCATION_SITE" AS "Site_Code"
,"COMMISSIONING_SERVICE_AGREEMENT_COMMISSIONER" AS "Commissioner_Code"
,"PATIENT_USUAL_ADDRESS_POSTCODE_DISTRICT" AS "Postcode_District_Usual_Address"
,"PATIENT_USUAL_ADDRESS_LSOA_11" AS "LSOA_11_Usual_Address"
,CASE
WHEN "ATTENDANCE_LOCATION_SITE" = 'RQM25' THEN '03'
ELSE "ATTENDANCE_LOCATION_DEPARTMENT_TYPE"
END AS "Department_Type"
,"ATTENDANCE_ARRIVAL_DATE" AS "Arrival_Date"
,"ATTENDANCE_ARRIVAL_TIME" AS "Arrival_Time"
,"ATTENDANCE_ARRIVAL_ARRIVAL_MODE_CODE" AS "Arrival_Mode"
,"ATTENDANCE_ARRIVAL_ATTENDANCE_CATEGORY" AS "Attendance_Category"
,"ATTENDANCE_ARRIVAL_PLANNED" AS "Arrival_Planned"
,"ATTENDANCE_ARRIVAL_AMBULANCE_INCIDENT_NUMBER" AS "Ambulance_Incident_Number"
,"ATTENDANCE_ARRIVAL_CONVEYING_AMBULANCE_TRUST" AS "Conveying_Ambulance_Trust_Code"
,"ATTENDANCE_ARRIVAL_AMBULANCE_CARE_CONTACT_IDENTIFIER" AS "Ambulance_Care_Contact_Identifier"
,"ATTENDANCE_ARRIVAL_ATTENDANCE_SOURCE_CODE" AS "Attendance_Source"
,"ATTENDANCE_ARRIVAL_ATTENDANCE_SOURCE_ORGANISATION" AS "Attendance_Source_For_Organisation_Site_Identifier"
,"ATTENDANCE_INITIAL_ASSESSMENT_DATE" AS "Initial_Assessment_Date"
,"ATTENDANCE_INITIAL_ASSESSMENT_TIME" AS "Initial_Assessment_Time"
,"ATTENDANCE_INITIAL_ASSESSMENT_TIME_SINCE_ARRIVAL" AS "Initial_Assessment_Time_Since_Arrival"
,"ATTENDANCE_SEEN_FOR_TREATMENT_DATE" AS "Seen_For_Treatment_Date"
,"ATTENDANCE_SEEN_FOR_TREATMENT_TIME" AS "Seen_For_Treatment_Time"
,"ATTENDANCE_SEEN_FOR_TREATMENT_TIME_SINCE_ARRIVAL" AS "Seen_For_Treatment_Time_Since_Arrival"
,"ATTENDANCE_CONCLUSION_DATE" AS "Conclusion_Date"
,"ATTENDANCE_CONCLUSION_TIME" AS "Conclusion_Time"
,"ATTENDANCE_CONCLUSION_TIME_SINCE_ARRIVAL" AS "Conclusion_Time_Since_Arrival"
,"ATTENDANCE_DEPARTURE_DATE" AS "Departure_Date"
,"ATTENDANCE_DEPARTURE_TIME" AS "Departure_Time"
,"ATTENDANCE_DEPARTURE_TIME_SINCE_ARRIVAL" AS "Departure_Time_Since_Arrival"
,"ATTENDANCE_DECISION_TO_ADMIT_DATE" AS "Decided_To_Admit_Date"
,"ATTENDANCE_DECISION_TO_ADMIT_TIME" AS "Decided_To_Admit_Time"
,"ATTENDANCE_DECISION_TO_ADMIT_TIME_SINCE_ARRIVAL" AS "Decided_To_Admit_Time_Since_Arrival"
,"ATTENDANCE_DECISION_TO_ADMIT_TREATMENT_FUNCTION_CODE" AS "Decided_To_Admit_Treatment_Function_Code"
,"ATTENDANCE_DECISION_TO_ADMIT_RECEIVING_SITE" AS "Organisation_Site_Identifier_Discharge_From_Emergency_Care"
,"ATTENDANCE_DISCHARGE_STATUS_CODE" AS "Discharge_Status"
,"ATTENDANCE_DISCHARGE_DESTINATION_CODE" AS "Discharge_Destination"
,"ATTENDANCE_DISCHARGE_FOLLOW_UP_CODE" AS "Discharge_Follow_Up"
,"ATTENDANCE_DISCHARGE_INFORMATION_GIVEN_CODE" AS "Discharge_Information_Given"
,"ATTENDANCE_CLINICALLY_READY_TO_PROCEED_TIMESTAMP" AS "Clinically_Ready_To_Proceed_Time"
,"ATTENDANCE_CLINICALLY_READY_TO_PROCEED_TIME_SINCE_ARRIVAL" AS "Clinically_Ready_To_Proceed_Time_Since_Arrival"

--Clinical Fields
,"CLINICAL_CHIEF_COMPLAINT_CODE" AS "Chief_Complaint"
,"CLINICAL_CHIEF_COMPLAINT_IS_INJURY_RELATED" AS "Chief_Complaint_Is_Injury_Related"
,"CLINICAL_ACUITY_CODE" AS "Acuity"
,"COMMISSIONING_GROUPING_HEALTH_RESOURCE_GROUP" AS "HRG_Code"
,"COMMISSIONING_NATIONAL_PRICING_EXCLUDED" AS "National_Tariff_Excluded"
,"COMMISSIONING_NATIONAL_PRICING_TARIFF" AS "National_Tariff"
,"COMMISSIONING_NATIONAL_PRICING_FINAL_PRICE" AS "National_Tariff_Final_Price"
,"COMMISSIONING_NATIONAL_PRICING_MARKET_FORCES_FACTOR" AS "MFF_Factor"
,"COMMISSIONING_NATIONAL_PRICING_MARKET_FORCES_ADJUSTMENT" AS "MFF_Adjustment"
,"CLINICAL_INJURY_INTENT_CODE" AS "Injury_Intent"
,"CLINICAL_INJURY_MECHANISM_CODE" AS "Injury_Mechanism"
,"CLINICAL_INJURY_PLACE_TYPE" AS "Place_Of_Injury"
,"CLINICAL_INJURY_DATE" AS "Injury_Date"
,"CLINICAL_INJURY_TIME" AS "Injury_Time"
,"CLINICAL_DISEASE_NOTIFICATION_CODE" AS "Disease_Notification"

--Referral Fields
,"REFERRAL_PATIENT_PATHWAY_IDENTIFIER_VALUE_PSEUDO" AS "Patient_Pathway_Identifier"
,"REFERRAL_PERIOD_STATUS" AS "Referral_To_Treatment_Period_Status"
,"REFERRAL_PERIOD_START_DATE" AS "Referral_To_Treatment_Period_Start_Date"
,"REFERRAL_PERIOD_END_DATE" AS "Referral_To_Treatment_Period_End_Date"
,"REFERRAL_WAITING_TIME_MEASUREMENT_TYPE" AS "Waiting_Time_Measurement_Type"

--zDerived Fields
,"COMMISSIONING_SERVICE_AGREEMENT_PROVIDER" AS "zProvider_Code"

--zBusinessRules
,CAST(CASE
--CURRENT UTC/WICs IN NWL
WHEN "ATTENDANCE_LOCATION_SITE" = 'RQM25' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_CW'					--Chelsea & Westminster UTC (Co-located)
WHEN "ATTENDANCE_LOCATION_SITE" = 'AD915' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_EHT'				--Ealing Hospital UTC (Totally)
WHEN "ATTENDANCE_LOCATION_SITE" = 'R1K14' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_EHT'				--Ealing Hospital UTC (Trust)
WHEN "ATTENDANCE_LOCATION_SITE" = 'AD904' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_THH'				--Hillingdon Hospital UTC (Totally)
WHEN "ATTENDANCE_LOCATION_SITE" = 'RAS01' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_THH'				--Hillingdon Hospital UTC (Trust)
WHEN "ATTENDANCE_LOCATION_SITE" = 'AD906' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_NP'					--Northwick Park Hospital UTC (Totally)
WHEN "ATTENDANCE_LOCATION_SITE" = 'R1K11' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_NP'					--Northwick Park Hospital UTC (Trust)
WHEN "ATTENDANCE_LOCATION_SITE" = 'NLO21' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_SMH'				--St Mary's UTC (Totally)
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYJ01' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_SMH_Streamed'		--St Mary's UTC (Trust)
WHEN "ATTENDANCE_LOCATION_SITE" = 'AD918' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_CMX'				--Central Middlesex Hospital UTC (Totally)
WHEN "ATTENDANCE_LOCATION_SITE" = 'R1K12' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_CMX'				--Central Middlesex Hospital UTC (Trust)
WHEN "ATTENDANCE_LOCATION_SITE" = 'RY901' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_WMX'				--West Middlesex Hospital UTC (Totally / submitted by HRCH)
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYX24' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" IN ('03', '04') THEN 'WIC_EDG'		--Edgware Walk-In Centre
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYX23' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" IN ('03', '04') THEN 'WIC_FINCH'		--Finchley Walk-In Centre
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYX11' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" IN ('03', '04') THEN 'WIC_PGREEN'	--Parsons Green Walk-In Centre
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYX02' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" IN ('03', '04') THEN 'WIC_SOHO'		--Soho Walk-In-Centre
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYX01' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" IN ('03', '04') THEN 'WIC_STCharles'	--St Charles Walk-In Centre
WHEN "ATTENDANCE_LOCATION_SITE" = 'RAS02' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'MIU_MV'					--Mount Vernon Hospital
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYJ02' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_CX'					--Charing Cross UTC

--NOT CURRENTLY SUBMITTING:
WHEN "ATTENDANCE_LOCATION_SITE" = 'RYJ03' AND "ATTENDANCE_LOCATION_DEPARTMENT_TYPE" = '03' THEN 'UTC_HH'					--Hammersmith Hospital UTC
ELSE NULL
END AS VARCHAR(50)) AS zBusinessRule

FROM {{ ref('raw_sus_ecds_emergency_care') }} 