{{
    config(
        description="Raw layer (Providers submissions from PID environment via MESH). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.LOCAL_PROVIDER_FLOWS.DEMOGRAPHICS \ndbt: source(''local_provider_flows'', ''DEMOGRAPHICS'') \nColumns:\n  METADATA_FILE_PATH -> metadata_file_path\n  METADATA_FILE_ROW_NUMBER -> metadata_file_row_number\n  METADATA_RECORD_INGESTION_TIMESTAMP -> metadata_record_ingestion_timestamp\n  METADATA_FILE_CONTENT_KEY -> metadata_file_content_key\n  METADATA_FILE_LAST_MODIFIED -> metadata_file_last_modified\n  DeleteInd -> delete_ind\n  PersonID -> person_id\n  Version -> version\n  NHSNumber -> nhs_number\n  MRN -> mrn\n  MRNAssigningAuthority -> mrn_assigning_authority\n  Surname -> surname\n  FirstName -> first_name\n  MiddleName -> middle_name\n  BirthDate -> birth_date\n  GenderCodeID -> gender_code_id\n  GenderCodeSystemID -> gender_code_system_id\n  GenderDisplay -> gender_display\n  EthnicityCodeID -> ethnicity_code_id\n  EthnicityCodeSystemID -> ethnicity_code_system_id\n  EthnicityDisplay -> ethnicity_display\n  MaritalStatusCodeID -> marital_status_code_id\n  MaritalStatusCodeSystemID -> marital_status_code_system_id\n  MaritalStatusDisplay -> marital_status_display\n  ReligionCodeID -> religion_code_id\n  ReligionCodeSystemID -> religion_code_system_id\n  ReligionDisplay -> religion_display\n  DeceasedInd -> deceased_ind\n  DeathDate -> death_date\n  CauseOfDeathCodeID -> cause_of_death_code_id\n  CauseOfDeathCodeSystemID -> cause_of_death_code_system_id\n  CauseOfDeathDisplay -> cause_of_death_display\n  PrimaryLanguageCodeID -> primary_language_code_id\n  PrimaryLanguageCodeSystemID -> primary_language_code_system_id\n  PrimaryLanguageDisplay -> primary_language_display\n  StreetAddress1 -> street_address1\n  StreetAddress2 -> street_address2\n  City -> city\n  PostalCode -> postal_code\n  CountryCodeID -> country_code_id\n  CountryCodeSystemID -> country_code_system_id\n  CountryDisplay -> country_display\n  PrimaryPhoneNumber -> primary_phone_number\n  PrimaryPhoneNumberUseCodeID -> primary_phone_number_use_code_id\n  PrimaryPhoneNumberUseCodeSystemID -> primary_phone_number_use_code_system_id\n  PrimaryPhoneNumberUseDisplay -> primary_phone_number_use_display\n  SecondaryPhoneNumber -> secondary_phone_number\n  SecondaryPhoneNumberUseCodeID -> secondary_phone_number_use_code_id\n  SecondaryPhoneNumberUseCodeSystemID -> secondary_phone_number_use_code_system_id\n  SecondaryPhoneNumberUseDisplay -> secondary_phone_number_use_display\n  PrimaryEmailAddress -> primary_email_address\n  PrimaryEmailAddressUseCodeID -> primary_email_address_use_code_id\n  PrimaryEmailAddressUseCodeSystemID -> primary_email_address_use_code_system_id\n  PrimaryEmailAddressUseDisplay -> primary_email_address_use_display\n  SecondaryEmailAddress -> secondary_email_address\n  SecondaryEmailAddressUseCodeID -> secondary_email_address_use_code_id\n  SecondaryEmailAddressUseCodeSystemID -> secondary_email_address_use_code_system_id\n  SecondaryEmailAddressUseDisplay -> secondary_email_address_use_display\n  RegisteredGPIdentifier -> registered_gp_identifier\n  RegisteredGPIdentifierType -> registered_gp_identifier_type\n  RegisteredGPDisplay -> registered_gp_display\n  RegisteredGPStartDate -> registered_gp_start_date\n  RegisteredGPEndDate -> registered_gp_end_date"
    )
}}
select
    "METADATA_FILE_PATH" as metadata_file_path,
    "METADATA_FILE_ROW_NUMBER" as metadata_file_row_number,
    "METADATA_RECORD_INGESTION_TIMESTAMP" as metadata_record_ingestion_timestamp,
    "METADATA_FILE_CONTENT_KEY" as metadata_file_content_key,
    "METADATA_FILE_LAST_MODIFIED" as metadata_file_last_modified,
    "DeleteInd" as delete_ind,
    "PersonID" as person_id,
    "Version" as version,
    "NHSNumber" as nhs_number,
    "MRN" as mrn,
    "MRNAssigningAuthority" as mrn_assigning_authority,
    "Surname" as surname,
    "FirstName" as first_name,
    "MiddleName" as middle_name,
    "BirthDate" as birth_date,
    "GenderCodeID" as gender_code_id,
    "GenderCodeSystemID" as gender_code_system_id,
    "GenderDisplay" as gender_display,
    "EthnicityCodeID" as ethnicity_code_id,
    "EthnicityCodeSystemID" as ethnicity_code_system_id,
    "EthnicityDisplay" as ethnicity_display,
    "MaritalStatusCodeID" as marital_status_code_id,
    "MaritalStatusCodeSystemID" as marital_status_code_system_id,
    "MaritalStatusDisplay" as marital_status_display,
    "ReligionCodeID" as religion_code_id,
    "ReligionCodeSystemID" as religion_code_system_id,
    "ReligionDisplay" as religion_display,
    "DeceasedInd" as deceased_ind,
    "DeathDate" as death_date,
    "CauseOfDeathCodeID" as cause_of_death_code_id,
    "CauseOfDeathCodeSystemID" as cause_of_death_code_system_id,
    "CauseOfDeathDisplay" as cause_of_death_display,
    "PrimaryLanguageCodeID" as primary_language_code_id,
    "PrimaryLanguageCodeSystemID" as primary_language_code_system_id,
    "PrimaryLanguageDisplay" as primary_language_display,
    "StreetAddress1" as street_address1,
    "StreetAddress2" as street_address2,
    "City" as city,
    "PostalCode" as postal_code,
    "CountryCodeID" as country_code_id,
    "CountryCodeSystemID" as country_code_system_id,
    "CountryDisplay" as country_display,
    "PrimaryPhoneNumber" as primary_phone_number,
    "PrimaryPhoneNumberUseCodeID" as primary_phone_number_use_code_id,
    "PrimaryPhoneNumberUseCodeSystemID" as primary_phone_number_use_code_system_id,
    "PrimaryPhoneNumberUseDisplay" as primary_phone_number_use_display,
    "SecondaryPhoneNumber" as secondary_phone_number,
    "SecondaryPhoneNumberUseCodeID" as secondary_phone_number_use_code_id,
    "SecondaryPhoneNumberUseCodeSystemID" as secondary_phone_number_use_code_system_id,
    "SecondaryPhoneNumberUseDisplay" as secondary_phone_number_use_display,
    "PrimaryEmailAddress" as primary_email_address,
    "PrimaryEmailAddressUseCodeID" as primary_email_address_use_code_id,
    "PrimaryEmailAddressUseCodeSystemID" as primary_email_address_use_code_system_id,
    "PrimaryEmailAddressUseDisplay" as primary_email_address_use_display,
    "SecondaryEmailAddress" as secondary_email_address,
    "SecondaryEmailAddressUseCodeID" as secondary_email_address_use_code_id,
    "SecondaryEmailAddressUseCodeSystemID" as secondary_email_address_use_code_system_id,
    "SecondaryEmailAddressUseDisplay" as secondary_email_address_use_display,
    "RegisteredGPIdentifier" as registered_gp_identifier,
    "RegisteredGPIdentifierType" as registered_gp_identifier_type,
    "RegisteredGPDisplay" as registered_gp_display,
    "RegisteredGPStartDate" as registered_gp_start_date,
    "RegisteredGPEndDate" as registered_gp_end_date
from {{ source('local_provider_flows', 'DEMOGRAPHICS') }}
