{{
    config(
        description="Raw layer (Providers submissions from PID environment via MESH). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.LOCAL_PROVIDER_FLOWS.MEDICATION \ndbt: source(''local_provider_flows'', ''MEDICATION'') \nColumns:\n  METADATA_FILE_PATH -> metadata_file_path\n  METADATA_FILE_ROW_NUMBER -> metadata_file_row_number\n  METADATA_RECORD_INGESTION_TIMESTAMP -> metadata_record_ingestion_timestamp\n  METADATA_FILE_CONTENT_KEY -> metadata_file_content_key\n  METADATA_FILE_LAST_MODIFIED -> metadata_file_last_modified\n  DeleteInd -> delete_ind\n  MedicationID -> medication_id\n  Version -> version\n  PersonID -> person_id\n  EncounterID -> encounter_id\n  DrugCodeID -> drug_code_id\n  DrugCodeSystemID -> drug_code_system_id\n  DrugDisplay -> drug_display\n  StartDate -> start_date\n  StopDate -> stop_date\n  RouteCodeID -> route_code_id\n  RouteCodeSystemID -> route_code_system_id\n  RouteDisplay -> route_display\n  FrequencyCodeID -> frequency_code_id\n  FrequencyCodeSystemID -> frequency_code_system_id\n  FrequencyDisplay -> frequency_display\n  DoseStrengthAmount -> dose_strength_amount\n  DoseStrengthUnitCodeID -> dose_strength_unit_code_id\n  DoseStrengthUnitCodeSystemID -> dose_strength_unit_code_system_id\n  DoseStrengthUnitDisplay -> dose_strength_unit_display\n  DoseVolumeAmount -> dose_volume_amount\n  DoseVolumeUnitCodeID -> dose_volume_unit_code_id\n  DoseVolumeUnitCodeSystemID -> dose_volume_unit_code_system_id\n  DoseVolumeUnitDisplay -> dose_volume_unit_display\n  DoseQuantity -> dose_quantity\n  DoseQuantityUnitCodeID -> dose_quantity_unit_code_id\n  DoseQuantityUnitCodeSystemID -> dose_quantity_unit_code_system_id\n  DoseQuantityUnitDisplay -> dose_quantity_unit_display\n  PatientInstructions -> patient_instructions\n  OrderStatusCodeID -> order_status_code_id\n  OrderStatusCodeSystemID -> order_status_code_system_id\n  OrderStatusDisplay -> order_status_display\n  OrderDetailLine -> order_detail_line\n  PrescribingProviderID -> prescribing_provider_id\n  PrescribingProviderSurname -> prescribing_provider_surname\n  PrescribingProviderGivenName -> prescribing_provider_given_name\n  PrescribingProviderMiddleName -> prescribing_provider_middle_name\n  PrescribingProviderFullName -> prescribing_provider_full_name"
    )
}}
select
    "METADATA_FILE_PATH" as metadata_file_path,
    "METADATA_FILE_ROW_NUMBER" as metadata_file_row_number,
    "METADATA_RECORD_INGESTION_TIMESTAMP" as metadata_record_ingestion_timestamp,
    "METADATA_FILE_CONTENT_KEY" as metadata_file_content_key,
    "METADATA_FILE_LAST_MODIFIED" as metadata_file_last_modified,
    "DeleteInd" as delete_ind,
    "MedicationID" as medication_id,
    "Version" as version,
    "PersonID" as person_id,
    "EncounterID" as encounter_id,
    "DrugCodeID" as drug_code_id,
    "DrugCodeSystemID" as drug_code_system_id,
    "DrugDisplay" as drug_display,
    "StartDate" as start_date,
    "StopDate" as stop_date,
    "RouteCodeID" as route_code_id,
    "RouteCodeSystemID" as route_code_system_id,
    "RouteDisplay" as route_display,
    "FrequencyCodeID" as frequency_code_id,
    "FrequencyCodeSystemID" as frequency_code_system_id,
    "FrequencyDisplay" as frequency_display,
    "DoseStrengthAmount" as dose_strength_amount,
    "DoseStrengthUnitCodeID" as dose_strength_unit_code_id,
    "DoseStrengthUnitCodeSystemID" as dose_strength_unit_code_system_id,
    "DoseStrengthUnitDisplay" as dose_strength_unit_display,
    "DoseVolumeAmount" as dose_volume_amount,
    "DoseVolumeUnitCodeID" as dose_volume_unit_code_id,
    "DoseVolumeUnitCodeSystemID" as dose_volume_unit_code_system_id,
    "DoseVolumeUnitDisplay" as dose_volume_unit_display,
    "DoseQuantity" as dose_quantity,
    "DoseQuantityUnitCodeID" as dose_quantity_unit_code_id,
    "DoseQuantityUnitCodeSystemID" as dose_quantity_unit_code_system_id,
    "DoseQuantityUnitDisplay" as dose_quantity_unit_display,
    "PatientInstructions" as patient_instructions,
    "OrderStatusCodeID" as order_status_code_id,
    "OrderStatusCodeSystemID" as order_status_code_system_id,
    "OrderStatusDisplay" as order_status_display,
    "OrderDetailLine" as order_detail_line,
    "PrescribingProviderID" as prescribing_provider_id,
    "PrescribingProviderSurname" as prescribing_provider_surname,
    "PrescribingProviderGivenName" as prescribing_provider_given_name,
    "PrescribingProviderMiddleName" as prescribing_provider_middle_name,
    "PrescribingProviderFullName" as prescribing_provider_full_name
from {{ source('local_provider_flows', 'MEDICATION') }}
