{{
    config(
        description="Raw layer (Providers submissions from PID environment via MESH). 1:1 passthrough with cleaned column names. \nSource: DATA_LAKE.LOCAL_PROVIDER_FLOWS.ENCOUNTER \ndbt: source(''local_provider_flows'', ''ENCOUNTER'') \nColumns:\n  METADATA_FILE_PATH -> metadata_file_path\n  METADATA_FILE_ROW_NUMBER -> metadata_file_row_number\n  METADATA_RECORD_INGESTION_TIMESTAMP -> metadata_record_ingestion_timestamp\n  METADATA_FILE_CONTENT_KEY -> metadata_file_content_key\n  METADATA_FILE_LAST_MODIFIED -> metadata_file_last_modified\n  DeleteInd -> delete_ind\n  EncounterID -> encounter_id\n  Version -> version\n  PersonID -> person_id\n  ActualServiceDate -> actual_service_date\n  HospitalisationStartDate -> hospitalisation_start_date\n  DischargeDate -> discharge_date\n  VisitTypeCodeID -> visit_type_code_id\n  VisitTypeCodeSystemID -> visit_type_code_system_id\n  VisitTypeDisplay -> visit_type_display\n  AdmissionTypeCodeID -> admission_type_code_id\n  AdmissionTypeCodeSystemID -> admission_type_code_system_id\n  AdmissionTypeDisplay -> admission_type_display\n  DischargeDispositionCodeID -> discharge_disposition_code_id\n  DischargeDispositionCodeSystemID -> discharge_disposition_code_system_id\n  DischargeDispositionDisplay -> discharge_disposition_display\n  DischargeToDisplay -> discharge_to_display\n  FacilityID -> facility_id\n  FacilityDisplay -> facility_display\n  BuildingID -> building_id\n  BuildingDisplay -> building_display\n  NurseUnitID -> nurse_unit_id\n  NurseUnitDisplay -> nurse_unit_display\n  RoomID -> room_id\n  RoomDisplay -> room_display\n  BedID -> bed_id\n  BedDisplay -> bed_display\n  ServiceCodeID -> service_code_id\n  ServiceCodeSystemID -> service_code_system_id\n  ServiceDisplay -> service_display\n  AdmissionSourceCodeID -> admission_source_code_id\n  AdmissionSourceCodeSystemID -> admission_source_code_system_id\n  AdmissionSourceDisplay -> admission_source_display\n  StatusCodeID -> status_code_id\n  StatusCodeSystemID -> status_code_system_id\n  StatusDisplay -> status_display\n  ReasonForVisitCodeID -> reason_for_visit_code_id\n  ReasonForVisitCodeSystemID -> reason_for_visit_code_system_id\n  ReasonForVisitDisplay -> reason_for_visit_display\n  ServiceProviderOrgName -> service_provider_org_name\n  ServiceProviderOrgID -> service_provider_org_id\n  PartOfEncounterID -> part_of_encounter_id\n  ParticipantID -> participant_id\n  ParticipantTypeCodeID -> participant_type_code_id\n  ParticipantTypeCodeSystemID -> participant_type_code_system_id\n  ParticipantTypeDisplay -> participant_type_display\n  ParticipantSurname -> participant_surname\n  ParticipantGivenName -> participant_given_name\n  ParticipantMiddleName -> participant_middle_name\n  ParticipantFullName -> participant_full_name"
    )
}}
select
    "METADATA_FILE_PATH" as metadata_file_path,
    "METADATA_FILE_ROW_NUMBER" as metadata_file_row_number,
    "METADATA_RECORD_INGESTION_TIMESTAMP" as metadata_record_ingestion_timestamp,
    "METADATA_FILE_CONTENT_KEY" as metadata_file_content_key,
    "METADATA_FILE_LAST_MODIFIED" as metadata_file_last_modified,
    "DeleteInd" as delete_ind,
    "EncounterID" as encounter_id,
    "Version" as version,
    "PersonID" as person_id,
    "ActualServiceDate" as actual_service_date,
    "HospitalisationStartDate" as hospitalisation_start_date,
    "DischargeDate" as discharge_date,
    "VisitTypeCodeID" as visit_type_code_id,
    "VisitTypeCodeSystemID" as visit_type_code_system_id,
    "VisitTypeDisplay" as visit_type_display,
    "AdmissionTypeCodeID" as admission_type_code_id,
    "AdmissionTypeCodeSystemID" as admission_type_code_system_id,
    "AdmissionTypeDisplay" as admission_type_display,
    "DischargeDispositionCodeID" as discharge_disposition_code_id,
    "DischargeDispositionCodeSystemID" as discharge_disposition_code_system_id,
    "DischargeDispositionDisplay" as discharge_disposition_display,
    "DischargeToDisplay" as discharge_to_display,
    "FacilityID" as facility_id,
    "FacilityDisplay" as facility_display,
    "BuildingID" as building_id,
    "BuildingDisplay" as building_display,
    "NurseUnitID" as nurse_unit_id,
    "NurseUnitDisplay" as nurse_unit_display,
    "RoomID" as room_id,
    "RoomDisplay" as room_display,
    "BedID" as bed_id,
    "BedDisplay" as bed_display,
    "ServiceCodeID" as service_code_id,
    "ServiceCodeSystemID" as service_code_system_id,
    "ServiceDisplay" as service_display,
    "AdmissionSourceCodeID" as admission_source_code_id,
    "AdmissionSourceCodeSystemID" as admission_source_code_system_id,
    "AdmissionSourceDisplay" as admission_source_display,
    "StatusCodeID" as status_code_id,
    "StatusCodeSystemID" as status_code_system_id,
    "StatusDisplay" as status_display,
    "ReasonForVisitCodeID" as reason_for_visit_code_id,
    "ReasonForVisitCodeSystemID" as reason_for_visit_code_system_id,
    "ReasonForVisitDisplay" as reason_for_visit_display,
    "ServiceProviderOrgName" as service_provider_org_name,
    "ServiceProviderOrgID" as service_provider_org_id,
    "PartOfEncounterID" as part_of_encounter_id,
    "ParticipantID" as participant_id,
    "ParticipantTypeCodeID" as participant_type_code_id,
    "ParticipantTypeCodeSystemID" as participant_type_code_system_id,
    "ParticipantTypeDisplay" as participant_type_display,
    "ParticipantSurname" as participant_surname,
    "ParticipantGivenName" as participant_given_name,
    "ParticipantMiddleName" as participant_middle_name,
    "ParticipantFullName" as participant_full_name
from {{ source('local_provider_flows', 'ENCOUNTER') }}
