{{
    config(
        materialized='table',
        cluster_by=['person_id'],
        tags=['smi_registry']
        )
}}

--SMI REGISTER BASE POPULATION

select
dem.PERSON_ID
,ID.HX_FLAKE
,dem.SK_PATIENT_ID
,dem.AGE
,dem.AGE_BAND_5Y
,dem.AGE_BAND_NHS
,dem.GENDER
,CASE
WHEN dem.ETHNICITY_CATEGORY = 'Not Recorded' THEN 'Unknown'
ELSE dem.ETHNICITY_CATEGORY END AS ETHNICITY_CATEGORY
,CASE 
WHEN dem.ETHNICITY_CATEGORY = 'Asian' THEN 1
WHEN dem.ETHNICITY_CATEGORY = 'Black' THEN 2
WHEN dem.ETHNICITY_CATEGORY = 'Mixed' THEN 3
WHEN dem.ETHNICITY_CATEGORY = 'Other' THEN 4
WHEN dem.ETHNICITY_CATEGORY = 'White' THEN 5
WHEN dem.ETHNICITY_CATEGORY = 'Unknown' THEN 6
WHEN dem.ETHNICITY_CATEGORY = 'Not Recorded' THEN 6
END AS ETHCAT_ORDER 
,CASE
WHEN dem.ETHNICITY_SUBCATEGORY in ('Not Recorded','Not stated','Not Stated','Recorded Not Known','Refused') THEN 'Unknown'
ELSE dem.ETHNICITY_SUBCATEGORY END AS ETHNICITY_SUBCATEGORY
,CASE 
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Bangladeshi' THEN 1
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Chinese' THEN 2
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Indian' THEN 3
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Pakistani' THEN 4
WHEN dem.ETHNICITY_SUBCATEGORY = 'Asian: Other Asian' THEN 5
WHEN dem.ETHNICITY_SUBCATEGORY = 'Black: African' THEN 6
WHEN dem.ETHNICITY_SUBCATEGORY = 'Black: Caribbean' THEN 7
WHEN dem.ETHNICITY_SUBCATEGORY = 'Black: Other Black' THEN 8
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: White and Asian' THEN 9
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: White and Black African' THEN 10
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: White and Black Caribbean' THEN 11
WHEN dem.ETHNICITY_SUBCATEGORY = 'Mixed: Other Mixed' THEN 12
WHEN dem.ETHNICITY_SUBCATEGORY = 'Other: Arab' THEN 13
WHEN dem.ETHNICITY_SUBCATEGORY = 'Other: Other' THEN 14
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: British' THEN 15
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: Irish' THEN 16
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: Traveller' THEN 17
WHEN dem.ETHNICITY_SUBCATEGORY = 'White: Other White' THEN 18
WHEN dem.ETHNICITY_SUBCATEGORY = 'Unknown' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Not Recorded' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Not stated' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Not Stated' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Recorded Not Known' THEN 19
WHEN dem.ETHNICITY_SUBCATEGORY = 'Refused' THEN 19
END AS ETHSUBCAT_ORDER
,dem.ETHNICITY_GRANULAR
--switch to IMD25
,COALESCE(dem.IMD_QUINTILE_25, 'Unknown') AS IMD_QUINTILE
,CASE 
WHEN dem.IMD_QUINTILE_25 = 'Most Deprived' THEN 1
WHEN dem.IMD_QUINTILE_25 = 'Second Most Deprived' THEN 2
WHEN dem.IMD_QUINTILE_25 = 'Third Most Deprived' THEN 3
WHEN dem.IMD_QUINTILE_25 = 'Second Least Deprived' THEN 4
WHEN dem.IMD_QUINTILE_25 = 'Least Deprived' THEN 5
ELSE 6 END AS IMDQUINTILE_ORDER
,dem.IMD_DECILE_25 AS IMD_DECILE
,CASE 
WHEN dem.MAIN_LANGUAGE = 'Pushto' THEN 'Pashto' 
WHEN dem.MAIN_LANGUAGE in ('Makaton sign language','Sign language','British Sign Language') THEN 'Sign language'
WHEN dem.MAIN_LANGUAGE = 'Not Recorded' THEN 'Unknown'
ELSE dem.MAIN_LANGUAGE END AS MAIN_LANGUAGE
,dem.INTERPRETER_NEEDED
,dem.INTERPRETER_TYPE
,CASE WHEN HOM.PERSON_ID IS NOT NULL THEN TRUE ELSE FALSE END AS IS_HOMELESS
,dem.BOROUGH_REGISTERED AS PRACTICE_BOROUGH 
,dem.NEIGHBOURHOOD_REGISTERED AS PRACTICE_NEIGHBOURHOOD
,dem.PCN_NAME AS PRIMARY_CARE_NETWORK
,dem.PRACTICE_NAME 
,dem.PRACTICE_CODE
,COALESCE(la.LAD25_NM,'Unknown') as RESIDENTIAL_BOROUGH
,COALESCE(dem.NEIGHBOURHOOD_RESIDENT,'Unknown') as RESIDENTIAL_NEIGHBOURHOOD
,dem.WARD_CODE
,dem.WARD_NAME
,dem.LSOA_CODE_21
,CASE WHEN la.RESIDENT_FLAG IS NULL THEN 'Unknown'
ELSE la.RESIDENT_FLAG END as RESIDENTIAL_LOC
,ltc.HAS_CORONARY_HEART_DISEASE as HAS_CHD
,ltc.HAS_CHRONIC_KIDNEY_DISEASE as HAS_CKD
,ltc.HAS_DIABETES 
,ltc.HAS_COPD
,ltc.HAS_HYPERTENSION as HAS_HYP
,ltc.HAS_STROKE_TIA as HAS_STIA
,ltc.HAS_HEART_FAILURE as HAS_HF
,ltc.HAS_PERIPHERAL_ARTERIAL_DISEASE as HAS_PAD
,smi.IS_ON_LITHIUM
,smi.HAS_ACTIVE_SMI_DIAGNOSIS
FROM {{ ref('dim_person_demographics') }} dem 
INNER JOIN {{ ref('fct_person_smi_register') }} smi using (PERSON_ID)
LEFT JOIN {{ ref('dim_person_conditions') }} ltc using (PERSON_ID)
LEFT JOIN {{ ref('person_pseudo') }} AS ID  using (PERSON_ID)
LEFT JOIN {{ ref('stg_reference_lsoa21_ward25_lad25') }} la on la.LSOA21_CD = dem.LSOA_CODE_21
LEFT JOIN {{ ref('dim_person_homeless') }} hom using (PERSON_ID)
where dem.is_active = TRUE
